microsoft/accessibility-insights-windows

Channels/Production/release_info.json
This is ti update release info file to v1.1.0795.01 for testing GitHub auto-update mechanism towards CSUN
=> Update release info JSON to v1.1.0795.01

src/AccessibilityInsights.SharedUx/Controls/HierarchyControl.xaml, src/AccessibilityInsights.SharedUx/Controls/ScannerResultControl.xaml, src/AccessibilityInsights.SharedUx/Controls/TestTabs/AutomatedChecksControl.xaml, src/AccessibilityInsights.SharedUx/Properties/Resources.Designer.cs, src/AccessibilityInsights.SharedUx/Properties/Resources.resx, src/AccessibilityInsights/AccessibilityInsights.csproj, src/AccessibilityInsights/Modes/LiveModeControl.xaml
- add issue icon.
- change button text to "File issue".
- fix fabric icon changed by mistake.
=> UX file issue icon

src/AccessibilityInsights.DesktopTests/DesktopTests.csproj, src/AccessibilityInsights.DesktopTests/Telemetry/LoggerUnitTests.cs
based on env variable FAKES_SUPPORTED, exclude tests if they require fakes
=> Excluding specific tests in DesktopTests if they require fakes

src/AccessibilityInsights.SharedUx/Controls/SettingsTabs/ConnectionControl.xaml, src/AccessibilityInsights.SharedUx/Controls/SettingsTabs/ConnectionControl.xaml.cs, src/AccessibilityInsights.SharedUx/FileBug/IssueReporterManager.cs, src/AccessibilityInsights.SharedUx/Settings/ConfigurationConstants.cs, src/AccessibilityInsights.SharedUx/Settings/ConfigurationModel.cs
- Handle case where connection config is null in ConnectionControl.
- Re-selected saved issue reporter
- Fix serialization issues with Guid
=> Improve integration with new issue filing interfaces

docs/NewProject.md
This docs change fixes a typo referenced in #203
=> fix typo in NewProject.md

docs/AddUnitTests.md, src/AccessibilityInsights.SharedUxTests/FileBug/FileBugActionTests.cs, src/AccessibilityInsights.SharedUxTests/Settings/InstallationInfoTests.cs, src/AccessibilityInsights.SharedUxTests/SharedUxTests.csproj
This documentation includes how and why to include/exclude Fakes when working in the Accessibility Insights solution.
=> Adding documentation about excluding Fakes.

src/AccessibilityInsights.SharedUx/Properties/Resources.Designer.cs, src/AccessibilityInsights.SharedUx/Properties/Resources.resx, src/AccessibilityInsights/Properties/Resources.Designer.cs, src/AccessibilityInsights/Properties/Resources.resx
Update UIA to UI Automation in UI and Name automation property.
=> Update UIA to UI Automation in UI and also Name Automation Property.

src/AccessibilityInsights.Extensions.GitHub/ConfigurationModelControl.xaml.cs, src/AccessibilityInsights.Extensions.GitHub/Extensions.GitHub.csproj, src/AccessibilityInsights.Extensions.GitHub/IIssueFormatter.cs, src/AccessibilityInsights.Extensions.GitHub/LinkValidator.cs, src/AccessibilityInsights.Extensions.GitHub/Properties/Resources.Designer.cs, src/AccessibilityInsights.Extensions.GitHub/Properties/Resources.resx, src/AccessibilityInsights/AccessibilityInsights.csproj
Make Sure that the GitHub repo link is valid before saving it.
=> Validate GitHub Repo Link Input Format

src/AccessibilityInsights.SharedUx/Controls/TestTabs/ColorContrast.xaml, src/AccessibilityInsights.SharedUx/Controls/TestTabs/ColorContrast.xaml.cs, src/AccessibilityInsights.SharedUx/Properties/Resources.Designer.cs, src/AccessibilityInsights.SharedUx/Properties/Resources.resx, src/AccessibilityInsights/Modes/CCAModeControl.xaml
Change labels from Foreground color/Background color to Color 1/Color2.
Adjust sample texts based on PM/Design feedback.
=> Change label for #210 issue.

build/settings.targets
use a SHA2 cert to sign binaries. (MSI is already ok)
#1459081
=> change it to SHA2

src/AccessibilityInsights.SharedUx/Controls/HierarchyControl.xaml, src/AccessibilityInsights.SharedUx/Controls/ScannerResultControl.xaml, src/AccessibilityInsights.SharedUx/Controls/TestTabs/AutomatedChecksControl.xaml, src/AccessibilityInsights/AccessibilityInsights.csproj
- bind to IssueDisplayText instead of BugId.
- set visibility={binding filebugvisibility}
- Extension is there.
- No Extension.
=> File Issue icon fix

src/AccessibilityInsights.SharedUx/Controls/EventRecordControl.xaml, src/AccessibilityInsights.SharedUx/Controls/EventRecordControl.xaml.cs, src/AccessibilityInsights.SharedUx/Properties/Resources.Designer.cs, src/AccessibilityInsights.SharedUx/Properties/Resources.resx, src/AccessibilityInsights/Modes/EventModeControl.xaml.cs, src/AccessibilityInsights/Modes/LiveModeControl.xaml.cs
- [ #146 ] Does this address an existing issue? If yes, Issue# - 
(Please provide an overview of the change in this PR)cks will be kicked off. All of these checks must pass before a merge. 
Modified instruction text for how to record an event
=> modified instruction text for how to record an event

.github/ISSUE_TEMPLATE/bug_report.md, docs/FAQ.md
- Removes the placeholder for rules. We already have an entry that Rob added.
- Adds a FAQ for the CLA being stuck
- Adds text to the issue filing template to make sure people go through already filed issues before filing a new one.
=> Adding info about the cla + other things

docs/DebuggingExtensions.md, docs/Overview.md
Updated docs to align with the new assemblies and changes made for github issue filing support.
=> Update docs due to issue filing changes

docs/RulesOverview.md
=> a broken link by a typo(case mismatch)

CODEOWNERS
Chatted with Min - updating the code owners to include Fer and Mark in this PR
=> Update CODE OWNERS

Channels/Insider/release_info.json, Channels/Insider/release_notes.md
Create placeholder files for Insider ring (points to the most recent Canary build for now)
=> Placeholder versions of Insider release_info.json and release_notes.md

src/AccessibilityInsights.Extensions.GitHubAutoUpdate/AutoUpdate.cs, src/AccessibilityInsights.Extensions.GitHubAutoUpdate/IChannelInfoProvider.cs, src/AccessibilityInsights.Extensions.GitHubAutoUpdate/ProductionChannelInfoProvider.cs, src/AccessibilityInsights.Extensions.GitHubAutoUpdateUnitTests/AutoUpdateUnitTests.cs, src/AccessibilityInsights.SetupLibrary/ChannelInfo.cs, src/AccessibilityInsights.SetupLibrary/ChannelInfoUtilities.cs, src/AccessibilityInsights.SetupLibrary/GitHubWrapper.cs, src/AccessibilityInsights.SetupLibrary/IGitHubWrapper.cs, src/AccessibilityInsights.SetupLibrary/OverridableConfig.cs, src/AccessibilityInsights.SetupLibrary/ReleaseChannel.cs, src/AccessibilityInsights.SetupLibrary/SetupLibrary.csproj, src/AccessibilityInsights.SetupLibrary/VersionSwitcherWrapper.cs, src/AccessibilityInsights.SetupLibraryUnitTests/ChannelInfoUnitTests.cs, src/AccessibilityInsights.SetupLibraryUnitTests/ChannelInfoUtilitiesUnitTests.cs, src/AccessibilityInsights.SetupLibraryUnitTests/SetupLibraryUnitTests.csproj, src/AccessibilityInsights.SharedUx/Controls/SettingsTabs/ApplicationSettingsControl.xaml.cs, src/AccessibilityInsights.SharedUx/SharedUx.csproj, src/AccessibilityInsights.SharedUx/ViewModels/ChannelConfigViewModel.cs, src/AccessibilityInsights/MainWindowHelpers/ControlHelper.cs, src/AccessibilityInsights/Modes/ConfigurationModeControl.xaml.cs
Refactor ReleaseChannel and GetChannelInfo into SetupLibrary, fix Exception being thrown in recursive copy
=> Fix issues discovered during John's UI work

Channels/Insider/release_info.json, Channels/Insider/release_notes.md
Updated version of Insider control files (still needs more detailed copy)
=> Updated version of Insider control files

src/AccessibilityInsights.Extensions.AzureDevOps/AzureDevOpsIntegration.cs
Restoring lost code which ensures the ADO login functions with UIAccess and Topmost = true.
=> Fix ADO login with UIAccess

Channels/Insider/release_info.json, Channels/Insider/release_notes.md
Publish build 1.1.0831.02 to Insider channel
=> Publish build 1.1.0831.01 to Insider channel

Channels/Insider/release_info.json, Channels/Insider/release_notes.md
Promote build 1.1.0835.01 to Insider
=> Publish build 1.1.0835.01 to Insider

CODEOWNERS
This allows Addie to approve our releases
=> Add Addie to codeowners

src/AccessibilityInsights.SharedUx/Controls/SettingsTabs/AboutTabControl.xaml.cs, src/AccessibilityInsights.SharedUx/Misc/VersionTools.cs, src/AccessibilityInsights.SharedUx/Settings/ConfigurationModel.cs, src/AccessibilityInsights.SharedUx/SharedUx.csproj, src/AccessibilityInsights/MainWindow.xaml.cs, src/AccessibilityInsights/MainWindowHelpers/ControlHelper.cs, src/AccessibilityInsights/Modes/StartUpModeControl.xaml.cs
=> Move get app version out of Core

Channels/Insider/release_info.json, Channels/Insider/release_notes.md
Promote build 1.1.0837.02 to Insider. This is primarily to include the fix for issue #317
=> Insider promotion 1.1.0837.02

src/AccessibilityInsights.Extensions.TelemetryTests/Extensions.TelemetryTests.csproj
Because we now give TelemetryTests access to Telemetry's internals, we need to sign the tests. This PR signs them.
=> Sign TelemetryTests

Channels/Insider/release_notes.md, Channels/Production/release_notes.md
The Release Notes template includes a couple of links that aren't yet in the Release notes. Add them now.
=> Add installer and documentation links to ReleaseNotes

.github/CODEOWNERS
This code will be moved to axe-windows. Therefore, we don't want it modified in the ai-win repo.
=> Add Wildlife Manager to the list of protected code paths for axe-windows

CODEOWNERS
=> Remove Min from code owners

build/prbuild.yml
Enable code coverage to see how much we cover and act based on that.
=> Enable code coverage in build result 

Channels/Insider/release_info.json, Channels/Insider/release_notes.md
Release build 1.1.833.1 to the Insider channel. Release notes will automatically be applied to the public release once this PR is merged
=> Release build 1.1.883.1 to Insider channel

docs/FAQ.md
Change "differently abled people" to "people with disabilities" (following "people first" guidelines) in the FAQ document
=> Change "differently abled people" to "people with disabilities"

src/AccessibilityInsights.Extensions.GitHub/ConfigurationModelControl.xaml.cs, src/AccessibilityInsights.Extensions.GitHub/LinkValidator.cs, src/AccessibilityInsights.Extensions.GitHub/PlaceHolderTextBox.cs
FXCop issues: Replace StringComparison.InvariantCulture with StringComparison.Ordinal when comparing strings
=> FXCop changes

docs/FAQ.md
=> Replace URL with linked text in FAQ

src/AccessibilityInsights.SharedUx/SharedUx.csproj, src/AccessibilityInsights.SharedUx/packages.config, src/AccessibilityInsights.SharedUxTests/SharedUxTests.csproj, src/AccessibilityInsights.SharedUxTests/packages.config, src/AccessibilityInsights/AccessibilityInsights.csproj, src/AccessibilityInsights/packages.config, src/UITests/AIWinSession.cs, src/UITests/GettingStartedPage.cs, src/UITests/UITests.csproj, src/UITests/packages.config
Update our axe-windows dependency. 
Only the UITests needed to be modified. They're about to be modified a lot more, so don't give too close of attention to their update in this PR.
=> Update axe-windows to 0.2.0

src/UITests/AIWinSession.cs, src/UITests/GettingStartedPage.cs, src/UITests/LoadTestFile.cs, src/UITests/UILibrary/AIWinDriver.cs, src/UITests/UILibrary/EventsMode.cs, src/UITests/UILibrary/GettingStarted.cs, src/UITests/UILibrary/LiveMode.cs, src/UITests/UILibrary/Settings.cs, src/UITests/UILibrary/TestMode.cs, src/UITests/UITests.csproj
AIWinDriver provides an organized and human readable way to interact with AI-Win in our UITests. You can see how it is used in the GettingStartedPage test and an outline of how it can be used in the LoadTestFile test (not implemented yet).
=> Introduce AIWinDriver and use it in the GettingStartPage UITest

src/UITests/AIWinSession.cs
This PR adds a property with saved Application events from the Windows Event Viewer to the UI Test Session. If a UI test leads to AI-Win crashing (e.g. on button click), this property may hold events pertaining to the crash, such as this example:
`Application: AccessibilityInsights.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
at AccessibilityInsights.Modes.StartUpModeControl.btnVideo_Click(System.Object, System.Windows.RoutedEventArgs)
at System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)`
This PR intentionally doesn't do much with the property - we are deferring further work until we address test artifacts in general (a11y test files, …
=> Exploring Windows Event capturing in E2E tests

src/AccessibilityInsights/Modes/DialogContainerModeControl.xaml, src/UITests/GettingStartedPage.cs, src/UITests/TelemetryDialog.cs, src/UITests/UITests.csproj
Test Telemetry opt-in dialog with a scan and dismiss. 
Fix a margin in the telemetry dialog so tests pass.
=> Add TelemetryDialog UITest

src/AccessibilityInsights.SharedUx/Controls/HierarchyControl.xaml, src/AccessibilityInsights.SharedUx/Controls/InspectTabsControl.xaml, src/AccessibilityInsights.SharedUx/Properties/AutomationIDs.cs, src/AccessibilityInsights.SharedUx/Properties/Resources.Designer.cs, src/AccessibilityInsights.SharedUx/Properties/Resources.resx, src/UITests/AIWinSession.cs, src/UITests/LiveMode.cs, src/UITests/UILibrary/LiveMode.cs, src/UITests/UITests.csproj
This UITest for live mode launches WildlifeManager, runs ai-win tests, and does basic validation and axe-windows scans. If the PR build succeeds, this will be a good starting point off of which to build.
Find a screencap [here](https://dev.azure.com/accessibility-insights/Accessibility%20Insights/_apis/test/Runs/5300/Results/100017/Attachments/3)
=> Add basic live mode UITest

src/UITests/LiveMode.cs, src/UITests/LoadTestFile.cs, src/UITests/UILibrary/TestMode.cs
Expand the live mode UI tests to spot check the test results in a similar way to the LoadTestFile test. Extracted some validation code out from the LoadTestFile tests to share with the added tests.
Find screencap [here](https://dev.azure.com/accessibility-insights/Accessibility%20Insights/_apis/test/Runs/5366/Results/100141/Attachments/3)
=> Expand LiveMode UITest Coverage

Channels/Insider/release_info.json, Channels/Insider/release_notes.md
Release 1.1.0933.01 to Insider channel. Product changes are outlined in the release notes
=> Release 1.1.0933.01 to Insider channel

CODEOWNERS
Mark has asked that we change the code owners for the control branch. Releasing is part of execution, so that operation needs to be owned by the engineering team. PM will still be asked to review the release notes before committing any release change. I'll update the documentation for the release process once this PR is merged.
=> Update code owners for the Control branch

Channels/Production/release_info.json, Channels/Production/release_notes.md
Update build 1.1.933.1 (currently in Insider) to Production. Release notes are copied from the current Insider release notes, with the date and channel references updated appropriately.
=> Promote 1.1.933.1 to Production (scheduled for August 5th)

Channels/Production/release_notes.md
=> Fix Issue #451

src/UIAAssemblies/readme.md
Remove readme references to projects that are in Axe.Windows
=> Remove Axe.Windows projects from UIAAssemblies readme

Channels/Production/release_notes.md
Add a couple of external links that were omitted from the 1.1.0933.01 release notes. Correct one incorrect internal link
=> Installation and Documentation links were missing

src/UITests/UITests.csproj, src/UITests/packages.config
Update UI tests to the same version of Castle.Core that we use in unit tests.
=> Use VS to update Castle.Core to 4.4.0 (the same version used in other tests)

src/AccessibilityInsights.Extensions.AzureDevOps/Extensions.AzureDevOps.csproj, src/AccessibilityInsights.Extensions.AzureDevOps/packages.config
Dependabot suggested a similar change in #474. This does it via Visual Studio. Validated by ensuring that ADO bug filing still works when installing from the MSI file
=> Use VS to update to System.Xml.ReaderWriter 4.3.1

src/AccessibilityInsights/AccessibilityInsights.csproj, src/AccessibilityInsights/packages.config
=> Use VS to update CommandLineParser to version 2.6.0

src/AccessibilityInsights.SharedUx/SharedUx.csproj, src/AccessibilityInsights.SharedUx/packages.config, src/AccessibilityInsights.SharedUxTests/SharedUxTests.csproj, src/AccessibilityInsights.SharedUxTests/packages.config, src/AccessibilityInsights/AccessibilityInsights.csproj, src/AccessibilityInsights/packages.config, src/UITests/UITests.csproj, src/UITests/packages.config
Change suggested by #493, but done via VS
=> Use VS to update to System.Security.Principal.Windows 4.5.1

src/AccessibilityInsights.Extensions.GitHubAutoUpdateUnitTests/Extensions.GitHubAutoUpdateUnitTests.csproj, src/AccessibilityInsights.Extensions.GitHubAutoUpdateUnitTests/packages.config, src/AccessibilityInsights.Extensions.GitHubUnitTests/Extensions.GitHubUnitTests.csproj, src/AccessibilityInsights.Extensions.GitHubUnitTests/packages.config, src/AccessibilityInsights.SharedUxTests/SharedUxTests.csproj, src/AccessibilityInsights.SharedUxTests/packages.config
=> Use VS to update Moq from 4.12 to 4.13

src/AccessibilityInsights.SharedUx/SharedUx.csproj, src/AccessibilityInsights.SharedUx/packages.config, src/AccessibilityInsights.SharedUxTests/SharedUxTests.csproj, src/AccessibilityInsights.SharedUxTests/packages.config, src/AccessibilityInsights/AccessibilityInsights.csproj, src/AccessibilityInsights/packages.config, src/UITests/UITests.csproj, src/UITests/packages.config
Updates to three Axe.Windows rules. See https://github.com/microsoft/axe-windows/releases/tag/v0.3.3.
=> Update Axe.Windows package to v0.3.3

Channels/Insider/release_info.json, Channels/Insider/release_notes.md, tools/scripts/ValidateReleaseInfo.ps1
Release build 1.1.0988.01 to the Insider channel
=> Release build 1.1.988.1 to Insider channel

Channels/Production/release_info.json, Channels/Production/release_notes.md
This PR promotes 1.1.0990.01 to production. This includes updates to the release notes and minimum version allowed.
https://github.com/microsoft/accessibility-insights-windows/blob/446f032d1a538ba0e2eb4165e9aa9670101b5366/Channels/Production/release_notes.md
=> Promote 1.1.0990.01 to production

src/AccessibilityInsights.SharedUx/SharedUx.csproj, src/AccessibilityInsights.SharedUx/packages.config, src/AccessibilityInsights.SharedUxTests/SharedUxTests.csproj, src/AccessibilityInsights.SharedUxTests/packages.config, src/AccessibilityInsights/AccessibilityInsights.csproj, src/AccessibilityInsights/packages.config, src/UITests/UITests.csproj, src/UITests/packages.config
This is the VS-driven version of #569 
=> Use VS to update to System.Drawing.Common 4.6.0

src/AccessibilityInsights.CommonUxComponents/CommonUxComponents.csproj, src/AccessibilityInsights.CommonUxComponents/packages.config, src/AccessibilityInsights.Extensions.AzureDevOps/AzureDevOpsIntegration.cs, src/AccessibilityInsights.Extensions.AzureDevOps/Extensions.AzureDevOps.csproj, src/AccessibilityInsights.Extensions.AzureDevOps/packages.config, src/AccessibilityInsights.Extensions.GitHub/Extensions.GitHub.csproj, src/AccessibilityInsights.Extensions.GitHub/packages.config, src/AccessibilityInsights.Extensions.GitHubAutoUpdate/Extensions.GitHubAutoUpdate.csproj, src/AccessibilityInsights.Extensions.GitHubAutoUpdate/packages.config, src/AccessibilityInsights.Extensions.Telemetry/Extensions.Telemetry.csproj, src/AccessibilityInsights.Extensions.Telemetry/packages.config, src/AccessibilityInsights.Extensions/Extensions.csproj, src/AccessibilityInsights.Extensions/packages.config, src/AccessibilityInsights.Fakes.Prebuild/app.config, src/AccessibilityInsights.SetupLibrary/SetupLibrary.csproj, src/AccessibilityInsights.SetupLibrary/packages.config, src/AccessibilityInsights.SharedUx/SharedUx.csproj, src/AccessibilityInsights.SharedUx/packages.config, src/AccessibilityInsights.VersionSwitcher/VersionSwitcher.csproj, src/AccessibilityInsights.VersionSwitcher/packages.config, src/AccessibilityInsights.Win32/Win32.csproj, src/AccessibilityInsights.Win32/packages.config, src/AccessibilityInsights/AccessibilityInsights.csproj, src/AccessibilityInsights/packages.config, src/UITests/app.config
Use VS to update to Roslyn 2.9.5 analyzers. Fix 3 instances of an issue that was not flagged in the beta1.final version
=> Update to Roslyn 2.9.5 final release

src/AccessibilityInsights.CommonUxComponents/CommonUxComponents.csproj, src/AccessibilityInsights.CommonUxComponents/packages.config, src/AccessibilityInsights.Extensions.AzureDevOps/Extensions.AzureDevOps.csproj, src/AccessibilityInsights.Extensions.AzureDevOps/packages.config, src/AccessibilityInsights.Extensions.GitHub/Extensions.GitHub.csproj, src/AccessibilityInsights.Extensions.GitHub/packages.config, src/AccessibilityInsights.Extensions.GitHubAutoUpdate/Extensions.GitHubAutoUpdate.csproj, src/AccessibilityInsights.Extensions.GitHubAutoUpdate/packages.config, src/AccessibilityInsights.Extensions.Telemetry/Extensions.Telemetry.csproj, src/AccessibilityInsights.Extensions.Telemetry/packages.config, src/AccessibilityInsights.Extensions/Extensions.csproj, src/AccessibilityInsights.Extensions/packages.config, src/AccessibilityInsights.SetupLibrary/SetupLibrary.csproj, src/AccessibilityInsights.SetupLibrary/packages.config, src/AccessibilityInsights.SharedUx/SharedUx.csproj, src/AccessibilityInsights.SharedUx/packages.config, src/AccessibilityInsights.VersionSwitcher/VersionSwitcher.csproj, src/AccessibilityInsights.VersionSwitcher/packages.config, src/AccessibilityInsights.Win32/Win32.csproj, src/AccessibilityInsights.Win32/packages.config, src/AccessibilityInsights/AccessibilityInsights.csproj, src/AccessibilityInsights/packages.config
Update to Roslyn 2.9.6. No code changes were required.
=> Update to Roslyn 2.9.6

src/AccessibilityInsights.SharedUx/ActionViews/ReturnA11yElementsView.xaml, src/AccessibilityInsights.SharedUx/Controls/InspectTabsControl.xaml, src/AccessibilityInsights.SharedUx/Dialogs/ElementInfoDialog.xaml, src/AccessibilityInsights.SharedUx/Properties/Resources.Designer.cs, src/AccessibilityInsights.SharedUx/Properties/Resources.resx, src/AccessibilityInsights/Properties/Resources.Designer.cs, src/AccessibilityInsights/Properties/Resources.resx
Remove unused strings, fix a couple of typos in string names. Should have 0 impact on the app
=> Remove unused strings, fix a couple of typos in string names

src/AccessibilityInsights.Extensions.GitHubAutoUpdateUnitTests/Extensions.GitHubAutoUpdateUnitTests.csproj, src/AccessibilityInsights.Extensions.GitHubAutoUpdateUnitTests/packages.config, src/AccessibilityInsights.Extensions.GitHubUnitTests/Extensions.GitHubUnitTests.csproj, src/AccessibilityInsights.Extensions.GitHubUnitTests/packages.config, src/AccessibilityInsights.SharedUxTests/SharedUxTests.csproj, src/AccessibilityInsights.SharedUxTests/packages.config
=> Update to Moq 4.13.1

src/UITests/UITests.csproj, src/UITests/packages.config
This is the VS-driven version of #633. Validated locally, impacts only E2E test scenarios 
=> Use VS to update to Appium.WebDriver 4.1.0

src/UITests/UITests.csproj, src/UITests/packages.config
Bump Appium.WebDriver from 4.1.0 to 4.1.1 (changed via VS). This supersedes #636 
=> Bump Appium.WebDriver from 4.1.0 to 4.1.1 (changed via VS)

Channels/Insider/release_info.json, Channels/Insider/release_notes.md
Creating a new insider release
https://github.com/microsoft/accessibility-insights-windows/blob/be6568c0909b7ef66a3ff45fd0efddda76fc9375/Channels/Insider/release_notes.md
=> Update metadata for releasing 1.1.1048.01 to insider

src/AccessibilityInsights.SharedUx/SharedUx.csproj, src/AccessibilityInsights.SharedUx/packages.config, src/AccessibilityInsights.SharedUxTests/SharedUxTests.csproj, src/AccessibilityInsights.SharedUxTests/packages.config, src/AccessibilityInsights/AccessibilityInsights.csproj, src/AccessibilityInsights/packages.config, src/UITests/UITests.csproj, src/UITests/packages.config
This is the VS-driven version of #661
=> Bump System.Drawing.Common from 4.6.1 to 4.7.0 (using VS)

src/AccessibilityInsights.SharedUx/SharedUx.csproj, src/AccessibilityInsights.SharedUx/packages.config, src/AccessibilityInsights.SharedUxTests/SharedUxTests.csproj, src/AccessibilityInsights.SharedUxTests/app.config, src/AccessibilityInsights.SharedUxTests/packages.config, src/AccessibilityInsights/AccessibilityInsights.csproj, src/AccessibilityInsights/packages.config, src/UITests/UITests.csproj, src/UITests/packages.config
Bump Axe.Windows from 0.3.4 to 0.3.5
=> Bump Axe.Windows from 0.3.4 to 0.3.5

Channels/Insider/release_info.json, Channels/Insider/release_notes.md
=> Release 1.1.1072.01 to Insider Channel

Channels/Production/release_info.json, Channels/Production/release_notes.md
=> Publish build 1.1.1072.01 to Production

build/signedbuild.yml
Due to ongoing signed build issues, this PR removes UI tests from the signed build. They still run on PR and CI.
=> Remove UI tests from signed build (temporary)

build/signedbuild.yml
A previous PR (#683) failed to remove the dependson for the job it removed. This PR removes the dependson.
=> Remove unused dependson

Channels/Insider/release_info.json, Channels/Insider/release_notes.md, Channels/Production/release_info.json, Channels/Production/release_notes.md
Release 1.1.1107.01 to both Insider and Prod
=> Simultaneous Insider & Production release of 1.1.1107.1

src/AccessibilityInsights.Extensions.GitHub/Extensions.GitHub.csproj, src/AccessibilityInsights.Extensions.GitHub/packages.config, src/AccessibilityInsights.SharedUx/SharedUx.csproj, src/AccessibilityInsights.SharedUx/packages.config, src/AccessibilityInsights.SharedUxTests/SharedUxTests.csproj, src/AccessibilityInsights.SharedUxTests/packages.config, src/AccessibilityInsights/AccessibilityInsights.csproj, src/AccessibilityInsights/MainWindowHelpers/TreeNavigator.cs, src/AccessibilityInsights/packages.config, src/UITests/UITests.csproj, src/UITests/packages.config
Update to the latest version of Axe.Windows
=> Update axe-windows package to version 0.9.0

Channels/Insider/release_info.json, Channels/Insider/release_notes.md, Channels/Production/release_info.json, Channels/Production/release_notes.md
Release build 1.1.1152.01 to Insider and Production channels
=> Release 1.1.1152.01 to Insider and Production

Channels/Insider/release_notes.md
I made some adjustments to the release pipeline--this is a trivial change to validate those adjustments. Since Insider and Release are at the same build, the Insider release notes aren't currently used anywhere, so they're safe to tweak.
=> Trivial change to validate release pipeline

Channels/Insider/release_notes.md
This change undoes #714 to test the pipeline trigger
=> Revert text change (force commit in Control branch)

src/AccessibilityInsights/Modes/LiveModeControl.xaml
Reverts microsoft/accessibility-insights-windows#720. This change seems to have broken the ability to interact in the hierarchy view.
=> Revert "Scroll Live Mode Instructions"

src/AccessibilityInsights.SharedUx/SharedUx.csproj, src/AccessibilityInsights.SharedUx/packages.config, src/AccessibilityInsights.SharedUxTests/SharedUxTests.csproj, src/AccessibilityInsights.SharedUxTests/packages.config, src/AccessibilityInsights/AccessibilityInsights.csproj, src/AccessibilityInsights/packages.config, src/UITests/UITests.csproj, src/UITests/packages.config
Changes to files were made by Visual Studio
=> Update to Axe.Windows 0.9.1

src/AccessibilityInsights.SharedUx/SharedUx.csproj, src/AccessibilityInsights.SharedUx/packages.config, src/AccessibilityInsights.SharedUxTests/SharedUxTests.csproj, src/AccessibilityInsights.SharedUxTests/app.config, src/AccessibilityInsights.SharedUxTests/packages.config, src/AccessibilityInsights/AccessibilityInsights.csproj, src/AccessibilityInsights/App.config, src/AccessibilityInsights/packages.config, src/UITests/UITests.csproj, src/UITests/packages.config
Pick up the latest version of Axe.Windows to address issue #745 
=> Bump Axe.Windows from 0.9.1-prerelease to 0.9.3-prerelease

src/AccessibilityInsights.Extensions/Interfaces/IssueReporting/IIssueReporting.cs, src/AccessibilityInsights/Modes/TestModeControl.xaml.cs
This just removes a couple of using statements that aren't needed. It also makes a great test to see if auto-merging works correctly.
=> Remove a couple of unnecessary using statements

docs/SetUpDevEnv.md, src/AccessibilityInsights.sln, tools/WildlifeManager/src/WildlifeManager.sln
Our internal tools and build pipeline use VS2019, but the documentation and solution file both say VS2017. This just brings the files into sync with reality. 
I forced updates of all of the csproj and resx files with the new tools, and their version stamps were not modified by the changes.
=> Update docs and solution file to VS 2019

src/AccessibilityInsights.SharedUx/Dialogs/TextRangeFindDialog.xaml.cs
Missed replacing this zero with a meaningful variable in a recent change.
=> Replace magic number with meaningful variable

Channels/Insider/release_info.json, Channels/Insider/release_notes.md, Channels/Production/release_info.json, Channels/Production/release_notes.md
Simultaneous release of 1.1.1248.01 to Insider and Production
=> Release build 1.1.1248.01

Channels/Insider/release_info.json, Channels/Insider/release_notes.md, Channels/Production/release_info.json, Channels/Production/release_notes.md
Simultaneous release of 1.1.1334.02 to Insider and Production
=> Release build 1.1.1334.02

Channels/Insider/release_info.json, Channels/Insider/release_notes.md, Channels/Production/release_info.json, Channels/Production/release_notes.md
Release build 1.1.1369.01 to Insider and Production
=> chore: Release build 1.1.1369.01 to Insider and Production

src/AccessibilityInsights.SharedUx/SharedUx.csproj, src/UITests/UITests.csproj
Bump to Axe.Windows v1.0.5 to pick up the latest set of changes.
=> chore: Bump to Axe.Windows v1.0.5

Channels/Insider/release_info.json, Channels/Insider/release_notes.md, Channels/Production/release_info.json, Channels/Production/release_notes.md, tools/scripts/ValidateReleaseInfo.ps1
Publish the build with the new `Axe.Windows` to Insider and Production channels
We need to get this build out
=> Release 1.1.1562.01

CODEOWNERS
=> chore: Add RobGallo as code owner

src/AccessibilityInsights.Extensions.AzureDevOps/ConfigurationControl.xaml.cs, src/AccessibilityInsights.Extensions.AzureDevOps/Properties/Resources.Designer.cs, src/AccessibilityInsights.Extensions.AzureDevOps/Properties/Resources.resx, src/AccessibilityInsights.Extensions.GitHubAutoUpdate/AutoUpdate.cs, src/AccessibilityInsights.SharedUx/Enums/FileFilters.cs, src/AccessibilityInsights.SharedUx/FileIssue/FileIssueAction.cs, src/AccessibilityInsights.SharedUx/Properties/Resources.Designer.cs, src/AccessibilityInsights.SharedUx/Properties/Resources.resx, src/AccessibilityInsights/App.xaml.cs, src/AccessibilityInsights/Scripts/UIAccess.cmd
I noticed some typos and thought I'd fix them
Typos are bad
=> chore: Fix typos

src/AccessibilityInsights/MainWindowHelpers/Timers.cs
Fix a couple of typos that I noticed while debugging something
Better accuracy
=> chore: Correct a couple of typos

src/AccessibilityInsights.SharedUx/SharedUx.csproj, src/UITests/UITests.csproj
Update to the newest release of Axe.Windows (1.0.10)
Unblock work on adding live support for custom UIA properties
- [n/a] Does this address an existing issue?
=> Chore: Update Axe.Windows to 1.0.10

Channels/Insider/release_info.json, Channels/Insider/release_notes.md, Channels/Production/release_info.json, Channels/Production/release_notes.md
Update release with support for Custom UIA & Axe.Windows 1.1.0
Release new features, fix bugs
=> chore: Publish build 1.1.1663.01 to Insider and Production channels

Channels/Insider/release_info.json, Channels/Insider/release_notes.md, Channels/Production/release_info.json, Channels/Production/release_notes.md
See release_notes.md
Publish the #1169 fix
=> chore: Publish build 1.1.1689.01 to Insider and Production channels

src/AccessibilityInsights/Modes/CCAModeControl.xaml.cs, src/AccessibilityInsights/Modes/LiveModeControl.xaml.cs, src/AccessibilityInsights/Modes/TestModeControl.xaml.cs, src/AccessibilityInsights/Properties/Resources.Designer.cs, src/AccessibilityInsights/Properties/Resources.resx
This PR improves localization in the `AccessibilityInsights` project. Some of the changes replace a hardcoded string with a new resource string, while others replace hardcoded concatenation of resource strings with a parameterized resource string (which would allow the parameters to be used in any order). One change corrects a bug where the resource string expected a filename but the calling code failed to provide one.
To make the work more manageable, I'll create a separate PR for each project.
Each commit includes strings from a single .cs file. It might be easier to review each commit separately. They do not overlap. …
=> feat(compliance-fall-21): Improve localizability in AccessibilityInsights project

src/AccessibilityInsights/MainWindow.xaml.cs, src/AccessibilityInsights/Properties/Resources.Designer.cs, src/AccessibilityInsights/Properties/Resources.resx
This PR improves localization in the `AccessibilityInsights` project. One change replaces 2 strings that get concatenated with a formattable resource string. The change in wording is intentional, so that the automation name matches the visible text. There's also a change to add "hints" about how parameters in several formatting strings are used.
To make the work more manageable, I'll create a separate PR for each project.
=> feat(compliance-fall-21): Improve localization in AccessibilityInsights project

src/AccessibilityInsights.SharedUx/Highlighting/Win32SnapshotButton.cs
This PR fixes issue #1290, where one user reported an issue where Application Insights would crash while trying to render the "beaker" icon as part of its highlighter overlay.
The root cause of the crash is that the code path in question was rendering the icon using a `FontFamily` pulled out of a `PrivateFontCollection` which we had already `Dispose()`ed. The `Families` getter in the `PrivateFontCollection` doesn't document the lifetime requirements of the `FontFamily` objects it returns and its implementation is misleading in that it *looks* like it's cloning a copy of the underlying native font objects with a separate lifetime, but the native clone still maintains some links to data backed by the font collection, so it isn't safe to use it this way in practice.
Addresses issue #1290
I …
=> fix: prevent crash in Highlighter beaker rendering due to FontFamily use-after-dispose

src/AccessibilityInsights.Extensions.AzureDevOps/FileIssue/IssueFileForm.cs
#1312 accidentally removed a newline--this restores it
=> chore: Restore newline that was accidentally removed

Channels/Insider/release_info.json, Channels/Insider/release_notes.md, Channels/Production/release_info.json, Channels/Production/release_notes.md
Update Insider and Production releases to 1.1.1934.1
We have some changes that we want to get into production.
This PR will fail validation until build 1.1.1934.1 comes out of the pipeline on Tuesday
- [n/a] Does this address an existing issue? If yes, Issue 
=> chore: Release 1.1.1934.1 to Insider and Production 

docs/TelemetryDetails.md
Make 2 updates to telemetry details doc:
1. Update `Scan_Statistics` to reflect Axe.Windows [#678](https://github.com/microsoft/axe-windows/pull/678). 
2. Update the list of Windows versions to reflect more recent Windows releases.
Have accurate docs
=> chore: Update telemetry docs

src/AccessibilityInsights/MainWindow.xaml.cs
When opening the project in a recent version of Visual Studio, the analyzer suggests some changes. These changes were made by accepting the suggested changes.
Reduce noise when opening project in Visual Studio
- [n/a] Does this address an existing issue? If yes, Issue:
=> chore: Make some analyzer-suggested changes

docs/FAQ.md, docs/VirusScannerExclusions.md
This adds docs about excluding the repo from virus scanners to improve app startup time
Document best practices
- [n/a] Does this address an existing issue? If yes, Issue:
=> chore: Add docs for virus scanner exclusions

src/AccessibilityInsights.Extensions.AzureDevOps/ForcedDependencies.cs
Improve a comment that had some typos
Comments should be clear
=> chore: Improve comment for ForcedDependencies

src/AccessibilityInsights.Extensions.AzureDevOps/AzureBoardsIssueReporting.cs, src/AccessibilityInsights.Extensions.AzureDevOps/AzureDevOpsIntegration.cs, src/AccessibilityInsights.Extensions.AzureDevOps/ConfigurationControl.xaml.cs, src/AccessibilityInsights.Extensions.AzureDevOps/ConnectionCache.cs, src/AccessibilityInsights.Extensions.AzureDevOps/ConnectionInfo.cs, src/AccessibilityInsights.Extensions.AzureDevOps/FileIssue/IssueFileForm.cs, src/AccessibilityInsights.Extensions.AzureDevOps/IDevOpsIntegration.cs, src/AccessibilityInsights.Extensions.AzureDevOps/Models/AdoTeam.cs, src/AccessibilityInsights.Extensions.AzureDevOps/Models/AzureDevOpsEntity.cs, src/AccessibilityInsights.Extensions.AzureDevOps/Models/IssueResult.cs, src/AccessibilityInsights.Extensions.AzureDevOps/Models/TeamProject.cs, src/AccessibilityInsights.Extensions.AzureDevOpsTests/ConnectionCacheTests.cs
This PR fixes various spelling and typographical errors found in strings and comments in the `AccessibilityInsights.Extensions.AzureDevOps` namespace.
=> chore: Fix various spelling and typographical errors in source code comments and strings (AccessibilityInsights.Extensions.AzureDevOps namespace)

src/AccessibilityInsights.SetupLibrary/ChannelInfoUtilities.cs, src/AccessibilityInsights.SetupLibrary/GitHubWrapper.cs, src/AccessibilityInsights.SetupLibrary/OverridableConfig.cs, src/AccessibilityInsights.SetupLibrary/SettingsDictionary.cs, src/AccessibilityInsights.SetupLibrary/VersionSwitcherWrapper.cs
This PR fixes various spelling and typographical errors found in strings and comments in the `AccessibilityInsights.SetupLibrary` namespace.
=> chore: Fix various spelling and typographical errors in source code comments and strings (AccessibilityInsights.SetupLibrary namespace)

src/UITests/LiveMode.cs, src/UITests/LoadTestFile.cs, src/UITests/README.md, src/UITests/UILibrary/LiveMode.cs
This PR fixes various spelling and typographical errors found in strings and comments in the `UITests` namespace.
=> chore: Fix various spelling and typographical errors in source code comments and strings (UITests namespace)

src/AccessibilityInsights.SharedUx/ViewModels/BaseActionViewModel.cs, src/AccessibilityInsights.SharedUx/ViewModels/EventConfigNodeViewModel.cs, src/AccessibilityInsights.SharedUx/ViewModels/HierarchyNodeViewModel.cs, src/AccessibilityInsights.SharedUx/ViewModels/NotSupportedActionViewModel.cs, src/AccessibilityInsights.SharedUx/ViewModels/RuleResultViewModel.cs, src/AccessibilityInsights.SharedUxTests/ViewModels/ViewModelTests.cs
This PR fixes various spelling and typographical errors found in strings and comments in the `AccessibilityInsights.SharedUx.ViewModels` namespace.
=> chore: Fix various spelling and typographical errors in source code comments and strings (AccessibilityInsights.SharedUx.ViewModels namespace)

src/AccessibilityInsights/App.xaml.cs, src/AccessibilityInsights/AppManifests/UIAccess_Disabled.manifest, src/AccessibilityInsights/AppManifests/UIAccess_Enabled.manifest, src/AccessibilityInsights/MainWindow.xaml.cs, src/AccessibilityInsights/MainWindowHelpers/ControlHelper.cs, src/AccessibilityInsights/MainWindowHelpers/Initialize.cs, src/AccessibilityInsights/MainWindowHelpers/StateMachine.cs, src/AccessibilityInsights/MainWindowHelpers/TelemetryStartup.cs, src/AccessibilityInsights/Modes/ConfigurationModeControl.xaml.cs, src/AccessibilityInsights/Modes/EventModeControl.xaml.cs, src/AccessibilityInsights/Modes/LiveModeControl.xaml.cs, src/AccessibilityInsights/Modes/SnapshotModeControl.xaml.cs, src/AccessibilityInsights/Modes/TestModeControl.xaml.cs, src/AccessibilityInsights/Properties/AssemblyInfo.cs, src/AccessibilityInsights/Properties/Resources.resx
This PR fixes various spelling and typographical errors found in strings and comments in the `AccessibilityInsights` namespace.
=> chore: Fix various spelling and typographical errors in source code comments and strings (AccessibilityInsights namespace)

Channels/Insider/release_info.json, Channels/Insider/release_notes.md, Channels/Production/release_info.json, Channels/Production/release_notes.md
PR to release most recent updates of AIWin to prod. Our last Prod release was on June 21st.
Publish the most recent changes
=> chore: September 2022 release

build/signedbuild.yml
This enables CodeQL analysis in our signed pipeline. This change is based on https://github.com/microsoft/axe-windows/pull/765. It can only really be tested in the main branch, so the idea is to merge it then observe.
Enable analysis via CodeQL
- [n/a] Does this address an existing issue? If yes, Issue
=> chore: Enable CodeQL analysis

docs/Overview.md
Our overview document has not been kept current as new projects have been added to the solution. This PR adds the missing projects and reformats things a little bit to (hopefully) make the document more usable and consistent.
Obsolete docs are bad
=> chore: Update overview document

Channels/Insider/release_info.json, Channels/Insider/release_notes.md, Channels/Production/release_info.json, Channels/Production/release_notes.md
Release 2213.01 to Insider and Production. Includes all changes since release 1.1.2089.01
Standard release mechanism
=> chore: Release 2213.01 to Insider and Production

build/build-and-unit-tests.yml, build/check-dependencies.yml, build/prbuild.yml, build/ui-test-job.yml
Migrated accessibility-insights-windows to 1ES template as per the changes mentioned in the documentation link provided for the 1ES pipeline migration.
Pipeline migration to 1ES template. User Stories - [User Story 2136511](https://dev.azure.com/mseng/1ES/_workitems/edit/2136511): Migrate accessibility-insights-windows-CI to 1ES template and [User Story 2136512](https://dev.azure.com/mseng/1ES/_workitems/edit/2136512): Migrate  accessibility-insights-windows-PR to 1ES template
Old Pipeline for CI: https://dev.azure.com/accessibility-insights/Accessibility%20Insights/_build/results?buildId=51302&view=results
New Pipeline for CI: https://dev.azure.com/accessibility-insights/Accessibility%20Insights/_build/results?buildId=51378&view=results
Old Pipeline for PR: …
=> feat(Pipeline Migration to 1ES Template):accessibility-insights-windows

src/AccessibilityInsights.Extensions.AzureDevOps/Extensions.AzureDevOps.csproj, src/AccessibilityInsights.SharedUx/SharedUx.csproj, src/UITests/UITests.csproj
Dependabot got confused and closed out several PRs, stating they "aren't dependencies". However, Visual Studio is able to update them just fine.
Ingest Axe.Windows changes.
=> chore(deps): Manual dependency update

src/AccessibilityInsights.Extensions.AzureDevOps/Extensions.AzureDevOps.csproj
Manual PR for the dependabot PR https://github.com/microsoft/accessibility-insights-windows/pull/1836
=> chore(deps): update Microsoft.Identity.Client from 4.61.2 to 4.61.3
