microsoft/accessibility-insights-windows

- CODE_OF_CONDUCT.md
- Contributing.md
While we have our Code of Conduct listed under Contributing.md, GitHub community profile won't detect it unless it's in a separate file (see [Add Code of Conduct to repo](https://help.github.com/en/articles/adding-a-code-of-conduct-to-your-project)). This pull request moves the content out into its separate file.
> Move code of conduct into a separate file

- src/AccessibilityInsights.ActionsTests/Actions/CaptureActionUnitTests.cs
- src/AccessibilityInsights.ActionsTests/Actions/PrivacyExtensionsUnitTests.cs
- src/AccessibilityInsights.ActionsTests/ActionsTests.csproj
- src/AccessibilityInsights.ActionsTests/Misc/ResultsFileSarifMapperUnitTests.cs
This omits individual unit tests in ActionsTests if they have fakes. The original behavior omits entire files. With this PR we can still preserve the unit tests that don't require fakes, and we get 27 tests back in this project.
Some open questions:
- if all the tests in a file require fakes, should we still if/endif methods, or should we leave it the way it is?
- if consecutive tests require fakes, should we if/endif the whole block & rearrange methods, or should each method have its own if/endif?
- does each fakes import require its own if/endif or are we OK breaking sorting order to block them together?
> Excluding individual fakes-tests in ActionsTests at a test-level granularity

- build/prbuild.yml
This adds a job that simply builds the solution with FAKES_SUPPORTED disabled. It is a sanity check to ensure nothing is broken for users without fakes. The tests themselves run in existing jobs.
> Add a job that builds without fakes

- src/AccessibilityInsights.CoreTests/CoreTests.csproj
- src/AccessibilityInsights.CoreTests/Fingerprint/InMemoryIssueStoreUnitTests.cs
- src/AccessibilityInsights.CoreTests/Fingerprint/IssueUnitTests.cs
- src/AccessibilityInsights.CoreTests/Fingerprint/OutputFileIssueStoreUnitTests.cs
- src/AccessibilityInsights.CoreTests/Fingerprint/OutputFileLocationUnitTests.cs
- src/AccessibilityInsights.CoreTests/Fingerprint/ScanResultFingerprintUnitTests.cs
This PR ignores individual tests in CoreTests.csproj that require fakes if the FAKES_SUPPORTED environment variable is disabled. This improves upon the old approach that ignored entire files.
> Ignore fakes at a per-test level in CoreTests.csproj

- Contributing.md
- docs/GitBranchSetup.md
This PR adds initial documentation about git workflow - both [web](https://github.com/Microsoft/accessibility-insights-web/pull/381) and windows are modeled after OF. May be able to consolidate these separate sources but for now this works.
See preview here: https://github.com/Microsoft/accessibility-insights-windows/pull/192/files?short_path=73ea53d#diff-73ea53d2bfcb766b349c692c9bc78185
> Add guidance for setting up forks

- src/AccessibilityInsights.Extensions.AzureDevOpsTests/AzureDevOpsBugReportingUnitTests.cs
- src/AccessibilityInsights.Extensions.AzureDevOpsTests/Extensions.AzureDevOpsTests.csproj
This project had one file with both fakes & non-fakes tests. Those tests have now been individually excluded based on the FAKES_SUPPORTED env variable.
> Excluding tests with fakes in azuredevops extension

- src/AccessibilityInsights.Extensions/Extensions.csproj
- src/AccessibilityInsights.Extensions/Interfaces/IssueReporting/IIssueReporting.cs
- src/AccessibilityInsights.Extensions/Interfaces/IssueReporting/ReporterFabricIcon.cs
- src/AccessibilityInsights.SharedUx/Controls/SettingsTabs/ConnectionControl.xaml.cs
- src/AccessibilityInsights.SharedUx/Controls/SettingsTabs/TestIssueProvider.cs
- src/AccessibilityInsights.SharedUx/Controls/SettingsTabs/TestIssueProvider2.cs
- src/AccessibilityInsights.SharedUx/FileBug/BugReporter.cs
- src/AccessibilityInsights.SharedUx/SharedUx.csproj
- src/AccessibilityInsights.SharedUx/ViewModels/LogoViewModel.cs
- src/AccessibilityInsights/MainWindow.xaml
- src/AccessibilityInsights/MainWindow.xaml.cs
- src/AccessibilityInsights/Modes/ConfigurationModeControl.xaml.cs
- src/AccessibilityInsights/Properties/Resources.Designer.cs
- src/AccessibilityInsights/Properties/Resources.resx
Provides a way to update the logo and the tooltip after config restore (on login) and when we hit save on the connections page. We do not have the tooltip text and the default logo yet. Added the ladybug tentatively.
Inverts the order of the settings and the connection order.
Please ignore all files with a "TestIssue" prefix in the name (TestIssue*)
> Update logo when the state of the issue reporter changes

- README.md
This PR adds some badges to the readme. These are small SVGs common to most READMEs that share info about the project.
- The download count is total/all-time. We could also use 'latest' instead or have a specific version. 
- The release badge goes to the release. We could instead link to the direct MSI.
I wanted to add one for the MIT license but GitHub is unable to figure out that our license is MIT. Contrast this with vscode, for example: https://github.com/Microsoft/vscode/blob/master/LICENSE.txt
Please go here to see a rich diff: https://github.com/Microsoft/accessibility-insights-windows/pull/201/files?short_path=04c6e90#diff-04c6e90faac2675aa89e2176d2eec7d8
These badges aren't fully accessible - e.g. we can provide static alt text but the numbers are not available to a screenreader. …
> adding some badges

- src/AccessibilityInsights.Rules/Library/LandmarkOneMain.cs
Changing from Error to Warning because the rule is based on Deque's rule for the web, which is labeled "moderate" and "best practice", but is not strictly required for compliance with WCAG.
This was reported as a false positive by a customer.
> Changing the EvaluationCode returned by the LandmarkOneMain rule.

- src/AccessibilityInsights.Desktop/UIAutomation/EventHandlers/EventMessage.cs
- src/AccessibilityInsights/Modes/LiveModeControl.xaml.cs
- [ #161 ] Does this address an existing issue? If yes, Issue# - 
Fixed the event details view by suppressing the warning
> fixed the event details view by suppressing the warning

- src/AccessibilityInsights.ActionsTests/ActionsTests.csproj
- src/AccessibilityInsights.ActionsTests/packages.config
- src/AccessibilityInsights.AutomationTests/AutomationTests.csproj
- src/AccessibilityInsights.AutomationTests/packages.config
- src/AccessibilityInsights.CoreTests/CoreTests.csproj
- src/AccessibilityInsights.CoreTests/packages.config
- src/AccessibilityInsights.DesktopTests/DesktopTests.csproj
- src/AccessibilityInsights.DesktopTests/packages.config
- src/AccessibilityInsights.Extensions.AzureDevOpsTests/Extensions.AzureDevOpsTests.csproj
- src/AccessibilityInsights.Extensions.AzureDevOpsTests/packages.config
- src/AccessibilityInsights.Extensions.GitHubAutoUpdateUnitTests/Extensions.GitHubAutoUpdateUnitTests.csproj
- src/AccessibilityInsights.Extensions.GitHubAutoUpdateUnitTests/packages.config
- src/AccessibilityInsights.Extensions.GitHubUnitTests/Extensions.GitHubUnitTests.csproj
- src/AccessibilityInsights.Extensions.GitHubUnitTests/packages.config
- src/AccessibilityInsights.Extensions.TelemetryTests/Extensions.TelemetryTests.csproj
- src/AccessibilityInsights.Extensions.TelemetryTests/packages.config
- src/AccessibilityInsights.ExtensionsTests/ExtensionsTests.csproj
- src/AccessibilityInsights.ExtensionsTests/packages.config
- src/AccessibilityInsights.RuleSelectionTests/RuleSelectionTests.csproj
- src/AccessibilityInsights.RuleSelectionTests/packages.config
- src/AccessibilityInsights.RulesTest/RulesTests.csproj
- src/AccessibilityInsights.RulesTest/packages.config
- src/AccessibilityInsights.SharedUxTests/SharedUxTests.csproj
- src/AccessibilityInsights.SharedUxTests/packages.config
- src/AccessibilityInsights.WebApiHostTests/WebApiHostTests.csproj
- src/AccessibilityInsights.WebApiHostTests/packages.config
- src/AccessibilityInsights.Win32Tests/Win32Tests.csproj
- src/AccessibilityInsights.Win32Tests/packages.config
Some unit tests project were only runnable via Run All, not as individual projects or tests. After some online research, I tried updating to the current MSTest adapters and it fixed the problem. All changes are in test code and auto-generated by Visual Studio
All unit tests build and pass, and I've verified that each unit test project can be run on its own without being part of Run All.
> Update all unit tests to use version 1.4 of the MSTest* adapters

- src/AccessibilityInsights.Extensions.AzureDevOps/Extensions.AzureDevOps.csproj
- src/AccessibilityInsights.Extensions.AzureDevOps/FileIssue/FileIssueHelpers.cs
- src/AccessibilityInsights.Extensions.AzureDevOps/FileIssue/IEBrowserEmulation.cs
We have occasionally noticed the WebBrowser used in the AzureDevops extension is unable to render the page and instead shows a white screen (even though viewing the source shows proper HTML). This PR applies a potential fix via feature controls. IE provides several feature controls in order to enhance the way the WebBrowser behaves. Earlier we set the Browser Emulation registry key to a high number [99999] which doesn't seem accurate - according to the docs and suggested fix, this key should be set to the values defined [here](https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/general-info/ee330730(v%3dvs.85)#browser-emulation). This affects what 'mode' web pages are rendered in (read more [here](https://docs.microsoft.com/en-us/previous-versions/wind …
> Add appropriate feature control registry keys to improve WebBrowser rendering

- src/AccessibilityInsights.Rules/Library/BoundingRectangleNotNull.cs
- src/AccessibilityInsights.Rules/PropertyConditions/ElementGroups.cs
- src/AccessibilityInsights.RulesTest/Library/BoundingRectangleNotNullTest.cs
- src/AccessibilityInsights.RulesTest/PropertyConditions/ElementGroupsTests.cs
When the thumb control of a WPF scrollbar is all the way down or up, the rectangle of the PageDown or PageUp buttons may be null.
It is possible this fix could be even more specific, testing to actually see if the vertical or horizontal scroll percent of the parent scrollbar is 0 or 100%. Such a test might be overkill, but thoughts are welcome.
> Fixed bug #205  Test reports null BoundingRectangle on ScrollBar button

- docs/GitBranchSetup.md
I find myself copy-pasting these commands occasionally and the > characters have to be removed. It would be easier if I could copy them at once to run.
> Remove > characters before commands in readme

- src/AccessibilityInsights.Extensions.GitHub/Extensions.GitHub.csproj
The microbuild nuget package import for the github issue extension was in a strange semi-installed state. This PR ensures it is properly imported. 
> Fix microbuild import in github extension

- src/AccessibilityInsights/Modes/TestModeControl.xaml.cs
We were encountering this issue: #227. The timing of when MainWindow's visibility is restored affects when UserControl_IsVisibleChanged in AutomatedChecks gets hit. Currently, the timing results in the automated checks listview's checkboxes effectively getting checked twice. This PR fixes the timing such that the boxes are not double-checked. 
> Restore mainwindow visibility earlier to fix automated checks IsVisible event timing

- build/signedbuild.yml
The current release script downloads the entire drop artifact. We only need 1 file, so this is to create a smaller artifact to accelerate the Release process (especially when we automate the Canary release)
> Attempt to create an MSI-only artifact from the signed build

- src/AccessibilityInsights.SharedUxTests/SharedUxTests.csproj
- src/AccessibilityInsights.SharedUxTests/Snapshots/Taskbar.snapshot
- src/AccessibilityInsights.SharedUxTests/ViewModels/ViewModelTests.cs
This PR removes the reference from SharedUxTests to UnitTestSharedLibrary so that UnitTestSharedLibrary does not need to be exposed from axe-windows. There is more to do here - it would be better to remove the utility entirely and mock out the tests loading an A11yElement. Doing this requires adding several fields to the IA11yElement interface so I'd like to chat about it offline first. This PR should decouple the projects for now so we can proceed with splitting the repos - will work on introducing mocking asyncronously.
> Remove reference from SharedUxTests to UnitTestSharedLibrary

- src/AccessibilityInsights.Automation/Automation.csproj
- src/AccessibilityInsights.WebApiHost/WebApiHost.csproj
Removing two references from ai-win projects to axe-windows projects. These references are not being used and will need to be severed if we plan to separate axe-windows
> Removing unneeded references to eventual axe-windows

- src/AccessibilityInsights.SetupLibrary/VersionSwitcherWrapper.cs
The code to copy VersionSwitcher had 2 bugs:
- It was passing the wrong data to Path.Combine, which threw an Exception
- If wasn't properly locking the file after copy
This code was working, then I did some code shuffling and apparently broke it. Tested by forcing an upgrade situation, ensuring that VersionSwitcher gets copied correctly, then ensuring that the upgrade version gets installed. Without this fix, it's impossible to upgrade or switch channels (change already exists in the branch with the channel selection UI, but I wanted to get it into master to fix potential upgrade cases).
> Fix problems when copying VersionSwitcher

- tools/scripts/release-cleanup.ps1
- This script will run in a power shell task to clean up releases.
- It will run after a custom nuget task to install OcktoKit is run.
- Sample run - https://dev.azure.com/mseng/1ES/_releaseProgress?_a=release-environment-logs&releaseId=990&environmentId=1110
> Adding the releases clean up script 

- src/AccessibilityInsights.Extensions.GitHubAutoUpdate/AutoUpdate.cs
- src/AccessibilityInsights.Extensions.GitHubAutoUpdateUnitTests/AutoUpdateUnitTests.cs
Issue #267 was caused by an incorrect production constructor in the AutoUpdate class. MEF requires a default constructor, which is different from a non-default constructor with a default argument. Changed to use a true default constructor.
> Fix issue #267

- src/AccessibilityInsights.Extensions.GitHubAutoUpdate/AutoUpdate.cs
- src/AccessibilityInsights.Extensions.GitHubAutoUpdate/ProductionChannelInfoProvider.cs
- src/AccessibilityInsights.Extensions.GitHubAutoUpdateUnitTests/AutoUpdateUnitTests.cs
- src/AccessibilityInsights.Extensions/Container.cs
- src/AccessibilityInsights.Extensions/Extensions.csproj
- src/AccessibilityInsights.Extensions/Interfaces/Upgrades/ReleaseChannelProvider.cs
- src/AccessibilityInsights/MainWindowHelpers/Initialize.cs
AutoUpdate needs to be responsive to ReleaseChannel settings (it currently only supports Production)
> Enable ReleaseChannel in AutoUpdate

- docs/AddUnitTests.md
- docs/AddingColorContrastTests.md
- docs/NewProject.md
- docs/Overview.md
- docs/RulesOverview.md
We want to keep the docs relatively up-to-date, so this reflects the rename to axe-windows for some assemblies. We could probably restructure some of the headings but since this area is still in some flux I don't think it makes sense to do until we have settled fully.
> Updates to the docs after axe-windows rename

- src/AccessibilityInsights.Rules/PropertyConditions/ContentView.cs
- src/AccessibilityInsights.Rules/PropertyConditions/ControlView.cs
- src/AccessibilityInsights.RulesTest/Library/Structure/ContentView/SpinnerTests.cs
- src/AccessibilityInsights.RulesTest/Library/Structure/ControlView/SpinnerTests.cs
- src/AccessibilityInsights.RulesTest/RulesTests.csproj
- Issue #272 ControlViewSpinnerStructure should allow ListItem
- Issue #268 ContentViewSpinnerStructure should allow ListItem
In both cases, the code now allows for 0 or more ListItem children of the spinner control.
Note: Keen observers of the documentation may notice that list items are permitted only when the Selection control pattern is present, and such a check is not done in this code. This is a shortcoming of several of the content/control view rules. However, since no rules currently check for such patterns, it is not the intent to remedy that as part of this change.
Another such failing is that the children are not actually checked to make sure they have the IsContentElement or IsControlElement properties set to true. This failing is common throughout these rules. And again, …
> Fixed two spinner Content/Control view issues.

- src/AccessibilityInsights.Core/Enums/RuleId.cs
- src/AccessibilityInsights.Rules/Library/Structure/ControlView/Scrollbar.cs
- src/AccessibilityInsights.Rules/PropertyConditions/ControlView.cs
- src/AccessibilityInsights.Rules/Rules.csproj
- src/AccessibilityInsights.RulesTest/Library/Structure/ControlView/ScrollbarTest.cs
- src/AccessibilityInsights.RulesTest/RulesTests.csproj
This PR adds a rule that checks whether Control View scrollbars adhere to the structure given here: https://docs.microsoft.com/en-us/windows/desktop/WinAuto/uiauto-supportscrollbarcontroltype
It is partly in response to issue #274 - when a complex structure like a tab has children controls like a scrollbar, the scrollbar's children can be checked using this rule instead of checking the full tree at the tab-level.
> New rule for scrollbar structure

- build/compliance-build.yml
Compliance build is failing because it's looking for Extensions.AutoUpdate, which has been removed. It also fails to look for Extensions.GitHub, which was recently added. I also sorted the projects alphabetically, just for housekeeping reasons.
> Update Extension projects for compliance build

- src/AccessibilityInsights.SetupLibrary/MsiUtilities.cs
- src/AccessibilityInsights.SharedUx/Misc/SetupExceptionReporter.cs
- src/AccessibilityInsights.SharedUx/SharedUx.csproj
- src/AccessibilityInsights/Modes/StartUpModeControl.xaml.cs
Make the release notes page in the What's New dialog point to a release-specific page, instead of a generic page in the docs. This makes it work for all channels, and eventually lets us reduce the amount of duplicated content that we need to maintain
Uri before change was a fwlink that pointed to https://accessibilityinsights.io/docs/en/windows/reference/releases. 
Uri after the change is build-specific. With build 1.1.0831.02 installed, it points to https://github.com/Microsoft/accessibility-insights-windows/releases/tag/v1.1.0831.02.
> Issue [#298] - direct link from What's new page to release-specific page

- src/AccessibilityInsights.Extensions.Telemetry/AITelemetry.cs
ContextProperties are intended to be included on all client telemetry, and are properly being sent on all published actions, but they are not included on Exceptions. As a result, it's much more difficult to use Exception telemetry in a meaningful way. This change adds the ContextProperties into the Exception data stream
I've forced an Exception on my local build, and confirmed that the following customDimension field is included in the Exception telemetry, with the following values:
AppSessionID = 5aa1b757-ec2e-4c52-8f4b-42ae7c8db0ce
InstallationID = f30ece9b-90a3-4e51-8d14-5ef47b54c1d7
ModeName  = Inspect
ModeSessionId = 4e38fd7c-1b11-43b1-8072-d7f62846ce12
ReleaseChannel = Insider
SessionType = Desktop
Version = 1.1.836.1
View = Live
> Note: After the PR has been created, certain checks …
> Include ContextProperties in reported exceptions

- src/AccessibilityInsights.Extensions.AzureDevOps/AzureDevOpsIntegration.cs
This PR proactively limits the characters allowed in the Azure DevOps bug URLs to a basic (e.g. < 127 ascii) set to limit navigation issues. For example, filing a bug from any rule with how-to-fix text containing the middle dot · character can lead to a redirect loop if the user signs out from the hosted web browser prior to filing the issue. After this PR, filing an issue from any of these rules properly navigates to the page. Any non-basic characters are omitted from the text.
> Simplify bug URLs with special characters

- src/AccessibilityInsights.SharedUx/Properties/Resources.Designer.cs
- src/AccessibilityInsights.SharedUx/Properties/Resources.resx
This PR fixes #306 . The PR also includes an updated comment for a different resource string.
> fixing a typo in 'to file issues' error message

- src/MSI/Product.wxs
Build 1.1.835.1 introduced a change that caused the app to hang when starting on a specific machine. The root cause was that Microsoft.Deployment.WindowsInstaller.dll wasn't being found because it was installed as part of an extension instead of part of the app. Most machines successfully loaded the assembly as part of the AutoUpdate code--it's not clear why this machine behaves differently, but it's 100% reproducible on this machine. This change moves the assembly into the same folder as the main app so it will reliably be found when needed, either by the main app or by the AutoUpdate code.
Tested in 2 stages:
1. On an affected machine, manually moved Microsoft.Deployment.WindowsInstaller.dll to the app folder and successfully launched the app
2. Built a private MSI, installed it on the …
> Move Microsoft.Deployment.Windows.Installer.dll up to main app

- src/AccessibilityInsights.Extensions.Telemetry/AITelemetry.cs
Telemetry has 2 sets of properties--context properties and event-specific properties. The intent is that event-specific properties will take precedence over context properties if the same key exists in both sets of properties.
The code to merge was using the Dictionary.Add method, which throws an ArgumentException if the key being added already exists. To merge properly, we need to use the syntax that overrides an existing key.
(Found this while running bug filing inside the debugger, with the telemetry extension enabled)
> Code was dropping telemetry if conflicting properties were being set

- src/AccessibilityInsights.Extensions.AzureDevOps/AzureDevOpsIntegration.cs
This PR follows up on #313 in which we limited the set of allowable characters in our bug URLs to respond to odd behavior when the user is redirected to login - as suggested by @DaveTryon , instead of removing characters outside our allowable range, we now replace them with preconfigured alternatives or a '?'.
> Substituting characters to be more friendly to bug-url generation

- src/AccessibilityInsights.SharedUx/Resources/Styles.xaml
- src/AccessibilityInsights/Modes/TestModeControl.xaml
- src/AccessibilityInsights/Modes/TestModeControl.xaml.cs
- src/AccessibilityInsights/Properties/Resources.Designer.cs
- src/AccessibilityInsights/Properties/Resources.resx
This is for issue #186 - we are adding text so that users are aware of the role of automated vs manual testing in accessibility. 
> Adding info about the role of automated checks

- src/AccessibilityInsights.Actions/Actions/LoadAction.cs
- src/AccessibilityInsights.Core/Bases/A11yElement.cs
- src/AccessibilityInsights.CoreTests/Bases/A11yElementTests.cs
This content needs to be created so we can generate xml documentation files to accompany the axe-windows NuGet package. This is only part of the work needed to get Axe.Windows.Core ready, but it's a start.
> Add documentation to public members of A11yElement

- .github/CODEOWNERS
The runtime components will be removed once the new repo is set up. During this change, PRs should be limited so conflicts are less likely to occur. This temporary change adds Rob/Ortiga/myself to the code owners so we are notified when such changes may need to happen
> Add code owners for runtime components

- src/AccessibilityInsights/MainWindowHelpers/AutoUpdate.cs
- src/AccessibilityInsights/Modes/ConfigurationModeControl.xaml.cs
Addressing #336: If AI-Win attempts to install a new version of itself, whether from auto-update or from channel change, the UAC dialog is obscurred.
This change causes AI-Win to backup its current topmost state, set topmost to false, run the update/channel switch, and then restore its topmost state (if AI-Win is still open). This is similar to what we do for the ADO sign in dialog scenario.
See bug for before screenshots. 
UAC dialog is on top of AI-Win:
> Stop main window from being topmost while UAC prompt is displayed

- build/compliance-build.yml
- build/signedbuild.yml
- docs/Scenarios.md
PR [#353] removed the check-automation.ps1 file, but left some references in scripts and documentation. As such, the signed build failed. Remove the remaining references.
> Remove remaining references to check-automation.ps1

- .github/CODEOWNERS
We previously had extra code owners for the files that were duplicated between ai-win and axe-windows. Now that the files have been fully moved, we no longer need the code owner information
> Remove axe-windows files from code owners

- src/AccessibilityInsights.CommonUxComponents/Dialogs/MessageDialog.xaml
- src/AccessibilityInsights.SharedUx/Dialogs/TelemetryApproveContainedDialog.xaml
- src/AccessibilityInsights.SharedUx/Resources/HighContrast/Brushes.xaml
- src/AccessibilityInsights.SharedUx/Resources/Light/Brushes.xaml
- src/AccessibilityInsights.SharedUx/Resources/Styles.xaml
- src/AccessibilityInsights/Dialogs/UpdateDialog.xaml
- src/AccessibilityInsights/Modes/StartUpModeControl.xaml
To address #342- [BUG] Insufficient contrast ratio for Update button, this PR updates the hover and active state colors of the blue buttons in our app. This had a side effect of fixing some pretty serious high contrast theme issues with our update dialog. I included screenshots of the most significantly affected buttons--I can add more for the other buttons if desired, but there are a lot and the changes are minor.
There should only be visual changes from this PR.
Update button hover state (before/after on top/bottom):
Normal:
HC White:
HC Black:
Other blue buttons were touched with varying levels of improvement along the same lines as those above.
> Improve color contrast of blue buttons in app

- src/AccessibilityInsights/Dialogs/UpdateDialog.xaml
- src/AccessibilityInsights/Dialogs/UpdateDialog.xaml.cs
UpdateDialog.Topmost now matches MainWindow.Topmost instead of always being true. This makes more sense because the scenarios where the two are out of sync are undesirable.
This addresses #351- [BUG] Update Dialog shows up on top of release notes. If the user has selected to be always on top, AI-Win will be on top of their web browser when they open release notes, so the update dialog should be as well. In @DaveTryon's scenario where always on top is not selected, the update dialog will no longer float on top of the release notes.
> Change UpdateDialog to only be topmost when MainWindow is topmost

- src/AccessibilityInsights.SharedUx/Dialogs/TextRangeFindDialog.xaml.cs
- src/AccessibilityInsights.SharedUx/Enums/HighlighterColor.cs
- src/AccessibilityInsights.SharedUx/Highlighting/Highlighter.cs
- src/AccessibilityInsights.SharedUx/Highlighting/HollowHighlightDriver.cs
- src/AccessibilityInsights.SharedUx/Highlighting/TextRangeHilighter.cs
- src/AccessibilityInsights.SharedUx/SharedUx.csproj
The HighlighterColor enum is defined in axe-windows (https://github.com/microsoft/axe-windows/blob/master/src/Core/Enums/HighlighterColor.cs), but it is only used in AIWin. This change ports it to AIWin. A separate change will remove it from axe-windows. If you look at the commits, you'll see that I went through a step where the enum was named HighlighterColorTemp to make sure that there weren't any lurking references. Goal is that the UI is unchanged, other that the enum is defined in a different assembly
> Move HighlighterColor to shared ux

- src/AccessibilityInsights.SharedUx/KeyboardHelpers/HotKey.cs
- src/AccessibilityInsights.SharedUx/KeyboardHelpers/HotKeyHandler.cs
- src/AccessibilityInsights.SharedUx/SharedUx.csproj
- src/AccessibilityInsights.SharedUxTests/KeyboardHelpers/HotKeyUnitTests.cs
- src/AccessibilityInsights.SharedUxTests/SharedUxTests.csproj
- src/AccessibilityInsights/MainWindow.xaml.cs
- src/AccessibilityInsights/MainWindowHelpers/Initialize.cs
- src/AccessibilityInsights/MainWindowHelpers/StateMachine.cs
The HotKey handlers were in desktop by mistake. They belong in SharedUx. Port the classes over. The HotKeyHandlers class was blending an IDisposable with a singleton, which is a bizarre mix. I converted it to not use IDisposable.
Tested by running through multiple Hotkey scenarios (loading, changing, triggering, saving, etc.)
> Port HotKey classes from axe-windows to SharedUx

- src/AccessibilityInsights/Modes/EventModeControl.xaml.cs
Note: This is a reprise of #375, which was auto-closed when I deleted the wrong branch from my fork 😒 
The current highlighter behavior is strange after opening an events file. It is enabled by default and always draws with the snapshot beaker (which doesn't work). This change does 2 things:
1. When the opening an events file, the global highlighter state is disabled by default (and the command bar reflects this state).
2. The user can optionally enable the highlighter via the command bar. When this happens, the highlighter is just the highlighter--no snapshot button, no tooltip.
> Hide the highlighter by default when opening an Events file

- src/AccessibilityInsights.SharedUx/Dialogs/HotkeyGrabDialog.xaml.cs
- src/AccessibilityInsights.SharedUx/KeyboardHelpers/HotKey.cs
- src/AccessibilityInsights.SharedUxTests/KeyboardHelpers/HotKeyUnitTests.cs
HotKeys have 2 issues:
1. When adding multiple modifiers via the UI, extra spaces get added. This causes the "check for duplicates" to fail to find duplicates
2. When parsing the multiple modifiers with spaces, the modifiers get completely lost. This is just weird.
To maintain compatibility with default and previously broken customizations, we're removing the spaces when generated in the UI, and we're respecting the spaces if they exist. Added a unit test to cover the case with spaces; fixed a typo in a method name
> Fix hot key issues

- src/AccessibilityInsights/MainWindow.xaml.cs
- src/AccessibilityInsights/Modes/LiveModeControl.xaml.cs
Addresses #381- AI-Win crashes if the user attempts to run tests immediately after changing the "What to select" value. Previously, the selected data was cleared when scope changed, but the ui was not changed to reflect this. This PR clears the ui so that the user cannot attempt to run tests in this scenario.
> Clear live mode when selection scope is changed

- src/AccessibilityInsights.SharedUx/SharedUx.csproj
- src/AccessibilityInsights.SharedUx/packages.config
- src/AccessibilityInsights.SharedUxTests/SharedUxTests.csproj
- src/AccessibilityInsights.SharedUxTests/packages.config
- src/AccessibilityInsights/AccessibilityInsights.csproj
- src/AccessibilityInsights/packages.config
- src/UITests/UITests.csproj
- src/UITests/packages.config
Update the NuGet packages to use the Axe-Windows 0.1.1-prerelease, but keep NewtonSoft 10.0.3 (needed for ADO issue filing). The "special handling" of Newtonsoft will presumably go away once the package includes both Sarif and Newtonsoft as dependencies, instead of building the assemblies into the package
> Update NuGet packages to use the Axe-Windows 0.1.1-prerelease

- src/AccessibilityInsights.Extensions.GitHubAutoUpdate/AutoUpdate.cs
- src/AccessibilityInsights.Extensions.GitHubAutoUpdateUnitTests/AutoUpdateUnitTests.cs
- src/AccessibilityInsights.Extensions/Interfaces/Upgrades/UpgradeOption.cs
- src/AccessibilityInsights.SharedUx/Controls/SettingsTabs/AboutTabControl.xaml
- src/AccessibilityInsights.SharedUx/Controls/SettingsTabs/AboutTabControl.xaml.cs
- src/AccessibilityInsights.SharedUx/Properties/Resources.Designer.cs
- src/AccessibilityInsights.SharedUx/Properties/Resources.resx
- src/AccessibilityInsights.SharedUx/SharedUx.csproj
- src/AccessibilityInsights.SharedUx/ViewModels/AboutTabViewModel.cs
- src/AccessibilityInsights/MainWindowHelpers/AutoUpdate.cs
- src/AccessibilityInsights/MainWindowHelpers/ControlHelper.cs
- src/AccessibilityInsights/Properties/Resources.Designer.cs
- src/AccessibilityInsights/Properties/Resources.resx
Update how version and UIAccess are displayed. Make the UIAccess status more accessible as a result.
Changes to the version bar:
- UIAccess information has been removed from the version bar.
- In prerelease versions (defined as being on Canary or Insider channel, or running a build newer than the current build in the Production channel), the build is called out as a Prerelease build.
- If the Channel is Production AND the version isn't newer than the current Production build, the version bar will be empty.
Changes to the about dialog appear below:
- The version label is now a hyperlink that points to the version-specific release notes.
- UIAccess availability is now displayed in the about dialog.
Screenshot of new about page (with highlighted differences) appears below. The lack of …
> Update how version and UIAccess are displayed

- Channels/Production/release_info.json
- Channels/Production/release_notes.md
Build 1.1.883.1 has been in the Insider channel for 2 weeks without reported issue. We want to promote it to the Production channel. This snaps us to our pattern of allowing Production clients to remain on the Current-1 version. Release notes were copied from the Insider channel release notes, then updated with the new date and channel.
> Promote Build 1.1.883.1 to Production channel as an optional upgrade

- src/AccessibilityInsights.SharedUx/Telemetry/TelemetryAction.cs
- src/AccessibilityInsights.SharedUx/Telemetry/TelemetryProperty.cs
- src/AccessibilityInsights.SharedUxTests/Telemetry/LoggerUnitTests.cs
- src/AccessibilityInsights/AccessibilityInsights.csproj
- src/AccessibilityInsights/Dialogs/UpdateDialog.xaml.cs
- src/AccessibilityInsights/MainWindow.xaml.cs
- src/AccessibilityInsights/MainWindowHelpers/AutoUpdate.cs
- src/AccessibilityInsights/MainWindowHelpers/StateMachine.cs
- src/AccessibilityInsights/MainWindowHelpers/TestMode.cs
- src/AccessibilityInsights/Misc/TelemetryEventFactory.cs
- src/AccessibilityInsights/Modes/ConfigurationModeControl.xaml.cs
- Connect 2 recently-added telemetry events that were never connected.
- Change the Logger unit tests to be independent of specific values for TelemetryProperty and TelemetryAction
- Remove unused values for TelemetryProperty and TelemetryAction. I've confirmed with the existing telemetry that none of these values are being used in current builds. Many of these old values were remnants of code that was removed more than a year ago.
- Create AccessibilityInsights.Misc.TelemetryEventFactory to combine several closely-related pieces of code into a single class. This replaces most of the instances in the AccessibilityInsights project where Logger.PublishTelemetryEvent was being called with one or more TelemetryProperty values)
> Note: After the PR has been created, certain checks will be …
> Clean up telemetry

- src/AccessibilityInsights/MainWindowHelpers/AutoUpdate.cs
Decision about showing the upgrade should return false for `AutoUpdateOption.NewerThanCurrent`. This is a new enum value, but the consuming logic in the UI wasn't updated to handle the new value.
> Fix check for prompting for upgrades

- src/AccessibilityInsights.CommonUxComponents/Controls/ProgressRingControl.xaml.cs
- src/AccessibilityInsights.Win32/Win32Helper.cs
- src/AccessibilityInsights/Modes/TestModeControl.xaml.cs
Update the existing Jaws repaint glitch workaround. This glitch is apparently caused by interaction of WPF and the Jaws-installed screen driver. Hide the window before invalidating and forcing a repaint. To minimize flash, only do this is we have reason to believe that Jaws is on the machine.
Old behavior without Jaws
Old behavior with Jaws
New behavior without Jaws
New behavior with Jaws
> Update the existing Jaws repaint glitch workaround

- src/AccessibilityInsights.SharedUx/Telemetry/TelemetryProperty.cs
- src/AccessibilityInsights/MainWindowHelpers/TestMode.cs
- src/AccessibilityInsights/Misc/TelemetryEventFactory.cs
A recent change used ProtocolMode incorrectly (although it would have never appeared in the telemetry stream). Removing it completely, since it's currently an unsupported feature and we don't really know how we want it to be at this time.
> Remove PrototolMode. Fix where I had misused it in telemetry

- src/AccessibilityInsights/MainWindowHelpers/AutoUpdate.cs
Fix an error in Upgrade_DoInstallation telemetry (the wrong value was being used for the result). Instead of passing an `UpdateResult` (values of *Unknown*, *Success*, or *NoUpdateAvailable*, we were passing in the `AutoUpdateOption` (values of *Unknown*, *NewerThanCurrent*, *Current*, *OptionalUpgrade*, or *RequiredUpgrade*). The `AutoUpdateOption` is already being sent in the Upgrade_GetUpgradeOption telemetry, so we're currently sending the `AutoUpdateOption` twice but never sending the `AutoUpdateOption`)
> Fix error in Upgrade_DoInstallation telemetry

- src/AccessibilityInsights/MainWindow.xaml.cs
- src/AccessibilityInsights/Modes/ConfigurationModeControl.xaml
- src/AccessibilityInsights/Modes/ConfigurationModeControl.xaml.cs
This change responds to issue #364 by forcing the settings and connection buttons to always go to the application and connection tabs. Before this change, the settings button acts like a toggle - selecting it while in settings view will take the user out of settings view. Now, the settings button always goes to the application tab.
> Remove toggle-behavior of settings button

- build/signedbuild.yml
Revise the signed build phases
- Move compliance-related pieces of SignedDebug phase to ComplianceDebug phase
- Fix typo that was preventing CredScan from running for AzureDevOps project
- Enable TSA (uses build variables for database and email details)
- SignedRelease phase uploads BinSkim
- ComplianceDebug phase uploads CredScan, FxCop, and PoliCheck
- Make the task names more indicative of what they're actually doing
Where checks occur after this change:
AutoApplicability: ComplianceDebug
BinSkim: SignedRelease
Component Detection: ComplianceRelease
CredScan: ComplianceDebug
FxCop: ComplianceDebug
PoliCheck: ComplianceDebug
> Revise the signed build phases

- src/AccessibilityInsights.SharedUx/Controls/TestTabs/TabStopControl.xaml.cs
Previously, started listening to events and then set focus to the target element. This didn't work because the UIA event listener wasn't actually registered before the focus changed--there is a slight gap between `RegisterAutomationEventListener` completing and the listener actually starting.
This PR delays setting focus on the target element until we get a message from the event listener confirming that it has started listening.
> Show first tab stop in tab stops test

- build/signedbuild.yml
Stop publishing the MSI to the drop share because we are no longer using it. The MSI files built from the master branch auto-release to GitHub as Canary builds. The MSI files built from other branches are available as build artifacts. Once this PR is merged, I'll also update the build definition to stop defining DropRoot as a build variable, and clean up the MSI files that are already there.
> Stop publishing the MSI to the drop share

- build/prbuild.yml
- src/UITests/UITests.csproj
- src/UITests/UITests.runsettings
This PR tries adds video recording to UI tests - you can see an example [here](https://dev.azure.com/accessibility-insights/Accessibility%20Insights/_build/results?buildId=1763&view=ms.vss-test-web.build-test-results-tab&runId=4870&resultId=100049&paneView=attachments)
docs [here](https://docs.microsoft.com/en-us/visualstudio/test/configure-unit-tests-by-using-a-dot-runsettings-file?view=vs-2019#video-data-collector)
One side effect is that we have very small videos for unit tests as well. I've added a separate task to move our UI tests to a separate job to see if we exclude unit tests from the video capturing.
This change only affects our PR remote build, so no additional product validation was done
> Add video recording to ui tests

- src/UITests/AIWinSession.cs
- src/UITests/LoadTestFile.cs
This PR creates a result file including Windows Event Logs for the duration of the test run. It attaches this result file to the TestContext so that the Visual Studio Test Runner can pick it up in the remote build.
UITest change only
> Add event logs to test result

- src/AccessibilityInsights/Modes/StartUpModeControl.xaml
- src/UITests/AIWinSession.cs
- src/UITests/GettingStartedPage.cs
- src/UITests/LoadTestFile.cs
- src/UITests/UILibrary/AIWinDriver.cs
This change adds the a11y test file to UI test output, similar to how we add event logs. If a UI test fails because of an accessibility issue, the a11y test file should show up in the ADO attachments for that test.
We assume a 1:1 mapping between our test methods and a11y test files because any failure will stop test execution. If this changes in the future, we will need to ensure we can name each a11y test file differently. We could do this now via renaming / copying, but it would be nicer if Axe.Windows could accept a file name for the result file.
Here is an [example](https://dev.azure.com/accessibility-insights/Accessibility%20Insights/_build/results?buildId=1819&view=ms.vss-test-web.build-test-results-tab) of a failing accessibility issue.
-----
This PR also removes some unnecessary …
> Adding a11ytest file to output of UI tests, clean up some lingering code

- src/UITests/TelemetryDialog.cs
Two previous PRs led to a mismatch in the signature of ScanAIWin. This updates the usage in TelemetryDialog to utilize the new signature.
> Fixing merge conflict in telemetry dialog

- build/compliance-build.yml
- src/UITests/GettingStartedPage.cs
- src/UITests/LoadTestFile.cs
- src/UITests/TelemetryDialog.cs
We need to get the Screen Resolution Utility extension in the account where the compliance build runs. Until this happens, the UI tests must be skipped. The extension is available and running with our PR builds.
> temporarily skip UI tests in the compliance build

- src/UITests/AIWinSession.cs
We gave the UITests a loongg delay so that they would run on the ado build. This PR replaces that delay with a repeated retry so that quicker test machines don't have to wait as long to run ui tests. 
> Change WinAppDriver connection to retry instead of having a long delay

- src/AccessibilityInsights.SharedUx/Controls/EventDetailControl.xaml
- src/AccessibilityInsights.SharedUx/Controls/EventRecordControl.xaml
- src/AccessibilityInsights.SharedUx/Properties/AutomationIDs.cs
- src/AccessibilityInsights/Modes/EventModeControl.xaml
- src/UITests/AIWinSession.cs
- src/UITests/LoadEventFile.cs
- src/UITests/TestFiles/WildlifeManagerTest.a11yevent
- src/UITests/UILibrary/AIWinDriver.cs
- src/UITests/UITests.csproj
This PR adds an initial UI test for event-loading. It opens a saved event file, clicks to show certain events, and then verifies the number of rows in the window. Getting more granular (e.g. how many property rows vs event detail rows) was difficult due to WinAppDriver oddities. We may explore that further in a future PR. For now, we validate the number of rows across various views and verify there are no accessibility issues. This PR only touches test code and automation IDs in our UI.
> Add initial UI tests for loading an event

- src/AccessibilityInsights.SharedUx/Controls/ChannelConfigControl.xaml
- src/AccessibilityInsights.SharedUx/Controls/SettingsTabs/AboutTabControl.xaml
- src/AccessibilityInsights.SharedUx/Controls/SettingsTabs/ApplicationSettingsControl.xaml
- src/AccessibilityInsights.SharedUx/Dialogs/HotkeyGrabDialog.xaml
- src/AccessibilityInsights.SharedUx/Properties/AutomationIDs.cs
- src/AccessibilityInsights/MainWindow.xaml
- src/AccessibilityInsights/Modes/ConfigurationModeControl.xaml
- src/UITests/GettingStartedPage.cs
- src/UITests/LoadEventFile.cs
- src/UITests/LoadTestFile.cs
- src/UITests/SettingsPage.cs
- src/UITests/TelemetryDialog.cs
- src/UITests/UILibrary/AIWinDriver.cs
- src/UITests/UITests.csproj
This UI test includes the following:
- spot-checking the application settings tab
- accessibility testing of the application settings tab
- spot-checking the about tab
- accessibility testing of the about tab
- changing a keyboard shortcut and validating it works
- validating the save and close button becomes enabled with changed options
Here's a video: https://dev.azure.com/accessibility-insights/Accessibility%20Insights/_build/results?buildId=1880&view=ms.vss-test-web.build-test-results-tab&runId=5176&resultId=100147&paneView=attachments
> Add a UI test for the settings page

- src/AccessibilityInsights.SharedUx/Controls/HierarchyControl.xaml
- src/AccessibilityInsights.SharedUx/Controls/ScannerResultControl.xaml
- src/AccessibilityInsights.SharedUx/Controls/TestTabs/AutomatedChecksControl.xaml
- src/AccessibilityInsights.SharedUx/Properties/AutomationIDs.cs
- src/AccessibilityInsights/Modes/SnapshotModeControl.xaml
- src/UITests/LoadTestFile.cs
- src/UITests/UILibrary/LiveMode.cs
Expands coverage of LoadTestFile UITest to:
- Verify the count of results in listview and textblock above listview
- Expand results and click through to the results in UIA tree view for a specific element
- Spot check UIA tree
- Verify the correct number of results show up and that there is some how to fix text
- Spot check properties and patterns
- Switch to a different element in the UIA tree
- Repeat some validation for newly selected element
> Significantly improve LoadTestFile UITest coverage

- build/compliance-build.yml
- build/prbuild.yml
- build/signedbuild.yml
This PR changes usages of VS 2017 to VS 2019. The PR was made from VS 2019 after opening the same solution saved by VS 2017. Exploring whether the builds still pass, whether other changes will show up, etc.
> Changing usages of VS 2017 to VS 2019

- build/prbuild.yml
- build/ui-test-job.yml
We're experimenting with creating separate jobs for our UI tests that can run in parallel. We're using YAML templates in order to accomplish this. This PR adds a template for the ui-test-job and executes it from the prebuild file. If it works, we have opportunities to refactor some of our other build scripts via templates.
> Adding initial ui-test-job template

- build/build-and-unit-tests.yml
- build/build-without-fakes.yml
- build/prbuild.yml
This PR attempts to simplify the PR YAML build by creating and using a template for the build & unit test job. This template is called once with debug and again with release. There are template variables for CG and license header checks. There should be no functional change after this PR is merged - it is intended to simply rearrange how the tasks are defined.
> Simplify YAML structure of PR builds

- src/AccessibilityInsights.SharedUx/ViewModels/ColorContrastViewModel.cs
This changes the threshold for the relative luminance calculations, per #391. 
> Update Luminance Calculations

- build/signedbuild.yml
Debug UI tests are failing in the signed build with:
Initialization method UITests.LiveMode.TestInitialize threw exception. System.ComponentModel.Win32Exception: A referral was returned from the server.
at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
at System.Diagnostics.Process.Start()
at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
at System.Diagnostics.Process.Start(String fileName, String arguments)
at UITests.AIWinSession.LaunchApplicationAndAttach() in \src\UITests\AIWinSession.cs:line 71
at UITests.AIWinSession.Setup() in \src\UITests\AIWinSession.cs:line 36
at UITests.LiveMode.TestInitialize() in \src\UITests\LiveMode.cs:line 85
This PR removes the debug UI tests to unblock that build. The release UI tests still run. Our PR builds …
> Remove debug ui tests in signed build

- build/signedbuild.yml
We removed the debug UI test job int he signed build but forgot to remove the dependency on it. Removing now so the signed build fully runs.
> Removing dependency on deleted debug UI test job

- src/AccessibilityInsights.Extensions.GitHub/ConfigurationModelControl.xaml
- src/AccessibilityInsights.Extensions.GitHub/Extensions.GitHub.csproj
- src/AccessibilityInsights.Extensions.GitHub/Properties/AutomationIDs.cs
- src/AccessibilityInsights.SharedUx/Controls/SettingsTabs/ConnectionControl.xaml
- src/AccessibilityInsights.SharedUx/Properties/AutomationIDs.cs
- src/AccessibilityInsights/Modes/ConfigurationModeControl.xaml
- src/UITests/SettingsPage.cs
- src/UITests/UITests.csproj
This PR adds a UITest that checks if the connection tab in settings has radio buttons for both issue filing extensions and does a basic validation of the save button's enabled state change. AutomationIDs are added as appropriate. 
[Screencap here](https://dev.azure.com/accessibility-insights/Accessibility%20Insights/_apis/test/Runs/5690/Results/100004/Attachments/3)
> Add UITest for Connection settings tab

- src/AccessibilityInsights.SharedUx/Controls/ChannelConfigControl.xaml
- src/AccessibilityInsights.SharedUx/Controls/EventRecordControl.xaml
- src/AccessibilityInsights.SharedUx/Controls/SettingsTabs/AboutTabControl.xaml
- src/AccessibilityInsights.SharedUx/Controls/SettingsTabs/ApplicationSettingsControl.xaml
- src/AccessibilityInsights.SharedUx/Dialogs/HotkeyGrabDialog.xaml
- src/AccessibilityInsights.SharedUx/Properties/AutomationIDs.cs
- src/AccessibilityInsights/MainWindow.xaml
- src/AccessibilityInsights/Modes/ConfigurationModeControl.xaml
- src/UITests/LoadEventFile.cs
- src/UITests/SettingsPage.cs
- src/UITests/UILibrary/AIWinDriver.cs
This change renames some of the Automation IDs so that each is scoped by the control it comes from. After doing this, I alphabetized the list. This change should only affect our UI tests.
- [UI tests validated] Run through of all [test scenarios](https://github.com/Microsoft/accessibility-insights-windows/blob/master/docs/Scenarios.md) completed?
- (no) Does this address an existing issue? If yes, Issue# - 
- (no) Includes UI changes?
> Rename and reorder Automation IDs for readability

- build/ui-test-job.yml
We've seen some issues with the WinAppDriver Stop build task. Since tests have already finished at that point, the build should continue.
> Don't block build if WinAppDriver Stop command has error

- src/UITests/GettingStartedPage.cs
- src/UITests/LiveMode.cs
- src/UITests/LoadEventFile.cs
- src/UITests/LoadTestFile.cs
- src/UITests/SettingsPage.cs
- src/UITests/TelemetryDialog.cs
- src/UITests/UILibrary/AIWinDriver.cs
This PR only modifies the UI Tests. We add messages to the asserts so that errors are more actionable. This is particularly important because a test method includes a full scenario with multiple screens and checks.
> Adding assert text messages in UI tests

- src/AccessibilityInsights/AccessibilityInsights.csproj
- src/AccessibilityInsights/MainWindowHelpers/AutoUpdate.cs
- src/AccessibilityInsights/MainWindowHelpers/ControlHelper.cs
There were 2 errors here:
1. The code to display the PreRelease used != when it should have used ==. Fixed by correcting the check.
2. There was a timing issue. UpdateVersionString was getting called before the AutoUpdate module completed, so it always used the default (which always set the PreRelease text because of the first error). Fixed by explicitly calling UpdateVersionString after the upgrade check completes.
Testing: Explicitly force all return states that the updater can return, confirm the version bar text is correctly set in each case.
> Fix prerelease build text

- build/ui-test-job.yml
- src/UITests/GettingStartedPage.cs
- src/UITests/LiveMode.cs
- src/UITests/LoadEventFile.cs
- src/UITests/LoadTestFile.cs
- src/UITests/SettingsPage.cs
- src/UITests/TelemetryDialog.cs
- src/UITests/TestCategory.cs
- src/UITests/UITests.csproj
This PR uses TestCategory to disable the LiveMode UI test until it can be made more dependable.
The TestCategory class is introduced to define TestCategories in a more structured way. This is in line with [what axe-windows does](https://github.com/microsoft/axe-windows/blob/master/src/UnitTestSharedLibrary/TestCategory.cs).
> Add LiveMode TestCategory to temporarily disable flaky UI test

- src/AccessibilityInsights.SharedUx/SharedUx.csproj
- src/AccessibilityInsights.SharedUx/packages.config
- src/AccessibilityInsights.SharedUxTests/SharedUxTests.csproj
- src/AccessibilityInsights.SharedUxTests/packages.config
- src/AccessibilityInsights/AccessibilityInsights.csproj
- src/AccessibilityInsights/packages.config
- src/MSI/Product.wxs
- src/UITests/UITests.csproj
- src/UITests/packages.config
Update to Axe.Windows 0.3.2 (VS made all of the changes to the .csproj and .config files). Manually update Product.wxs to reflect the revised fileset (1 new assembly in Axe.Windows, 4 new dependent assemblies).
While validating this, I found an issue (cause unknown) in the thread handling, with the following behavior:
1. Start AIWin under the debugger
2. Open a file (A11yEvent or A11yTest)
3. Close AIWin
The UI closes and the app should be done, but a thread is still running, meaning that you need to kill the app via the debugger. This problem is limited to running with the debugger, so it should not be a blocker for customer use.
> Upgrade from Axe.Windows 0.3.1 to Axe.Windows 0.3.2

- src/AccessibilityInsights.Extensions.GitHubAutoUpdateUnitTests/Extensions.GitHubAutoUpdateUnitTests.csproj
- src/AccessibilityInsights.Extensions.GitHubAutoUpdateUnitTests/app.config
- src/AccessibilityInsights.Extensions.GitHubAutoUpdateUnitTests/packages.config
- src/AccessibilityInsights.Extensions.GitHubUnitTests/Extensions.GitHubUnitTests.csproj
- src/AccessibilityInsights.Extensions.GitHubUnitTests/app.config
- src/AccessibilityInsights.Extensions.GitHubUnitTests/packages.config
- src/AccessibilityInsights.SharedUxTests/SharedUxTests.csproj
- src/AccessibilityInsights.SharedUxTests/app.config
- src/AccessibilityInsights.SharedUxTests/packages.config
I approved dependabot-suggested change #459, then realized that it had only changed the package.config files. That's an incomplete change, since it completely ignores the .csproj and app.config files, as well as NuGet-based dependencies. This PR makes the change via VisualStudio, so it picks up all of the additional changes. These changes impact only unit tests, not production code.
> Use VS to update to dependabot-suggested version of System.Threading.Tasks.Extensions

- src/AccessibilityInsights.Extensions.GitHubAutoUpdateUnitTests/Extensions.GitHubAutoUpdateUnitTests.csproj
- src/AccessibilityInsights.Extensions.GitHubAutoUpdateUnitTests/packages.config
- src/AccessibilityInsights.Extensions.GitHubUnitTests/Extensions.GitHubUnitTests.csproj
- src/AccessibilityInsights.Extensions.GitHubUnitTests/packages.config
- src/AccessibilityInsights.SharedUxTests/SharedUxTests.csproj
- src/AccessibilityInsights.SharedUxTests/packages.config
Dependabot wanted to move to a newer version of Castle.Core (see #456), but that needs to be paired with an update to Moq. This updates the unit tests to the latest stable version
> Update to Moq version 4.12.0 (based on dependabot suggestion)

- src/AccessibilityInsights.Extensions.AzureDevOps/AzureBoardsIssueReporting.cs
- src/AccessibilityInsights.Extensions.AzureDevOps/Extensions.AzureDevOps.csproj
- src/AccessibilityInsights.Extensions.AzureDevOps/app.config
- src/AccessibilityInsights.Extensions.AzureDevOps/packages.config
- src/AccessibilityInsights.Extensions.AzureDevOpsTests/app.config
- src/AccessibilityInsights.Fakes.Prebuild/app.config
- src/MSI/Product.wxs
- src/UITests/app.config
The old version of Microsoft.IdentityModel.Clients.ActiveDirectory.dll has a reported security vulnerability that is fixed in version 5.2.0. The new version no longer includes Microsoft.IdentityModel.Clients.ActiveDirectory.Platform.dll, so the WXS file also needed to be updated.
Tested by exercising the ADO scenarios after installing from the locally built MSI:
- Disconnect from ADO
- Connect to ADO (as expected, login prompt was presented)
- Go through the ADO issue filing experience
- Exit the app (so the ADO data persists to the config)
- Start the app & go through the ADO issue filing experience (as expected, no login prompt was presented)
> Update Microsoft.IdentityModel.Clients.ActiveDirectory.dll to version 5.2.0

- src/AccessibilityInsights.Extensions.Telemetry/Extensions.Telemetry.csproj
- src/AccessibilityInsights.Extensions.Telemetry/packages.config
- src/AccessibilityInsights.Extensions.TelemetryTests/Extensions.TelemetryTests.csproj
- src/AccessibilityInsights.Extensions.TelemetryTests/app.config
- src/AccessibilityInsights.Extensions.TelemetryTests/packages.config
- src/MSI/Product.wxs
Use VS to update to ApplicationInsights 2.10.0. This was suggested by dependabot in #483, but this does it via VS. Validation that telemetry from the privately built MSI is flowing normally into the telemetry pipeline.
> Use VS to update to ApplicationInsights 2.10.0

- src/AccessibilityInsights.Extensions.AzureDevOps/Extensions.AzureDevOps.csproj
- src/AccessibilityInsights.Extensions.AzureDevOps/packages.config
Use VS to update to System.Runtime 4.3.1. Change suggested by dependabot in #484, done through Visual Studio. Validated by ensuring that ADO issue filing still works from a locally built MSI 
> Use VS to update to System.Runtime 4.3.1

- .github/CODEOWNERS
We've started updating all the accessibility insights repos to use a shared CODEOWNERS team, rather than maintaining separate ones per project. This brings accessibility-insights-windows up to date with this new policy.
> Generalize CODEOWNERS to use whole-team alias

- src/AccessibilityInsights.SharedUx/Controls/TestTabs/ColorContrast.xaml
- src/AccessibilityInsights.SharedUx/Controls/TestTabs/ColorContrast.xaml.cs
- src/AccessibilityInsights.SharedUx/Properties/Resources.Designer.cs
- src/AccessibilityInsights.SharedUx/Properties/Resources.resx
- src/AccessibilityInsights.SharedUx/ViewModels/ColorContrastViewModel.cs
This adds non-text element support (new for WCAG 2.1) to the color contrast analyzer, while also refactoring the dialog to the latest spec.
> Add WCAG 2.1 support to color contrast dialog

- build/prbuild.yml
This PR disables CG on PR builds. It will still run on all of our other builds.
> Don't run CG on PR builds

- src/AccessibilityInsights.Extensions.AzureDevOpsTests/Extensions.AzureDevOpsTests.csproj
- src/AccessibilityInsights.Extensions.AzureDevOpsTests/packages.config
- src/AccessibilityInsights.Extensions.GitHubAutoUpdateUnitTests/Extensions.GitHubAutoUpdateUnitTests.csproj
- src/AccessibilityInsights.Extensions.GitHubAutoUpdateUnitTests/packages.config
- src/AccessibilityInsights.Extensions.GitHubUnitTests/Extensions.GitHubUnitTests.csproj
- src/AccessibilityInsights.Extensions.GitHubUnitTests/packages.config
- src/AccessibilityInsights.Extensions.TelemetryTests/Extensions.TelemetryTests.csproj
- src/AccessibilityInsights.Extensions.TelemetryTests/packages.config
- src/AccessibilityInsights.ExtensionsTests/ExtensionsTests.csproj
- src/AccessibilityInsights.ExtensionsTests/packages.config
- src/AccessibilityInsights.SetupLibraryUnitTests/SetupLibraryUnitTests.csproj
- src/AccessibilityInsights.SetupLibraryUnitTests/packages.config
- src/AccessibilityInsights.SharedUxTests/SharedUxTests.csproj
- src/AccessibilityInsights.SharedUxTests/packages.config
- src/UITests/UITests.csproj
- src/UITests/packages.config
MSTest released 2.0.0 today. The breaking changes mentioned in [release notes](https://github.com/microsoft/testfx/releases) impact .NET Core and didn't seem to give us problems when testing.
> Use VS to update MSTest.TestFramework & MSTest.TestAdapter to version 2.0.0

- src/AccessibilityInsights.SharedUx/Controls/InspectTabsControl.xaml.cs
Currently, we set unused tabs in our right panel as `Visibility = Collapsed`. This works well visually, but screen readers still count the collapsed tabs when reading n of m information. This means that m is always 3, regardless of how many tabs are actually visible and usable. This PR fully removes the unused TabItems from the TabControl. Now, screen readers will announce the correct number for m. There should be no other perceivable impact.
- [-] Does this address an existing issue? If yes, Issue# - 
- [-] Attach any screenshots / GIF's that are applicable.
> Note: After the PR has been created, certain checks will be kicked off. All of these checks must pass …
> Fully remove unused right panel tabs

- src/AccessibilityInsights.SharedUx/Resources/Styles.xaml
- src/AccessibilityInsights/MainWindow.xaml
- src/AccessibilityInsights/Modes/ConfigurationModeControl.xaml
According to [the docs](https://docs.microsoft.com/en-us/dotnet/api/system.windows.automation.automationproperties.helptext?view=netframework-4.8), AutomationProperties.HelpText is generally the same text that is provided in the tooltip for the control. WPF takes this to heart and automatically sets a button's helptext to its tooltip value. Frustratingly, if the tooltip is set as a text-containing control such as a `Run`, the helptext is set to be that control's class name. For ai-win's icon buttons, the tooltip's content is roughly the same as the AutomationProperties.Name's content. To avoid repetitive screen reader output, we don't want to set the helptext with the tooltip at all (much less with the tooltip's class name). This PR sets dummy (blank space) values to the helptext in the …
> Set dummy HelpText value on some buttons

- src/AccessibilityInsights.Extensions.AzureDevOps/IssueTemplates/IssueColorContrast.json
- src/AccessibilityInsights.Extensions.AzureDevOps/IssueTemplates/IssueNoFailures.json
- src/AccessibilityInsights.Extensions.AzureDevOps/IssueTemplates/IssueSingleFailure.json
This PR adds the "Accessibility Insights for Windows" tag to any ADO bugs filed by our tool.
> Add "Accessibility Insights for Windows" tag to bugs filed by AI-Win

- src/AccessibilityInsights.CommonUxComponents/CommonUxComponents.csproj
- src/AccessibilityInsights.CommonUxComponents/Controls/CommonAutomationPeerCreator.cs
- src/AccessibilityInsights.CommonUxComponents/Controls/CustomControlOverridingAutomationPeer.cs
- src/AccessibilityInsights.CommonUxComponents/Controls/DualFabricIconControl.xaml.cs
- src/AccessibilityInsights.CommonUxComponents/Controls/FabricIconControl.xaml.cs
- src/AccessibilityInsights.SharedUx/Properties/Resources.Designer.cs
- src/AccessibilityInsights.SharedUx/Properties/Resources.resx
This change updates the UIA properties of our fabric icons across the app. After this change the icons should appear in the control view, have the control type "Image", the localized control type "icon", and have no children. Because the control type is now "image", the icons will show up in scan mode. This also means that a screen reader will say "search icon" instead of just "search" - beforehand, the text child of the icon (implementation detail) would show up in scan mode but not the icon itself. This PR improves the representation so that the text child is not shown and instead the user is presented with an icon.
> Move fabric icons into control view

- src/AccessibilityInsights.SharedUx/Controls/TestTabs/ColorContrast.xaml
- src/AccessibilityInsights.SharedUx/Controls/TestTabs/ColorContrast.xaml.cs
Currently, we visually hide the confidence text in CCA mode when auto-detect is disabled. However, the text remains in the UI Automation tree. This PR updates that behavior to fully remove the confidence text, both visually and from the UIA tree. Some XAML cleanup is done while in the neighborhood. There should be no visual impact from this PR.
- [-] Does this address an existing issue? If yes, Issue# - 
- [-] Attach any screenshots / GIF's that are applicable.
> Fully remove CCA confidence level text when not applicable

- src/AccessibilityInsights.SharedUx/Controls/TestTabs/ColorContrast.xaml
The help text for the control was accidentally set as the name, making the text "sample small bold text". The tester was concerned the screen reader user would not hear the text as it appears on screen. Now the name is "the quick brown fox" and the help text is "sample small bold text".
> Fix trusted tester Bug 1584490

- src/AccessibilityInsights.SharedUx/Telemetry/TelemetryProperty.cs
- src/AccessibilityInsights.Win32/Win32Helper.cs
- src/AccessibilityInsights/Misc/TelemetryEventFactory.cs
Add a telemetry property to allow us to better understand what .NET Framework version is installed. This is to enable us to better evaluate how users will be impacted by potential future adoptions of newer versions of the .NET framework.
The lack of unit tests for the new code is intentional. We don't want to add any more Fake-based tests, and there's little return in testing the behavior of .NET's Registry.GetValue method. Testing was ensuring that the return value is correct for my dev machine, as well as confirming that `GetInstalledDotNetFrameworkVersion` returns null if the value doesn't exist in the registry.
> Add telemetry of installed .NET Framework version

- src/AccessibilityInsights/App.config
- src/UITests/LiveMode.cs
- src/UITests/LoadTestFile.cs
- src/UITests/UILibrary/TestMode.cs
This PR opts into accessibility features as described by these [docs](https://docs.microsoft.com/en-us/dotnet/framework/whats-new/whats-new-in-accessibility#accessibility-switches):
> You can configure your app to opt into accessibility features if it targets .NET Framework 4.7 or an earlier version but is running on .NET Framework 4.7.1 or later.
This results in some of the following improvements if the app is running on a machine with .NET framework 4.8 installed:
- > In .NET Framework 4.7.2 and earlier versions, tooltips display only when the user hovers the mouse cursor over a control. In .NET Framework 4.8, tooltips also display on keyboard focus, as well as via a keyboard shortcut.
- > Windows 10 introduced two new UIAutomation properties, SizeOfSet and PositionInSet, which are used …
> Opt into accessibility features available in .NET framework 4.8

- src/AccessibilityInsights.SharedUx/SharedUx.csproj
- src/AccessibilityInsights.SharedUx/packages.config
- src/AccessibilityInsights.SharedUxTests/SharedUxTests.csproj
- src/AccessibilityInsights.SharedUxTests/app.config
- src/AccessibilityInsights.SharedUxTests/packages.config
- src/AccessibilityInsights/AccessibilityInsights.csproj
- src/AccessibilityInsights/packages.config
- src/UITests/UITests.csproj
- src/UITests/packages.config
Update to Axe.Windows 0.3.4. This picks up the correction to the false positive that was introduced in Axe.Windows 0.3.3
> Update to Axe.Windows 0.3.4

- src/AccessibilityInsights.SharedUx/Controls/TestTabs/ColorContrast.xaml
- src/AccessibilityInsights.SharedUx/Properties/Resources.Designer.cs
- src/AccessibilityInsights.SharedUx/Properties/Resources.resx
This PR picks up some stuff that was missed in PR #525. Description copied from there:
The help text for the control was accidentally set as the name, making the text "sample small bold text". The tester was concerned the screen reader user would not hear the text as it appears on screen. Now the name is "the quick brown fox" and the help text is "sample small bold text".
A resource name was also updated while in the neighborhood.
> Change to HelpText what was mistakenly set to AutomationName

- src/AccessibilityInsights.SharedUx/Controls/TestTabs/AutomatedChecksControl.xaml
- src/AccessibilityInsights.SharedUx/Properties/Resources.Designer.cs
- src/AccessibilityInsights.SharedUx/Properties/Resources.resx
While looking into 1583836, we found that some of the content from the automated checks component was obsolete; it was permanently collapsed, rather than being removed. This PR removes the obsolete content completely, and cleans up the containing grid layout accordingly. Specifically:
* Removes the always-collapsed `<Rectangle>` and `<Grid>` that used to show an obsolete notification banner
* Removes the corresponding resource strings
* The original used a 2-column grid where the only content of the first column was an empty 16px wide rectangle; replaced the first column and the spacer rectangle with a margin on the grid.
* Removed an unnecessary `<RowDefinition>` from the grid and fixed up the `Grid.Row` references in the children that were pointing to non-existent rows.
This is intended …
> remove obsolete bits of AutomatedChecksControl.xaml

- src/AccessibilityInsights.SharedUx/Controls/HierarchyControl.xaml
- src/AccessibilityInsights.SharedUx/Controls/HierarchyControl.xaml.cs
- src/AccessibilityInsights.SharedUx/Properties/Resources.Designer.cs
- src/AccessibilityInsights.SharedUx/Properties/Resources.resx
The SizeOfSet and PositionInSet properties of the tree view menu items were incorrect (2 of 7, 3 of 7, etc) for the following reasons:
- We used a non-actionable menu item as a visual header
- Separators are included in the SizeOfSet count for menu items
- Hidden menu items are included in the SizeOfSet count for menu items
We are unable to override the SizeOfSet or PositionInSet properties unless we explicitly target .NET framework 4.8. In the meantime, this PR restructures the menu to improve accessibility. Now the SizeOfSet and PositionInSet properties are as expected and the visual-only header and separator have gone away.
**before**
**after**
-- It looks like both in production and this PR, we flag popups created by context menus because they have no name. We may want to look into …
> Improve n-of-m numbering by restructuring tree view walker menu

- src/AccessibilityInsights.Extensions.AzureDevOps/ConfigurationControl.xaml
- src/AccessibilityInsights.SharedUx/Controls/EventConfigurationControl.xaml
- src/AccessibilityInsights.SharedUx/Controls/EventRecordControl.xaml
- src/AccessibilityInsights.SharedUx/Controls/HierarchyControl.xaml
- src/AccessibilityInsights.SharedUx/Controls/PropertyInfoControl.xaml
- src/AccessibilityInsights.SharedUx/Controls/SettingsTabs/ApplicationSettingsControl.xaml
- src/AccessibilityInsights.SharedUx/Controls/TestTabs/AutomatedChecksControl.xaml
- src/AccessibilityInsights.SharedUx/Controls/WhatsNew/WhatsNewControl.xaml
- src/AccessibilityInsights.SharedUx/Resources/Styles.xaml
- src/AccessibilityInsights/Modes/LiveModeControl.xaml
- src/AccessibilityInsights/Modes/TestModeControl.xaml
In this PR, decorative images are moved out of the UIA control view. This will prevent these images from showing up in Narrator's scan mode. For our purposes, a decorative image adds no additional information than adjacent text.
> Move decorative images out of control view

- tools/scripts/ValidateReleaseInfo.ps1
Update ValidateReleaseInfo.ps1 with an environment variable to control the release of Octokit to use when validating the releases. This variable can be updated by changing the build definition.
This is the code-side fix for #545. The other changes are all in build definitions (already in place and validated)
> Add Octokit version as an overridable variable

- src/AccessibilityInsights.CommonUxComponents/Controls/CustomControlOverridingAutomationPeer.cs
This updates our `CustomControlOverridingAutomationPeer`'s default behavior to omit controls that are not visible from the content and control planes, similar to the new .NET 4.8 default behavior we recently opted into that does the same thing in the [default `UIElementAutomationPeer` implementation](https://referencesource.microsoft.com/#PresentationCore/Core/CSharp/System/Windows/Automation/Peers/UIElementAutomationPeer.cs,399).
This improves narrator scan mode behavior in a few cases where it was previously reading "invisible" icons; for example, in a "automated checks test results" page showing the "congratulations, no failures" message, this change prevents narrator's scan mode from incorrectly reading the "alert" icon that is only visible when there are failures present.
- [n/a, no …
> hide non-visible controls from control/content planes (like .NET 4.8)

- src/AccessibilityInsights.SharedUx/Controls/EventRecordControl.xaml
- src/AccessibilityInsights.SharedUx/Properties/Resources.Designer.cs
- src/AccessibilityInsights.SharedUx/Properties/Resources.resx
As in #532 - the current structure of the context menu for event recording is not accessible:
- the separator is included in the n-of-m count
- the disabled header menu item is not easily accessible via screen readers
- the n-of-m counts are inaccurate because they include the non-focusable header
This PR introduces a submenu so that the n-of-m counts are correct and the header is more accessible.
> Note: After the PR has been created, certain checks will be kicked off. All of these checks must pass before a merge. 
Screenshot:
> Improve n-of-m numbering by restructuring event config settings menu 

- src/AccessibilityInsights.SharedUx/Controls/ScannerResultControl.xaml.cs
- src/AccessibilityInsights.SharedUx/Utilities/HelperMethods.cs
- src/AccessibilityInsights/MainWindow.xaml.cs
Make the "File Issue" column width responsive to the configured font size.
> Issue #544: Don't cut off "File Issue" text in standard font size

- src/AccessibilityInsights.SharedUx/Dialogs/HotkeyGrabDialog.xaml
- src/AccessibilityInsights.SharedUx/Dialogs/HotkeyGrabDialog.xaml.cs
We were seeing a few accessibility/usability issues with the set hotkey dialog. This PR makes two key changes:
1. A TextBox is added to display the new hotkey selection. What is displayed does not change. The key purpose of the TextBox is to provide an actual focusable element on the window, which there previously was not.
2. The Tab key can no longer be added to a shortcut.
Minor visual impact. We could make it look the same, but then the TextBox would not look like a TextBox, which seems bad to me.
Before:
After:
> Update hotkey dialog to have TextBox + block saving tab key

- src/AccessibilityInsights.SharedUx/Dialogs/HotkeyGrabDialog.xaml
- src/AccessibilityInsights.SharedUx/Dialogs/HotkeyGrabDialog.xaml.cs
Picking up two minor changes pointed out by @dbjorge but missed in #552. Two event handler methods were switched from a window to a textbox, but their names still referenced the window. This PR renames them accordingly. It also prevents the Cut and Delete commands from being executed on the textbox, since it is not meant to be directly edited.
- [-] Does this address an existing issue? If yes, Issue# - 
- [-] Attach any screenshots / GIF's that are applicable.
> Update TextBox event handling

- src/AccessibilityInsights.SharedUx/KeyboardHelpers/HotKey.cs
- src/AccessibilityInsights/MainWindowHelpers/Initialize.cs
Currently, hotkeys attempt to function at all times and states in ai-win. This includes while the user is trying to change their hotkeys. This PR stops hotkeys from acting when the settings pane is open to avoid potentially confusing or difficult scenarios. We currently only have one hotkey which could possibly be useful in settings, the show/hide window hotkey. In my opinion, the purpose of this hotkey relates to actually testing and inspecting apps, not changing one's settings. I feel comfortable disabling it here. If anyone disagrees with that (or the change as a whole), feel free to voice those concerns.
- [-] Does this address an existing issue? If yes, Issue# - 
- [-] Run the production version of Accessibility Insights for Windows against a version with …
> Stop hotkeys from acting while settings pane is open

- src/AccessibilityInsights.Extensions.GitHub/Properties/Resources.Designer.cs
- src/AccessibilityInsights.Extensions.GitHub/Properties/Resources.resx
Our GitHub URL placeholder was missing a colon. This PR fixes the typo
> Fix typo in github placeholder

- Channels/Insider/release_info.json
- Channels/Insider/release_notes.md
- build/prbuild-Control.yml
This creates an insider release for v1.1.0990.01 (likely canary from the morning of the 18th).
See the updated release notes here: https://github.com/microsoft/accessibility-insights-windows/blob/67c726e791838a7d13954916180e2b96bc84c878/Channels/Insider/release_notes.md
This release contains primarily accessibility fixes. We'd like to be able to push these to prod alongside the existing WCAG 2.1 color contrast changes in flight.
> Create insider release for v1.1.0990.01

- src/AccessibilityInsights.SharedUx/Controls/SettingsTabs/AboutTabControl.xaml
- src/AccessibilityInsights.SharedUx/Misc/VersionTools.cs
- src/AccessibilityInsights.SharedUx/Properties/Resources.Designer.cs
- src/AccessibilityInsights.SharedUx/Properties/Resources.resx
- src/AccessibilityInsights.SharedUx/ViewModels/AboutTabViewModel.cs
This PR adds the text, "Built with Axe-Windows v\<axe version>" to the about tab. It is another step towards achieving the mocked state in [Feature Request] What's new content hasn't been updated since initial release #299.
> Add Axe-Windows version to About tab

- src/AccessibilityInsights.SharedUx/Settings/ConfigurationManager.cs
Layout.json is being read from the config files location, but is being written to the data files location. As a result, persisted changes are not honored on the next boot.
> Layout.json is being saved in the wrong location. Fix it.

- src/AccessibilityInsights.Fakes.Prebuild/app.config
- src/AccessibilityInsights.SharedUx/SharedUx.csproj
- src/AccessibilityInsights.SharedUx/app.config
- src/AccessibilityInsights.SharedUx/packages.config
- src/AccessibilityInsights.SharedUxTests/SharedUxTests.csproj
- src/AccessibilityInsights.SharedUxTests/app.config
- src/AccessibilityInsights.SharedUxTests/packages.config
- src/AccessibilityInsights/AccessibilityInsights.csproj
- src/AccessibilityInsights/App.config
- src/AccessibilityInsights/packages.config
- src/UITests/UITests.csproj
- src/UITests/app.config
- src/UITests/packages.config
#566 is the Dependabot-driven update to Microsoft.Win32.Registry version 4.6.0. This does it through Visual Studio. It auto-updated System.Security.Principal.Windows and System.Security.AccessControl to version 4.6.0, as well.
> Use VS to update Microsoft.Win32.Registry to version 4.6.0

- src/AccessibilityInsights.Extensions.GitHubAutoUpdateUnitTests/Extensions.GitHubAutoUpdateUnitTests.csproj
- src/AccessibilityInsights.Extensions.GitHubAutoUpdateUnitTests/app.config
- src/AccessibilityInsights.Extensions.GitHubAutoUpdateUnitTests/packages.config
- src/AccessibilityInsights.Extensions.GitHubUnitTests/Extensions.GitHubUnitTests.csproj
- src/AccessibilityInsights.Extensions.GitHubUnitTests/app.config
- src/AccessibilityInsights.Extensions.GitHubUnitTests/packages.config
- src/AccessibilityInsights.SharedUxTests/SharedUxTests.csproj
- src/AccessibilityInsights.SharedUxTests/app.config
- src/AccessibilityInsights.SharedUxTests/packages.config
VS-driven version of #571. Touches only unit test code, all of which pass 
> Use VS to update System.Runtime.CompilerServices.Unsafe to 4.6.0

- src/AccessibilityInsights.SharedUx/Controls/TestTabs/TabStopControl.xaml.cs
Per issue #543- Text on the automated checks overlaps with text from tabstops, we were seeing some unfortunate drawing behavior in our test mode tab control. I was able to narrow down the offending code to our call to hide the tab stop highlighter. I was able to alleviate the issue by putting that highlighter call in a `Dispatcher.BeginInvoke` call. I did not go deeper into the cause, considering that it is outside of our control how WPF draws the tab control.
Before:
After:
> Hide tab stop highlighter asyncronously on dispatcher to fix rendering

- src/AccessibilityInsights.SharedUx/Controls/CustomControls/CustomExpander.cs
- src/AccessibilityInsights.SharedUx/Controls/TestTabs/AutomatedChecksControl.xaml
- src/AccessibilityInsights.SharedUx/Controls/TestTabs/AutomatedChecksControl.xaml.cs
- src/AccessibilityInsights.SharedUx/SharedUx.csproj
A recent change to enable .NET 4.8 accessibility features had an unintended side effect of breaking our Automated Checks `ListView`'s screen reader user behavior. Specifically, once a group item had been expanded at least once, screen readers would no longer speak upon that item receiving keyboard focus. Per @karanbirsingh's investigation, this appeared to be caused by a change to the `GroupItemAutomationPeer` which made its `HasKeyboardFocus` UIA property set based on its child expander's `HasKeyboardFocus` property. Because of our customization, that expander never receives keyboard focus. This PR addresses the problem by overriding the child expander's `AutomationPeer` and setting its `HasKeyboardFocus` value based on its parent GroupItem's `IsFocused` value. This does not impact …
> Fix screen reader behavior in AutomatedChecks ListView

- docs/SetUpDevEnv.md
- src/AccessibilityInsights.SetupLibrary/SetupLibrary.csproj
- src/AccessibilityInsights.SetupLibrary/packages.config
- src/AccessibilityInsights.VersionSwitcher/VersionSwitcher.csproj
- src/AccessibilityInsights.VersionSwitcher/packages.config
- src/AccessibilityInsights/AccessibilityInsights.csproj
- src/AccessibilityInsights/packages.config
- src/MSI/MSI.wixproj
- src/MSI/packages.config
Update to WiX toolset 3.11.2. This was "mostly" automatic, but the 2 references in SetupLibrary and VersionSwitcher required manual tweaking of the version. This is because the WiX package doesn't automatically include references to its constituent assemblies. Replaces dependabot-authored #591 
Also updated the docs for the environment, since the WiX packages get installed automatically via NuGet and only the Visual Studio extension actually requires a separate installation.
**Note**: According to https://github.com/wixtoolset/wix3/releases/tag/wix3112rtm, this update is probably not really necessary for us, so I have no objections to skipping this update completely if that's the consensus.
Tested by installing the MSI, then exercising the version switcher by changing to the Insider …
> Update to WiX toolset 3.11.2. This was "mostly" automatic

- build/ui-test-job.yml
We've been seeing some UITests failures that seem to be timeout-related. We'll try for a more permanent fix, but this will allow each test 3 attempts to succeed. Deterministic failures will still cause the test task to fail (and break the build)
> Enable retry when running UITests

- src/AccessibilityInsights.Extensions.GitHub/ConfigurationModelControl.xaml
- src/AccessibilityInsights.SharedUx/Controls/PropertyInfoControl.xaml
- src/AccessibilityInsights.SharedUx/Resources/Styles.xaml
Use gray text for the GitHub issue filing placeholder text. 
There are 2 other places where PlaceholderTextBox is used. One is the Search control in the Hierarchy view, and the other is the Search control in the Details view. These controls retain their existing colors, since they render on a different background color. The changes take a somewhat naive approach, since it should be theoretically possible to have just 1 style to handle multiple colors, but my attempts to do were unsuccessful. Maybe John can suggest a better style option later on.
Screenshot: Key difference to observe is between the leftmost and rightmost portions of the top row of the screenshot. All others are intentionally unchanged.
> Note: After the PR has been created, certain checks will be kicked off. All of these …
> Use gray text for the GitHub issue filing placeholder text

- src/AccessibilityInsights.Extensions.AzureDevOps/ConfigurationControl.xaml
Improve color contrast on AzureBoards link placeholder text. The existing code uses a hardcoded value of SlateGray (RGB value of 708090), which is an insufficient color contrast on the default (non-HC) theme, and that fails to become high contrast when HC is enabled. This change replaces the hardcoded color with a color that does a better job at contrast (6E6E6E in non-HC mode, 000000 in HC White, and FFFFFF in other HC modes)
Screenshot:
> Improve color contrast on AzureBoards link placeholder text

- build/signedbuild.yml
Restrict the signing validation to just the SignedRelease job. It still has some failures, but at least they're only in the job where they should matter.
Build run: https://dev.azure.com/mseng/1ES/_build/results?buildId=10680701&view=results
> Disable injected code signing on unsigned jobs

- build/ui-test-job.yml
In a recent build, 3 of our 5 UITests failed, but no UITests were rerun. This was surprising since the retry flag was set to true. After digging into the docs at https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/vstest?view=azure-devops, we learned that the default behavior for rerunning is to disable rerun if the failure rate exceeds 30% of the tests. We had a 60% failure rate (3 of 5), so no rerun occurred. That's not what we wanted.
This changes the rerun failure rate to be based on the count of failures (not the percentage), and it sets the "don't rerun any tests" threshold to a value larger than our count of tests. The intent is that even if 100% of our UITests failed on the first try, we still want to rerun the failed tests.
Validation build has been queued: …
> Make UITests rerun even in case of 100% failure

- src/AccessibilityInsights/MainWindow.xaml.cs
- src/AccessibilityInsights/MainWindowHelpers/Initialize.cs
To address #608- [BUG] Opening file by file association is broken if welcome dialog is shown, this PR stops showing the startup/welcome screen when loading a file directly on launch. This makes more sense to me than our old behavior (which I would describe as unintentional), which was that the welcome screen would show over the loaded data. If others disagree, we can revert to that behavior instead.
> Don't show welcome screen when opening loaded file

- build/settings.targets
In #536- Fix signed build, I claimed to fix our signed build. That may have been true for digital signing, but the PR happened to break strong name signing. The cause: [the conditional here](https://github.com/microsoft/accessibility-insights-windows/blob/3d46005fc1c46861b0975bd5a4594592275a9299/build/settings.targets#L10) wasn't updated to check for the new SignedRelease configuration. A signed build ran without errors related to strong name keys. 
> Fix settings.targets to include keys on SignedRelease

- build/delaysign.targets
- build/settings.targets
- build/signedbuild.yml
- build/ui-test-job.yml
- src/AccessibilityInsights.sln
PRs #536, #620, and #621 failed to get us digitally and strong name signed. Hopefully this PR will. Here, we stop gating signing based on the Configuration and leave it entirely up to the build variables. We also tweak the variables set in signedbuild.yml to make signing opt-in instead of opt-out. A signed build ran and produced a digitally and strong name signed artifact.
> Gate signing only with build variables

- src/AccessibilityInsights.CommonUxComponents/CommonUxComponents.csproj
- src/AccessibilityInsights.CommonUxComponents/packages.config
- src/AccessibilityInsights.Extensions.AzureDevOps/Extensions.AzureDevOps.csproj
- src/AccessibilityInsights.Extensions.AzureDevOps/packages.config
- src/AccessibilityInsights.Extensions.GitHub/Extensions.GitHub.csproj
- src/AccessibilityInsights.Extensions.GitHub/packages.config
- src/AccessibilityInsights.Extensions.GitHubAutoUpdate/Extensions.GitHubAutoUpdate.csproj
- src/AccessibilityInsights.Extensions.GitHubAutoUpdate/packages.config
- src/AccessibilityInsights.Extensions.Telemetry/Extensions.Telemetry.csproj
- src/AccessibilityInsights.Extensions.Telemetry/packages.config
- src/AccessibilityInsights.Extensions/Extensions.csproj
- src/AccessibilityInsights.Extensions/packages.config
- src/AccessibilityInsights.SetupLibrary/SetupLibrary.csproj
- src/AccessibilityInsights.SetupLibrary/packages.config
- src/AccessibilityInsights.SharedUx/SharedUx.csproj
- src/AccessibilityInsights.SharedUx/packages.config
- src/AccessibilityInsights.VersionSwitcher/VersionSwitcher.csproj
- src/AccessibilityInsights.VersionSwitcher/packages.config
- src/AccessibilityInsights.Win32/Win32.csproj
- src/AccessibilityInsights.Win32/packages.config
- src/AccessibilityInsights/AccessibilityInsights.csproj
- src/AccessibilityInsights/packages.config
Done using VS (not by hand).
- Bump Microsoft.CodeAnalysis.VersionCheckAnalyzer from 2.9.6 to 2.9.7
- Bump Microsoft.NetCore.Analyzers from 2.9.6 to 2.9.7
- Bump Microsoft.CodeAnalysis.FxCopAnalyzers from 2.9.6 to 2.9.7
- Bump Microsoft.CodeQuality.Analyzers from 2.9.6 to 2.9.7
- Bump Microsoft.NetFramework.Analyzers from 2.9.6 to 2.9.7
> Bump analyzers from 2.9.6 to 2.9.7

- src/AccessibilityInsights.SharedUx/Dialogs/GlobalEyedropperWindow.xaml.cs
- src/AccessibilityInsights.SharedUx/Highlighting/Win32SnapshotButton.cs
- src/AccessibilityInsights.SharedUx/Utilities/ExtensionMethods.cs
- src/AccessibilityInsights.SharedUx/Utilities/HelperMethods.cs
- src/AccessibilityInsights.Win32/NativeMethods.cs
- src/AccessibilityInsights.Win32/Win32Enums.cs
- src/AccessibilityInsights.Win32/Win32Helper.cs
We identified some Axe.Windows methods that are used only in AIWin. We're adding these methods to AIWin and removing them from Axe.Windows. This is the complement of https://github.com/microsoft/axe-windows/pull/214
> Add private versions of Axe.Windows methods that aren't used by Axe.Windows

- src/AccessibilityInsights.Extensions.AzureDevOps/Extensions.AzureDevOps.csproj
- src/AccessibilityInsights.Extensions.AzureDevOps/packages.config
- src/AccessibilityInsights.Extensions.GitHubAutoUpdate/Extensions.GitHubAutoUpdate.csproj
- src/AccessibilityInsights.Extensions.GitHubAutoUpdate/packages.config
- src/AccessibilityInsights.Extensions.GitHubAutoUpdateUnitTests/Extensions.GitHubAutoUpdateUnitTests.csproj
- src/AccessibilityInsights.Extensions.GitHubAutoUpdateUnitTests/packages.config
- src/AccessibilityInsights.Fakes.Prebuild/Fakes.Prebuild.csproj
- src/AccessibilityInsights.Fakes.Prebuild/packages.config
- src/AccessibilityInsights.SetupLibrary/SetupLibrary.csproj
- src/AccessibilityInsights.SetupLibrary/packages.config
- src/AccessibilityInsights.SetupLibraryUnitTests/SetupLibraryUnitTests.csproj
- src/AccessibilityInsights.SetupLibraryUnitTests/packages.config
- src/AccessibilityInsights.SharedUx/SharedUx.csproj
- src/AccessibilityInsights.SharedUx/packages.config
- src/AccessibilityInsights.SharedUxTests/SharedUxTests.csproj
- src/AccessibilityInsights.SharedUxTests/packages.config
- src/AccessibilityInsights/AccessibilityInsights.csproj
- src/AccessibilityInsights/packages.config
- src/UITests/UITests.csproj
- src/UITests/packages.config
Bump Newtonsoft.Json.dll from 12.0.2 to 12.0.3. This is the VS-driven version of #631 
> Bump Newtonsoft.Json.dll from 12.0.2 to 12.0.3

- src/AccessibilityInsights.SharedUx/SharedUx.csproj
- src/AccessibilityInsights.SharedUx/packages.config
- src/AccessibilityInsights.SharedUxTests/SharedUxTests.csproj
- src/AccessibilityInsights.SharedUxTests/packages.config
- src/AccessibilityInsights/AccessibilityInsights.csproj
- src/AccessibilityInsights/packages.config
- src/UITests/UITests.csproj
- src/UITests/packages.config
Bump System.Drawing.Common from 4.6.0 to 4.6.1 (changed via VS). This supersedes #635 
> Bump System.Drawing.Common from 4.6.0 to 4.6.1 (changed via VS)

- src/AccessibilityInsights.CommonUxComponents/CommonUxComponents.csproj
- src/AccessibilityInsights.CommonUxComponents/packages.config
- src/AccessibilityInsights.Extensions.AzureDevOps/Extensions.AzureDevOps.csproj
- src/AccessibilityInsights.Extensions.AzureDevOps/packages.config
- src/AccessibilityInsights.Extensions.GitHub/Extensions.GitHub.csproj
- src/AccessibilityInsights.Extensions.GitHub/packages.config
- src/AccessibilityInsights.Extensions.GitHubAutoUpdate/Extensions.GitHubAutoUpdate.csproj
- src/AccessibilityInsights.Extensions.GitHubAutoUpdate/packages.config
- src/AccessibilityInsights.Extensions.Telemetry/Extensions.Telemetry.csproj
- src/AccessibilityInsights.Extensions.Telemetry/packages.config
- src/AccessibilityInsights.Extensions/Extensions.csproj
- src/AccessibilityInsights.Extensions/packages.config
- src/AccessibilityInsights.SetupLibrary/SetupLibrary.csproj
- src/AccessibilityInsights.SetupLibrary/packages.config
- src/AccessibilityInsights.SharedUx/SharedUx.csproj
- src/AccessibilityInsights.SharedUx/packages.config
- src/AccessibilityInsights.VersionSwitcher/VersionSwitcher.csproj
- src/AccessibilityInsights.VersionSwitcher/packages.config
- src/AccessibilityInsights.Win32/Win32.csproj
- src/AccessibilityInsights.Win32/packages.config
- src/AccessibilityInsights/AccessibilityInsights.csproj
- src/AccessibilityInsights/packages.config
Bump Roslyn Analyzers from 2.9.7 to 2.9.8 (via VS). This supersedes #646, #647, #648, #649, and #650.
> Bump analyzers from 2.9.7 to 2.9.8 (done via VS)

- src/AccessibilityInsights.Extensions.AzureDevOps/ConfigurationControl.xaml
Disable the connect button if no text is entered into the edit control
> Disable the connect button if no text is entered into the edit control

- src/AccessibilityInsights.Extensions.AzureDevOps/ConfigurationControl.xaml
- src/AccessibilityInsights.Extensions.AzureDevOps/Models/ConfigurationViewModel.cs
Fix issue #644: The empty user into controls are showing up for screen readers even when they contain no data. This change simply adds visibility properties to collapse each element if no data is available. Ran AIWin on the control with no validated user and it comes out clean.
Having a property for each control might be overkill, since all three properties should be populated together, but I opted for an approach that could handle any combination of properties from the server.
> Collapse User Info controls when we have no data

- src/AccessibilityInsights.SharedUx/Resources/Styles.xaml
This PR updates the margin/padding link in the btnBlue style to be consistent with btnGrey. Without this change, the padding value is not propagated to the templated ContentPresenter. I looked at other usages of btnBlue and none seemed inadvertently affected (none use padding).
Before:
After:
> Fix 'Connect Azure Boards account' padding

- src/AccessibilityInsights.Fakes.Prebuild/app.config
- src/AccessibilityInsights.SharedUx/SharedUx.csproj
- src/AccessibilityInsights.SharedUx/app.config
- src/AccessibilityInsights.SharedUx/packages.config
- src/AccessibilityInsights.SharedUxTests/SharedUxTests.csproj
- src/AccessibilityInsights.SharedUxTests/app.config
- src/AccessibilityInsights.SharedUxTests/packages.config
- src/AccessibilityInsights/AccessibilityInsights.csproj
- src/AccessibilityInsights/App.config
- src/AccessibilityInsights/packages.config
- src/UITests/UITests.csproj
- src/UITests/app.config
- src/UITests/packages.config
This is the VS-driven version of #658, and supersedes #658, #656, and #662
Bump Microsoft.Win32.Registry from 4.6.0 to 4.7.0 (using VS).
VS also bumped System.Security.AccessControl and System.Security.Principal.Windows to 4.7.0
> Bump Microsoft.Win32.Registry from 4.6.0 to 4.7.0 (using VS)

- src/AccessibilityInsights.Extensions.GitHubAutoUpdateUnitTests/Extensions.GitHubAutoUpdateUnitTests.csproj
- src/AccessibilityInsights.Extensions.GitHubAutoUpdateUnitTests/app.config
- src/AccessibilityInsights.Extensions.GitHubAutoUpdateUnitTests/packages.config
- src/AccessibilityInsights.Extensions.GitHubUnitTests/Extensions.GitHubUnitTests.csproj
- src/AccessibilityInsights.Extensions.GitHubUnitTests/app.config
- src/AccessibilityInsights.Extensions.GitHubUnitTests/packages.config
- src/AccessibilityInsights.SharedUxTests/SharedUxTests.csproj
- src/AccessibilityInsights.SharedUxTests/app.config
- src/AccessibilityInsights.SharedUxTests/packages.config
This is the VS-driven version of #660
> Bump System.Runtime.CompilerServices.Unsafe from 4.6.0 to 4.7.0 (using VS)

- src/AccessibilityInsights.SharedUx/Dialogs/EyedropperWindow.xaml.cs
- src/AccessibilityInsights.SharedUx/Highlighting/ImageHighlighter.cs
- src/AccessibilityInsights.SharedUx/Highlighting/OverlayHighlighter.cs
- src/AccessibilityInsights.SharedUx/Utilities/HelperMethods.cs
PR #630 moved methods from Axe.Windows into AIWin, but missed a few places where the Axe.Windows versions are still being used. Since these methods don't exist in Axe.Windows 0.3.5, we need to correct these usages before we can use upgrade to Axe.Windows 0.3.5
> Call AIWin versions of methods that were removed from Axe.Windows

- src/AccessibilityInsights.SharedUx/Highlighting/OverlayHighlighter.cs
To deal with an ambiguity, PR #667 temporarily replaced calling an extension method with calling the fully-qualified method. This was needed only as we moved between Axe.Windows 0.3.4 and Axe.Windows 0.3.5. Now that we've moved to Axe.Windows 0.3.5, we can revert to calling the method as an extension method. This is all syntactic sugar, with no impact to the generated code.
> Remove ugly code that was needed only temporarily

- src/AccessibilityInsights/AccessibilityInsights.csproj
- src/AccessibilityInsights/packages.config
Manually making a change that dependabot is unable to make on older project types.
> Bump CommandLineParser from 2.6.0 to 2.7.82

- src/AccessibilityInsights.SharedUx/Resources/HighContrast/Brushes.xaml
A recent issue (#675) pointed out that a certain control in the color contrast mode had poor color contrast while using high contrast themes. This PR addresses this issue by removing the specific color we set for that control's background in HC modes. This allows the background to revert to the control's default, which offers proper contrast.
Before and after (before on the left):
Normal (no change):
HC Black:
HC White:
> Fix color contrast mode background color for high contrast themes

- src/AccessibilityInsights.SharedUx/Highlighting/TextRangeHilighter.cs
- src/AccessibilityInsights.SharedUx/Utilities/ExtensionMethods.cs
The IsVisibleLocation extension method in Axe.Windows is used only by AIWin, so we want to migrate it into AIWin. This change adds it to AIWin. A separate change (as part of the port) will remove it from Axe.Windows.
> Port IsVisibleLocation from Axe.Windows to AIWin

- src/AccessibilityInsights.SharedUx/Controls/TestTabs/TabStopControl.xaml
- src/AccessibilityInsights.SharedUx/Properties/Resources.Designer.cs
- src/AccessibilityInsights.SharedUx/Properties/Resources.resx
Currently, for the (i) icon link, the AutomationName is "How to test" and the ToolTip is "Tab Stops". This PR updates both of those to be "Guidance", in line with AI-Web.
> Change AutomationName and ToolTip for tabstops (i) icon link

- src/AccessibilityInsights.SharedUx/Resources/HighContrast/Brushes.xaml
- src/AccessibilityInsights.SharedUx/Resources/Styles.xaml
AI-Win has several buttons styled to look like links. In high contrast modes, however, these revert back to the default text color. This makes them indistinguishable from non-interactive text. This PR updates those link-buttons to use the system link color while in high contrast modes.
Before and afters (befores on top; note the "Live Inspect" and "View results in the UI Automation tree" text colors):
HC White:
HC Black:
> Use system color for link-style buttons in HC modes

- src/AccessibilityInsights.SharedUx/ActionViews/ReturnA11yElementsView.xaml.cs
- src/AccessibilityInsights.SharedUx/Dialogs/EyedropperWindow.xaml.cs
- src/AccessibilityInsights.SharedUx/Highlighting/OverlayHighlighter.cs
There are a few places in the code that explicitly catch `NullReferenceException`, presumably based on observation of previous behavior that we can't directly control. Null parameter checks were recently added to several Axe.Windows methods, meaning that they now throw `ArgumentNullException` instead of `NullReferenceException`. The underlying fact that the data is null hasn't changed, but the changed Exception type is leaving the `ArgumentNullException` uncaught, and the app crashes as a result.
This change identifies all places where we silently ignore `NullReferenceException` and treats `ArgumentNullException` in exactly the same way. It's not pretty, but it's intended to prevent the crash in the same way that we used to prevent it. We've begun conversations on options of notifiying …
> Eat ArgumentNullException where we already eat NullReferenceException

- build/signedbuild.yml
CredScan V1 is on the road to deprecation and we're starting to receive warnings during build. The recommended change is to use CredScan V2. As outlined in https://www.1eswiki.com/wiki/CredScan_Azure_DevOps_Build_Task, this involves setting the toolMajorVerion input to V2. Validation build is at https://dev.azure.com/mseng/1ES/_build/results?buildId=11457821&view=results. Compare the CredScan results (in the ComplianceDebug job) to previous results, and you'll note that we're no longer getting the warning. This is a tool-only change that doesn't touch any code.
> Update CredScan to V2

- src/AccessibilityInsights/Modes/ConfigurationModeControl.xaml
Currently, the order of elements on our settings pages causes the Save and close button to appear before the settings tabs programmatically, even though it appears after the tabs visually. For more details, see issue #700- Object navigation in Narrator not in the logical/ visual sequence. This PR changes the programmatic order of the settings page from:
1. Back button
2. Settings text
3. Save and close button 
4. Tab container (and all children)
to:
1. Back button
2. Settings text
3. Tab container (and all children)
4. Save and close button 
This should make the page more logical for AT users. It should have no impact for non-AT users and no impact on tab order.
> Note: After the PR has been created, …
> Change programmatic order of settings page save button

- src/AccessibilityInsights.SharedUx/ViewModels/TextRangeViewModel.cs
This is the AIWin-side change of https://github.com/microsoft/axe-windows/issues/265. It ensures that style IDs are properly formatted in the UI. Instead of saying "Unknown(70001)", it will now say "Heading1(70001)". It will only display "Unknown" if the numeric value is not identified in https://github.com/microsoft/axe-windows/blob/master/src/Desktop/Styles/StyleId.cs
- [] Run the production version of Accessibility Insights for Windows against a version with changes.
Screenshot of dialog displaying "Normal" style--before this change it would say "Unknown(70012)" instead of "Normal(70012)"
> Display style id correctly

- src/MSI/Product.wxs
Update shortcut name from "Accessibility Insights" to "Accessibility Insights for Windows" to avoid ambiguity if multiple products are installed.
- [] Does this address an existing issue? If yes, Issue# - 
- [] Run the production version of Accessibility Insights for Windows against a version with changes.
> Update shortcut name for clarity

- src/AccessibilityInsights.Extensions.AzureDevOps/ConfigurationControl.xaml
- src/AccessibilityInsights.Extensions.AzureDevOps/Properties/Resources.Designer.cs
- src/AccessibilityInsights.Extensions.AzureDevOps/Properties/Resources.resx
- src/AccessibilityInsights.SharedUx/Properties/Resources.Designer.cs
- src/AccessibilityInsights.SharedUx/Properties/Resources.resx
Using an AT in the Azure Boards Connections dialog is extremely chatty. We use a combobox that currently incorporates the placeholder text into it to make it friendlier. Unfortunately, when NVDA or JAWS read the dialog, it repeats a long string, resulting in too much data to really be usable.
Here's what gets read before this change:
**NVDA**: "Enter the full Azure DevOps URL such as https://dev.azure.com/fabrikam combobox collapsed. Enter the full Azure DevOps URL such as https://dev.azure.com/fabrikam edit. Blank."
**JAWS**: "Enter the full Azure DevOps URL such as https://dev.azure.com/fabrikam combobox. Enter the full Azure DevOps URL such as https://dev.azure.com/fabrikam edit combo. To set the value use the arrow keys or type the value."
We're setting the automation name on the …
> Simplify automation name in Azure Boards connection dialog

- src/AccessibilityInsights.Extensions.AzureDevOps/ConfigurationControl.xaml
- src/AccessibilityInsights.Extensions.AzureDevOps/Properties/Resources.Designer.cs
- src/AccessibilityInsights.Extensions.AzureDevOps/Properties/Resources.resx
The "Server URL" text only manifests in JAWS, and adds no value. Removing it. I didn't try to update the rest of the grid, since it's autosized and an empty grid row will have 0 height.
> Remove text that only shows up in JAWS

- src/AccessibilityInsights.SharedUx/Resources/HighContrast/Brushes.xaml
- src/AccessibilityInsights.SharedUx/Resources/Light/Brushes.xaml
- src/AccessibilityInsights.SharedUx/Resources/Styles.xaml
While working on the dark mode change, I found the following brush definitions that appear to be unused anywhere in the code. I'm hoping to remove them before completing the dark mode changes. Part of this removes the `rbSelect` style, since it is unused and contains references to 2 brushes that are otherwise unused.
> Palette scrub

- src/AccessibilityInsights/MainWindow.xaml
- src/AccessibilityInsights/Modes/SnapshotModeControl.xaml
#719 introduced a regression by changing the ZIndex of the breadcrumbs to be "above" the tab control that displays the properties and HowToFix information. This was done to fix a breadcrumb button breaking. As a result, the tabs are not being displayed correctly. This change reverts the ZIndex change because it's better to have the broken breadcrumb than to not have the tabs.
With the ZIndex change:
With the ZIndex change reverted
> Ensure that tabs are displayed (at the expense of a broken button)

- src/AccessibilityInsights/Modes/TestModeControl.xaml
#719 and #721 left a broken button in the breadcrumbs. Cause is that the transparent background of the grid is causing the HitTest of the button to fail, so it no longer worked with the mouse. Fix is to remove the transparent background on the grid (a change that was in #719) to restore the breadcrumb behavior. Colors are still correct in both light and dark mode.
Screenshots with mouse over breadcrumb.
Before (no underline on mouse over, clicking does nothing):
After (underline on mouse over, clicking returns to live mode):
> Fix breadcrumb button (HitTest was impacted by transparent background)

- src/AccessibilityInsights.SharedUx/Controls/EventConfigTabControl.xaml
- src/AccessibilityInsights.SharedUx/Controls/EventRecordControl.xaml
- src/AccessibilityInsights.SharedUx/Resources/Dark/Brushes.xaml
- src/AccessibilityInsights.SharedUx/Resources/Styles.xaml
Update colors used in events view to properly handle dark mode
In the following screenshots, the current Canary build is shown in the top, with the revised build in the bottom.
Light mode, selecting events to record--UI should be basically the same
Dark mode, selecting events to record--UI should fix contrast issues in current code:
Light mode, showing recorded events--UI should be basically the same:
Dark mode, showing recorded events--UI should fix contrast issues in current code:
> Update events view for dark mode

- src/AccessibilityInsights/Modes/LiveModeControl.xaml
Live mode instructions support limited horizontal scroll (the links won't word wrap) but no vertical scroll. This adds a ScrollViewer around the StackPanel to get the vertical scroll, and sets the word wrap on the links so that they work better.
Video is in 2 parts--first part is using the mouse, second part is using the keyboard. Mouse cursor is inaccurately recorded in the video (bug in LiceCap)
> Scroll Live Mode Instructions

- src/AccessibilityInsights/Modes/LiveModeControl.xaml
- src/AccessibilityInsights/Modes/LiveModeControl.xaml.cs
Change #720 had a bug that it never collapsed the ScrollViewer, meaning that the transparent ScrollViewer ate all mouse input intended for the hierarchy control. #724 reverted the change from #720. 
This change restores #720, but with 3 additional changes:
1. It names the ScrollViewer as svInstructions
2. Where the code-behind used to collapse spInstructions, it now collapses svInstructions
3. Where the code-behind used to show spInstructions, it now shows svInstructions
The net result is that we get the scrolling as before, and that the hierarchy control gets the mouse input, as intended.
> Repeat of #720, this time collapsing the ScrollViewer

- src/AccessibilityInsights.SharedUx/Resources/Dark/Brushes.xaml
- src/AccessibilityInsights/Dialogs/UpdateDialog.xaml
The update dialog doesn't work well in dark mode
Update dialog showing a mandatory update in light mode (current is on top, revised is on the bottom--note how the current version makes the disabled "Later" button disappear completely, even though it's still in the UIA tree. I checked with @jalkire, and the "disappearing text" seems wrong to him. I checked with @ferBonnin about color contrast requirements for disabled text, and she confirmed that disabled buttons have no contrast requirement, so the current changes will be OK. She mentioned that we might want to simply remove the permanently disabled button as a usability improvement. I'll bring this up with @adarshrema, and if he approves the removal, that will be a separate PR. 
Update dialog showing a mandatory update in dark mode …
> Update dialog: Better support in dark mode

- src/AccessibilityInsights/Dialogs/UpdateDialog.xaml
- src/AccessibilityInsights/MainWindowHelpers/AutoUpdate.cs
The Update dialog currently disables the "Update later" button when a mandatory update takes place. Usability studies consistently show that permanently disabled buttons are confusing to users, and that it's preferable to simply remove the permanently disabled button. 
Screenshot is below. The "optional update" (the top image) experience is unchanged. In the old "required update" case (the middle image), the "Later" button is diabled. In the "required update" (the bottom image), the "Later"button gets collapsed.
> Collapse the "Update later" button when it will be permanently disabled

- src/AccessibilityInsights/MainWindow.xaml
The caption and command bars get overwritten as the window shrinks and/or the text size grows. This PR adjusts the positioning and backgrounds of the controls. It does _not_ address the problem of the items on the right of the command bar becoming unavailable as the window becomes smaller.
Before the change:
After the change:
> Improve border area at zoom

- src/AccessibilityInsights.SetupLibrary/VersionSwitcherWrapper.cs
Our existing upgrade code copies the VersionSwitcher app from ProgramFiles to Temp, then executes from Temp. We lock each file against writing immediately after copying it, but there's a tiny time window where a malicious app could theoretically modify the copied file before it is locked. This change waits until after the file is protected against writing, then compares its contents to the source file. There's a potential for a perf hit here, but since both source and destination files are probably still in the disk cache, it should be minimal.
This PR includes one other tiny change. #266 bypassed the method that validates that the source folder exists. This change seemed unintentional since it created an unused method. I noticed this unused method only because of the color coloring when …
> Ensure copied VersionSwitcher files are identical to their source files

- build/build-and-unit-tests.yml
- build/build-without-fakes.yml
- build/signedbuild.yml
- build/ui-test-job.yml
Currently, our remote builds run using Visual Studio 2019 (16.0). Our remote NuGet restores, however, use a [deprecated NuGet install task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/prev-versions/nuget-installer-0?view=azure-devops) that installs NuGet 4.3, which is associated with Visual Studio 2017. This combination has caused recent build issues. This PR updates the build to use the current version of the NuGet install task and specifies the use of NuGet version 5.x, which corresponds with VS2019. A successful run of the signed build (or at least the NuGet related parts) can be [found here](https://dev.azure.com/mseng/1ES/_build/results?buildId=11746468&view=results).
This PR does not attempt to update our csproj files to reference VS 2019.
- [n/a] Run …
> Update NuGet version in remote builds from 4.3 to 5.x

- src/AccessibilityInsights.SharedUx/Controls/ColorChooser.xaml
- src/AccessibilityInsights.SharedUx/Controls/TestTabs/ColorContrast.xaml
- src/AccessibilityInsights.SharedUx/Resources/Dark/Brushes.xaml
Early feedback from the dark mode feature pointed out that we'd overlooked both the color edits and the Ratio control in Color Contrast. This fixes both.
Before the change (shows both light and dark mode):
After the change (shows both light and dark mode):
> Color contrast more dark mode

- src/AccessibilityInsights.Extensions.GitHubAutoUpdateUnitTests/Extensions.GitHubAutoUpdateUnitTests.csproj
- src/AccessibilityInsights.Extensions.GitHubUnitTests/Extensions.GitHubUnitTests.csproj
- src/AccessibilityInsights.SharedUxTests/SharedUxTests.csproj
I merged #736 and #737 without picking up the changes in the .config files. This PR completes the task, using VS to update. I'm not really sure why VS chose the lib461 versions of the files instead of the netstandard2.0 files, but I'm willing to trust the tooling. These files are ultimately not critical, as this is test code that isn't consumed by anything else.
> Complete Dependabot changes that I merged too soon

- build/signedbuild.yml
This PR removes the symbol publishing tasks from our signed build. We don't use them or need them, so we are removing them.
> Stop publishing symbols from build

- src/AccessibilityInsights.Extensions.AzureDevOps/AzureDevOpsIntegration.cs
- src/AccessibilityInsights.Extensions.AzureDevOps/ConnectionInfo.cs
- src/AccessibilityInsights.Extensions.AzureDevOps/Extensions.AzureDevOps.csproj
- src/AccessibilityInsights.Extensions.AzureDevOps/FileIssue/FileIssueHelpers.cs
- src/AccessibilityInsights.Extensions.AzureDevOps/ForcedDependencies.cs
- src/AccessibilityInsights.Extensions.AzureDevOps/Models/AdoTeam.cs
- src/AccessibilityInsights.Extensions.AzureDevOps/Models/TeamProject.cs
- src/AccessibilityInsights.Extensions.AzureDevOps/Models/TeamProjectViewModel.cs
- src/AccessibilityInsights.Extensions.AzureDevOps/app.config
- src/AccessibilityInsights.Extensions.AzureDevOps/packages.config
- src/AccessibilityInsights.Extensions.AzureDevOpsTests/AzureBoardsIssueReportingTests.cs
- src/AccessibilityInsights.Extensions.AzureDevOpsTests/ConnectionInfoTests.cs
- src/AccessibilityInsights.Extensions.AzureDevOpsTests/DependencyTests.cs
- src/AccessibilityInsights.Extensions.AzureDevOpsTests/Extensions.AzureDevOpsTests.csproj
- src/AccessibilityInsights.Extensions.AzureDevOpsTests/app.config
- src/AccessibilityInsights.Extensions.AzureDevOpsTests/packages.config
- src/AccessibilityInsights.Fakes.Prebuild/Fakes.Prebuild.csproj
- src/AccessibilityInsights.Fakes.Prebuild/app.config
- src/AccessibilityInsights.Fakes.Prebuild/packages.config
- src/AccessibilityInsights.SharedUx/SharedUx.csproj
- src/AccessibilityInsights.SharedUx/packages.config
- src/AccessibilityInsights.SharedUxTests/SharedUxTests.csproj
- src/AccessibilityInsights.SharedUxTests/app.config
- src/AccessibilityInsights.SharedUxTests/packages.config
- src/AccessibilityInsights/packages.config
- src/MSI/Product.wxs
- src/UITests/UITests.csproj
- src/UITests/app.config
- src/UITests/packages.config
This is part 2 of 2. It includes the changes to upgrade to the most recent version of the packages used by the ADO extension. It also includes a conversion of ADO from packages.config to PackageReferences, which reduces the overhead of managing NuGet packages. We'd do well to make this conversion in all projects, but the ADO extension was the worst offender concerning transitive dependencies.
We've already done a full validation of the bits in the Net472_UpdateADO branch, including checking for accessibility issues and validating that ADO behaves as it does in current builds. Once this PR is approved, the code will be merged into the Net472 branch, and the Net472 branch will be merged into master via #740.
Note that this replaces #741, since our signed build system apparently isn't …
> Net472 updated ADO (without package references)

- src/AccessibilityInsights.SharedUx/Settings/ConfigurationManager.cs
Refactor ConfigurationManager.GetDefaultInstance to prevent NullReferenceException (instead of ignoring it)
`ConfigurationManager.GetDefaultInstance` contains some hackiness to allow for the fact that we sometimes ask for the configuration before we can fully answer the question. The old code caught and ate a NullReferenceException during initialization, but the current version of Visual Studio treats this as an unhandled Exception and stops in the debugger. This change prevents the Exception rather than eating it. In the offhand chance that an Exception still occurs, we catch it and log it. It makes no attempt to fix the ugliness inherent to how we're creating the singleton.
> Note: After the PR has been created, certain checks will be kicked off. All of these checks must pass before a …
> Refactor ConfigurationManager.GetDefaultInstance

- src/AccessibilityInsights.SharedUx/Resources/Dark/Brushes.xaml
- src/AccessibilityInsights.SharedUx/Resources/HighContrast/Brushes.xaml
- src/AccessibilityInsights.SharedUx/Resources/Light/Brushes.xaml
- src/AccessibilityInsights.SharedUx/Resources/Styles.xaml
- src/AccessibilityInsights/MainWindow.xaml
Issue #756 calls out a regression that (as a result of the dark mode changes) several icons disappear in HC White mode. This change creates 4 new colors in the palette and leverages these color to ensure that HC modes (especially HC White) are working properly. It restore pre-dark mode parity, plus it fixes the fact that command bar icons were kind of broken on mouse hover in HC White mode. There are still some mouse hover issues in HC White mode, but those will get fixed in a separate PR.
Also, #756 only called out issues in Live mode. This also fixes a couple of icons in Test mode that had the same problem (no screenshots for these)
- [ x Does this address an existing issue? If yes, Issue# - #756 
Production (before dark mode changes):
Canary (with dark mode changes):
Version with these …
> Fix high contrast regression

- src/AccessibilityInsights.SharedUx/Highlighting/Win32SnapshotButton.cs
- src/AccessibilityInsights.SharedUx/Resources/Dark/Brushes.xaml
- src/AccessibilityInsights.SharedUx/Resources/HighContrast/Brushes.xaml
- src/AccessibilityInsights.SharedUx/Resources/Light/Brushes.xaml
- src/AccessibilityInsights/App.xaml.cs
Highlighter and snapshot button contrast is a little odd in high contrast modes. It's something of an inexact science, since it depends on the pixels around the element being highlighted, but this change makes it a little better. We use the system-defined "Hot tracking color", which is defined [here](https://docs.microsoft.com/en-us/dotnet/api/system.windows.systemcolors.hottrackcolor?view=netframework-4.8) as "The color used to designate a hot-tracked item".
The Snapshot button background is drawn in the same color, and the snapshot button icon is drawn in a system color that is always black in HC Black themes, and white in the HC White theme.
Light and dark mode haven't changed, and we've made no attempt to respect HC settings in the tooltip. These screen grabs are all taken using …
> Improve highlighter contrast in HC modes

- src/AccessibilityInsights.SharedUx/SharedUx.csproj
- src/AccessibilityInsights.SharedUx/packages.config
- src/AccessibilityInsights.SharedUxTests/SharedUxTests.csproj
- src/AccessibilityInsights.SharedUxTests/app.config
- src/AccessibilityInsights.SharedUxTests/packages.config
- src/AccessibilityInsights/AccessibilityInsights.csproj
- src/AccessibilityInsights/packages.config
- src/UITests/UITests.csproj
- src/UITests/packages.config
Pick up the latest Axe.Windows. This change includes only the removal of some DebugBreak statements that were left in Axe.Windows for debugging, but shouldn't be in the shipping bits.
> Update to Axe.Windows 0.9.4 

- thirdpartynotices.html
Update third party notices again. We just did this, but some components were lacking licensing data, so they weren't included in the notices file. This file was auto-generated by going to the OSS notice generation tool (https://tools.opensource.microsoft.com/notice), copying in the link to our latest component governance update (https://dev.azure.com/mseng/1ES/_componentGovernance/164/history/900640), and clicking the generate button. The resulting file was copied over the existing thirdpartynotices.html.
> Update third party notices (previous list was incomplete)

- src/AccessibilityInsights.Extensions.AzureDevOps/ConfigurationControl.xaml
- src/AccessibilityInsights.SharedUx/Controls/HierarchyControl.xaml
- src/AccessibilityInsights.SharedUx/Controls/InspectTabsControl.xaml
- src/AccessibilityInsights.SharedUx/Controls/TestTabs/ColorContrast.xaml
- src/AccessibilityInsights.SharedUx/Resources/Dark/Brushes.xaml
- src/AccessibilityInsights.SharedUx/Resources/HighContrast/Brushes.xaml
- src/AccessibilityInsights.SharedUx/Resources/Light/Brushes.xaml
- src/AccessibilityInsights.SharedUx/Resources/Styles.xaml
- src/AccessibilityInsights/Modes/ConfigurationModeControl.xaml
- src/AccessibilityInsights/Modes/TestModeControl.xaml
This provides more fixes to dark modes, and fixes a high contrast issue that was discovered along the way.
Problem 1: Captions in the "Test Results view" didn't respect dark mode. Current behavior is on top, updated behavior on the bottom (ignore scale difference):
Problem 2: "Disconnect Azure Boards account" button needed a different foreground color. Current behavior is on top, updated behavior on the bottom (ignore scale difference):
Problem 3: Non-selected tabs in the settings dialog needed a different foreground color. Current behavior is on top, updated behavior on the bottom (ignore scale difference):
Problem 4: "FastPass" text and icon need to stand out more in dark mode. Current behavior is on top, updated behavior on the bottom (ignore scale difference):
Problem 5: "Selected …
> More dark mode changes

- src/AccessibilityInsights.SharedUx/Settings/ConfigurationConstants.cs
- src/AccessibilityInsights.SharedUx/Settings/ConfigurationModel.cs
- src/AccessibilityInsights.SharedUxTests/Resources/ConfigSettings.json
- src/AccessibilityInsights.SharedUxTests/Settings/ConfigurationModelTests.cs
- src/AccessibilityInsights/MainWindow.xaml.cs
We've recently made changes to enable dark mode, but kept the behavior behind a flag that could only be set by manually editing Configuration.json. We now think they're ready to be enabled by default, but we'll keep a config flag to disable them if problems arise.
To disable dark mode in just Accessibility Insights for Windows:
1. Exit Accessibility Insights for Windows
2. Edit %localappdata%\AccessibilityInsights\V1\Configurations\Configuration.json
3. Insert the following line somewhere in the middle of the file: 
"DisableDarkMode": true,
4. Save the updated file
5. Start Accessibility Insights for Windows
> Enable dark mode by default

- src/AccessibilityInsights.SharedUx/Dialogs/StartUpModeControl.xaml
- src/AccessibilityInsights.SharedUx/Dialogs/StartUpModeControl.xaml.cs
- src/AccessibilityInsights.SharedUx/Misc/VersionTools.cs
- src/AccessibilityInsights.SharedUx/Properties/Resources.Designer.cs
- src/AccessibilityInsights.SharedUx/Properties/Resources.resx
- src/AccessibilityInsights.SharedUx/ViewModels/AboutTabViewModel.cs
The welcome screen was flagged for update in #299, and also flagged for 200% zoom issues in #787. This PR addresses both via the following changes:
1. It adds a link to the release notes for the version
2. It adds clarifying text about shortcuts, and a link to https://accessibilityinsights.io/docs/en/windows/reference/keyboard, where the user can learn more about shortcuts and how to change them.
3. It massages the formatting to better fit a 200% zoom screen
4. By PM request, it changes the initial focus from the link to play the video to the link to the release notes.
Most of the changes are in StartupModeControl.xaml, although there was also a small refactor to better leverage version code from both the Startup and Settings screens.
Previous welcome screen at 200% zoom, maximized: …
> Update the welcome screen

- src/AccessibilityInsights.SharedUx/Controls/TextRangeControl.xaml
- src/AccessibilityInsights.SharedUx/Dialogs/TextPatternExplorerDialog.xaml
- src/AccessibilityInsights.SharedUx/Resources/Dark/Brushes.xaml
- src/AccessibilityInsights.SharedUx/Resources/HighContrast/Brushes.xaml
- src/AccessibilityInsights.SharedUx/Resources/Light/Brushes.xaml
Fix foreground color in `TextRangeControl` (was incorrectly styled for dark mode)
Light mode:
Dark mode (looks just like light mode since this dialog isn't styled at this time):
High Contrast 1:
High Contrast 2:
High Contrast Black:
High Contrast White:
> Add a new color to handle the text color in the TextRangeControl

- src/AccessibilityInsights.Extensions.TelemetryTests/Extensions.TelemetryTests.csproj
- src/AccessibilityInsights.Extensions.TelemetryTests/app.config
- src/AccessibilityInsights.Extensions.TelemetryTests/packages.config
When revising the TelemetryTests project to not use fakes, I accidentally used older versions of some assemblies. This consolidates the versions to the same versions used in other projects.
> Update assembly versions for TelemetryTests

- src/AccessibilityInsights.Extensions.Telemetry/Extensions.Telemetry.csproj
- src/AccessibilityInsights.Extensions.Telemetry/app.config
- src/AccessibilityInsights.Extensions.Telemetry/packages.config
- src/AccessibilityInsights.Extensions.TelemetryTests/Extensions.TelemetryTests.csproj
- src/AccessibilityInsights.Extensions.TelemetryTests/app.config
- src/AccessibilityInsights.Extensions.TelemetryTests/packages.config
- src/AccessibilityInsights/App.config
- src/UITests/app.config
VS-driven change to update Microsoft.ApplicationInsights assembly to most recent version. We had delayed this before due to complications using Fakes. Now that the Fakes are gone, there's no longer a reason to ship the old version.
VS added some additional assembly references in the csproj and config files, so I confirmed that the WXS file already includes all of the files that get dropped to the build folder.
Validated telemetry changes by running locally and ensuring that my installation ID shows up in the telemetry with a correct list of actions that I ran.
> Bump Microsoft.ApplicationInsights from 2.10.0 to 2.14.0

- src/AccessibilityInsights.Extensions.AzureDevOps/Extensions.AzureDevOps.csproj
- src/AccessibilityInsights.Extensions.AzureDevOps/app.config
- src/AccessibilityInsights.Extensions.AzureDevOps/packages.config
- src/AccessibilityInsights.Extensions.AzureDevOpsTests/Extensions.AzureDevOpsTests.csproj
- src/AccessibilityInsights.Extensions.AzureDevOpsTests/app.config
- src/AccessibilityInsights.Extensions.AzureDevOpsTests/packages.config
- src/AccessibilityInsights/AccessibilityInsights.csproj
- src/AccessibilityInsights/App.config
- src/AccessibilityInsights/packages.config
- src/UITests/UITests.csproj
- src/UITests/app.config
- src/UITests/packages.config
Bump Microsoft.IdentityModel.Clients.ActiveDirectory from 5.2.7 to 5.2.8
Bump System.IdentityModel.Tokens.Jwt from 6.7.0 to 6.7.1
> Bump dependencies manually after Dependabot failed to

- README.md
- docs/FAQ.md
I noticed that we're still referencing Win7 & Win8 in a couple of our markdown files, including at the very top of our readme file. Since our current policy is to support Microsoft-supported versions, I just referred to Windows and let the docs be the only place that describe supported versions. There's less to maintain that way. There are still Win7-specific code paths in the tool, and this PR makes no attempt to change or remove them. While we aren't explicitly supporting Win7, we also aren't intentionally breaking it. …
> chore: Remove references to old Windows versions

- build/settings.targets
- src/AccessibilityInsights/AccessibilityInsights.csproj
Currently, AI-Win contains several third party assemblies which are not signed with a Microsoft cert. This PR signs those assemblies with the appropriate cert. You can find the signed artifacts [here](https://dev.azure.com/mseng/1ES/_build/results?buildId=12657721&view=artifacts&type=publishedArtifacts) (different branch, same relevant configuration).
> Note: After the PR has been created, …
> Sign 3rd party assemblies

- src/MSI/Product.wxs
PR #847 ensured that we sign third party assemblies that we ship. It missed the Newtonsoft.JSON DLL that we include in the VersionSwitcher directory. Rather than signing the same DLL twice, this PR changes Product.wxs to reuse the already signed Newtonsoft DLL in the VersionSwitcher directory. 
> Note: After the PR has been created, certain checks will be kicked off. All of these checks must …
> Include only the signed Newtonsoft DLL in MSI

- src/AccessibilityInsights/AccessibilityInsights.csproj
- src/MSI/Product.wxs
This PR signs Microsoft.Deployment.WindowsInstaller.dll with the appropriate cert & ensures we ship only signed the DLL. I also verified that no other DLLs included in our MSI lack a signature from a Microsoft cert.
> Sign WindowsInstaller assembly & use in MSI

- build/signedbuild.yml
Currently, the auto injected signing validation task scans our entire build directory, which results in hundreds of false positives. This PR updates our signed build to copy the assemblies and executables that we ship to a particular directory and directs the signing validation task to scan only that directory. You can find an example of the files copied to the SigningValidation directory [here](https://dev.azure.com/accessibility-insights/Accessibility%20Insights/_build/results?buildId=11813&view=artifacts&type=publishedArtifacts).
- [n/a] Run the …
> Copy files to signing validation directory & scan it

- src/AccessibilityInsights.Extensions.AzureDevOps/AzureBoardsIssueReporting.cs
- src/AccessibilityInsights.Extensions.GitHub/IssueReporter.cs
- src/AccessibilityInsights.Extensions/Interfaces/IssueReporting/IIssueReporting.cs
- src/AccessibilityInsights.ExtensionsTests/DummyClasses/DummyIssueReporting.cs
- src/AccessibilityInsights.SharedUx/FileIssue/IssueReporter.cs
- src/AccessibilityInsights.SharedUx/FileIssue/IssueReporterManager.cs
- src/AccessibilityInsights.SharedUxTests/FileIssue/IssueReporterManagerTests.cs
As called out in #809, we're failing to save user customizations in zoom level. The root cause is that when we make each IIssueReporting responsible to serialize its own settings, we assumed (incorrectly) that settings would only ever change from the settings tab. As such, when the user zoom is customized, it never gets written to the config file. 
The fix is to add a new method to IIssueReporting, which optionally exposes the current serialized object, and then update this after calling FileIssueAsync. If the IIssueReporting implementation provides information, save it to the config file.
Test:
1. Open AIWin
2. Scan an app (Wildlife Manager will do nicely)
3. Start bug filing via ADO
4. Change the zoom level from its original value
5. Exit the bug filing (doesn't matter if you file the …
> fix: Persist zoom level from ADO issue filing

- src/AccessibilityInsights/Modes/EventModeControl.xaml
- src/AccessibilityInsights/Modes/LiveModeControl.xaml
- src/AccessibilityInsights/Modes/SnapshotModeControl.xaml
Currently, if a user reduces a left column width (such as the hierarchy tree in live mode) to 0, they can no longer use the mouse to resize that column. This PR addresses that concern by setting the min column width of applicable columns to 2. This ensures the user can always resize the column with their mouse.
New behavior:
This PR addresses [BUG] Unable to view the UIA tree once the pane width has been reduced to zero #814
> Set minimum width in mode control left columns

- src/AccessibilityInsights.SharedUx/Enums/HighlighterColor.cs
- src/AccessibilityInsights.SharedUx/Highlighting/Highlighter.cs
- src/AccessibilityInsights.SharedUx/Highlighting/TextRangeHilighter.cs
As called out in #840, there's a null dereference when using the text patterns dialog. The root cause was overlooking the fact that highlighter colors are prefixed with "HL", and attempting to use a color without this prefix. We couldn't find a color, returned null, and caused a null dereference exception. This is a regression of the palette work for dark mode, so this change essentially reverts the change to the highlighter color and adds comments to help avoid similar breaks in the future.
One thing that is _not_ addressed in this change is that since we choose our highlighter color with no awareness of the colors being used by the target app, there's no guarantee of the visual impact that the highlighter will have in the context of the target app. Our highlighter is always yellow, …
> Fix null dereference in text patterns

- build/signedbuild.yml
Our signing plugin version is no longer supported, so we need to upgrade. This is the same change as in https://github.com/microsoft/axe-windows/pull/418
Validation build showing it works: https://dev.azure.com/mseng/1ES/_build/results?buildId=12757594&view=results
> chore: Use newer version of signing plugin

- src/MSI/MSI.wixproj
- src/MSI/Product.wxs
Our MSI project is generating some warnings that we'd like to remove to get our build to no warnings in the build pipe. Here's a sample from a recent build:
- [warning]src\MSI\Product.wxs(51,0): Warning CNDL1113: Because it is an advertised shortcut, the target of shortcut 'aiforwin' will be the keypath of component 'FileExe' rather than parent file 'ProductComponent'. To eliminate this warning, you can (1) make the Shortcut element a child of the File element that is the keypath of component 'FileExe', (2) make file 'ProductComponent' the keypath of component 'FileExe', or (3) remove the @Advertise attribute so the shortcut is a non-advertised shortcut.
- [warning]src\MSI\Product.wxs(181,0): Warning LGHT1076: ICE69: Mismatched component reference. Entry 'ApplicationStartMenuShortcut' of …
> chore: Fix/suppress msi warnings

- src/AccessibilityInsights/AccessibilityInsights.csproj
- src/MSI/MSI.wixproj
Our current signed build is producing the following signing-related warnings:
[warning]E:\A\_work\5\a\MicroBuild\Plugins\MicroBuild.Plugins.Signing.1.1.295\build\MicroBuild.Plugins.Signing.targets(43,5): **Warning : File E:\A\_work\5\s\src\AccessibilityInsights\bin\Release\net472\AccessibilityInsights.exe is listed more than once in the file list. Duplicate instances are being ignored**
[warning]E:\A\_work\5\a\MicroBuild\Plugins\MicroBuild.Plugins.Signing.1.1.295\build\MicroBuild.Plugins.Signing.targets(93,5): **Warning : File E:\A\_work\5\s\src\MSI\bin\Release\AccessibilityInsights.msi is listed more than once in the file list. Duplicate instances are being ignored**
The root cause is that we add `$(TargetPath)` to `$(DropSignedFile)` inside `build\NetFrameworkRelease.targets`, then we …
> chore: Fix duplicate signing

- build/signedbuild.yml
For a long time now, we've had the following warning when our `ComplianceDebug` step of signed pipeline builds tried to run FxCop:
**[warning]Empty target provided.**
It was mostly lost in the noise of other warnings, but it's now the only warning left. Comparing the TSA uploads from AIWin to the TSA uploads from Axe.Windows, AIWin has no security Analyzers in its report.
To fix the warning and to ensure that our TSA reports include Roslyn Analyzers, this PR replaces the (obsolete) FxCop task with the Roslyn Analyzers task and updates the rest of the pipeline accordingly. The changes here are are based on the ComplianceDebug tasks of [Axe.Windows](https://github.com/microsoft/axe-windows/blob/master/build/signedbuild.yml)
Validation build showing no warnings and also showing that we're …
> chore: Replace FxCop with Roslyn Analyzers

- src/AccessibilityInsights.SharedUx/Controls/EventConfigTabControl.xaml
- src/AccessibilityInsights.SharedUx/Controls/EventConfigTabControl.xaml.cs
- src/AccessibilityInsights.SharedUx/ViewModels/EventConfigNodeViewModel.cs
As described in #815, the checkboxes in the event selection dialog don't follow the 3-state hierarchical selection pattern and are potentially confusing. This PR adds the plumbing needed to support the expected 3-state selection pattern. It includes the following changes:
- Expose an `IsThreeState` property to the `EventConfigNodeViewModel` class, and provide a way to set it when the node is constructed.
- Bind the `IsThreeState` property to the 3 key checkboxes in the configuration page
- Provide a notification to a ThreeState parent when any of its children change state or if the set of children is modified
- Teach the ThreeState parent to recalculate its `IsChecked` state in response to a modified child
- The natural order of a ThreeState checkbox is On, Mixed, Off, and that order will …
> fix: Support ThreeState checkboxes when selecting events to listen to

- src/AccessibilityInsights.SharedUx/ViewModels/EventConfigNodeViewModel.cs
This includes a PR suggestion from #888 that I didn't see until after the merge was complete. Re-ran the key event listening scenarios to ensure that it's working as expected. 
> Incorporate PR feedback that I saw after merging

- src/AccessibilityInsights.VersionSwitcher/VersionSwitcher.csproj
As called out in #891, VersionSwitcher is no longer elevating, meaning that upgrade and channel changing scenarios are broken. This was a regression introduced when we recently changed the csproj formats (#836). It only impacts Canary builds since we haven't yet shipepd that build. Just as insurance against this in the future, I'll add a test for this in the validation template.
I validated this locally by simply running VersionSwitcher.exe from the explorer. Before the change, it skips the LUA prompt and goes directly to the message about bad parameters. After the change, it gives a LUA prompt. If permissions are granted, the bad parameters message is displayed. If permissions are denied, no message is displayed.
I also double-checked that the external UIAccess manifest for …
> fix: Re-add app manifest to VersionSwitcher

- src/AccessibilityInsights.SharedUx/Controls/PatternInfoControl.xaml
- src/AccessibilityInsights.SharedUx/Controls/PatternInfoControl.xaml.cs
- src/AccessibilityInsights.SharedUx/Controls/PropertyInfoControl.xaml
- src/AccessibilityInsights.SharedUx/Controls/PropertyInfoControl.xaml.cs
- src/AccessibilityInsights/MainWindow.xaml
- src/AccessibilityInsights/MainWindow.xaml.cs
The "standard" for Windows apps (based on notepad, Office, and many others) is to trigger copy on KeyDown of Ctrl+C. AIWin is triggering on KeyUp of Ctrl+C. It probably shouldn't make much difference unless a user's muscle memory (like mine) is to do them quickly enough that the C is released slightly _after_ the Ctrl key. Copying will appear to be broken for users who do this, which is what led to #887. With this change in place, AIWin behaves like other Windows apps and copying feeling robust.
> Note: After the PR has been created, certain checks will be kicked off. All of these checks must pass …
> fix: Change Ctrl+C from KeyUp to KeyDown (typical for Windows apps)

- src/AccessibilityInsights.SharedUx/Converters/ColumnMaxWidthSpacingConverter.cs
- src/AccessibilityInsights.SharedUx/Resources/Styles.xaml
- src/AccessibilityInsights.SharedUxTests/Converters/ColumnMaxWidthSpacingConverterTests.cs
- src/AccessibilityInsights/Modes/EventModeControl.xaml
- src/AccessibilityInsights/Modes/LiveModeControl.xaml
- src/AccessibilityInsights/Modes/SnapshotModeControl.xaml
As promised in #852, this PR introduces a max column width to our main UI's left column (which usually holds the UIA tree). This is analogous to the min column width requested in #814. To accomplish this, ColumnMaxWidthSpacingConverter is introduced and used to limit the column's max width to slightly smaller than its parent control. The LeftPaneColumn style is introduced and used to apply this converter to the left columns in the Live, Event, and Test (Snapshot) mode controls.
Behavior:
> Stop left column from extending outside of window

- src/UITests/LiveMode.cs
- src/UITests/UILibrary/LiveMode.cs
Currently, there are two issues with our UI tests:
1. The live mode UI tests fail because axe-windows has been updated and reports a different number of results and because we changed our directory structure.
2. The automation to load test and event files fails on my machine (but not the remote build).
This PR addresses 1 by updating the expected result count and WildlifeManager executable path and 2 by removing some unnecessary automation complexity. …
> Fix ui tests

- src/AccessibilityInsights.SharedUx/Controls/ScannerResultControl.xaml
- src/AccessibilityInsights.SharedUx/Controls/TestTabs/AutomatedChecksControl.xaml
- src/AccessibilityInsights.SharedUx/Properties/Resources.resx
We have 2 places where the visible text is "File Issue" but the AT-visible text is "File Bug". This change consolidates the 3 strings into 1 so that they're back in sync and will stay in sync until someone explicitly takes them out of sync.
Validated that NVDA is reading the same string that is displayed on screen
> feat(tt-aug-2020): Consolidate "File Bug" strings into "File Issue"

- src/AccessibilityInsights.SharedUx/Controls/SettingsTabs/ApplicationSettingsControl.xaml
The focus rect in High Contrast modes is thicker. The edit for the "set delay" text is just barely large enough in non-HC modes, and as a result the text can't really be seen in HC modes. This change makes the edit control larger in all modes and adjusts the surrounding elements to accommodate the change. With the wider control, the edit text looks funny left-justified, so I made it right-justified, instead. The text is limited to 4 characters, so it shouldn't fill the edit with only 3 characters
I opted for simplicity and went for fixed sizing, rather than making it sensitive to whether or not HC mode is enabled. I think it looks OK, but let me know if you think the edit needs to be smaller in non-HC modes.
Screenshots of old behavior in light mode, as well as new behavior in all modes …
> feat(tt-aug-2020): Make "set delay" edit more HC-friendly

- src/AccessibilityInsights.SharedUx/Controls/SettingsTabs/AboutTabControl.xaml
- src/AccessibilityInsights.SharedUx/Properties/Resources.Designer.cs
- src/AccessibilityInsights.SharedUx/Properties/Resources.resx
Narrator isn't currently announcing the version number from the version number link. Add the version number to the text that Narrator announces.
It's worth noting that Narrator announces only the automation name, while NVDA announces both the automation name and the text in the run. Making this change means that NVDA is double-speaking, but it's double speaking in the same way that it does with other links in this dialog (although that could be seen as exacerbating an existing problem).
Here's a table of what gets announced, just for reference (a comma represents a brief pause in the speaking)
visual text | old version + Narrator | new version + Narrator | old version + NVDA | new version + NVDA
--- | --- | --- | --- | ---
Version 1.1.1234.1 | Hyperlink, Version | Hyperlink, Version …
> feat(tt-aug-2020): Announce version # in version link

- src/AccessibilityInsights/Modes/LiveModeControl.xaml
- src/AccessibilityInsights/Modes/SnapshotModeControl.xaml
- src/AccessibilityInsights/Properties/Resources.Designer.cs
- src/AccessibilityInsights/Properties/Resources.resx
The vertical splitter specifies the wrong constant as its help text. This specifies the correct constant and consolidates 2 copies of the same string into a single constant.
Here are the before and after views of the help text for the splitter pane:
Before:
After:
- [A/T only] Includes UI changes?
> feat(tt-aug-2020): Use correct string for splitter help text

- src/AccessibilityInsights.SharedUx/Controls/SettingsTabs/AboutTabControl.xaml
In the about page, the text 'built with axe windows' is omitted from initial scan mode navigation because the UIA tree currently has 'built with axe windows' as a child of a text node with the axe-windows version. 
before:
Using a label / content pair seems to create a parent node with the content, and the computed content string format ends up underneath the text node. Switching to a simple textblock seemed to produce a better representation, with a single node (no parent/child pair) with the computed content string.
after:
> feat(tt-aug-2020): include "Built with Axe Windows" in scan mode when it has focus

- src/AccessibilityInsights.SharedUx/Controls/HierarchyControl.xaml
- src/AccessibilityInsights.SharedUx/Controls/HierarchyControl.xaml.cs
- src/AccessibilityInsights.SharedUx/Properties/Resources.Designer.cs
- src/AccessibilityInsights.SharedUx/Properties/Resources.resx
The placeholder text used in the Search box is not being announced via an A/T. After consulting with @RobGallo, we opted to read the placeholder text only if the user hasn't typed anything into the control. That prevents overwhelming the user with the prompt, and provides an experience analogous to what a visual user experiences. The matrix looks like this:
Mode | HelpText before user enters data | HelpText after user enters non-trivial data
Live | Search by name and control type | _none_
Test | Search by common string properties and patterns | _none_
This can be viewed in the following screenshots--the upper instance of AIWin shows the user state, and the lower instance of AIWin shows the help text:
Live mode, no text in search box:
Live mode, text in search box:
Test …
> feat(tt-aug-2020): Revise help text for search box

- src/AccessibilityInsights.Extensions.GitHub/ConfigurationModelControl.xaml
- src/AccessibilityInsights.Extensions.GitHub/Properties/Resources.Designer.cs
- src/AccessibilityInsights.Extensions.GitHub/Properties/Resources.resx
The placeholder text for the GitHub repo is not being exposed to screen readers. This change makes the sample text readable as text outside the edit control. It also shortens the accessible name of the edit control, since its functionality is described by the previous control, and makes the edit control wider. Design also suggested that we remove the placeholder, as it's redundant and placeholders are tricky in general.
Screenshot of revised dialog (with no user-provided text):
Screenshot of revised dialog (with user-provided text):
> Note: After the PR has been created, certain checks will be kicked off. All of these checks must pass before a …
> feat(tt-aug-2020): Expose GitHub sample URL as readable text

- src/AccessibilityInsights.SharedUx/Controls/TestTabs/ColorContrast.xaml
- src/AccessibilityInsights.SharedUx/Properties/Resources.Designer.cs
- src/AccessibilityInsights.SharedUx/Properties/Resources.resx
The guidance for auto-detection of color contrast is in a tooltip, which is not fully accessible via a screen reader. After considering our options, we decided to replace the tooltip with explanatory text that remains on-screen.
> feat(tt-aug-2020): Replace CCA tooltip with help text

- src/AccessibilityInsights.Extensions.AzureDevOps/ConfigurationControl.xaml
- src/AccessibilityInsights.Extensions.AzureDevOps/Properties/Resources.Designer.cs
- src/AccessibilityInsights.Extensions.AzureDevOps/Properties/Resources.resx
The placeholder text for the ADO issue filing link is not being exposed to screen readers. This change makes the sample text readable as text outside the combobox. It also shortens the accessible name of the combobox, since its functionality is described by the previous control. Finally, feedback from design was to remove the placeholder (they're discouraged by design and no longer necessary)
Screenshot of revised dialog (with no user-provided text):
Screenshot of revised dialog (with user-provided text):
> feat(tt-aug-2020): Expose ADO sample URL as readable text

- src/AccessibilityInsights.SharedUx/Controls/HierarchyControl.xaml.cs
Focus is shifting unexpectedly to the hierarchy tree when the user cancels the menu action. This change retains the behavior of shifting the focus to the tree when the user takes a menu action, but leaves the focus unchanged if no menu action is taken. This GIF shows the focus changes as the various menu actions are exercised.
More context: Shifting the focus on menu action was introduced from a [previous accessibility bug](https://mseng.visualstudio.com/AzureDevOps/_workitems/edit/1244534). That change had a side effect of also switching the focus when no action was taken 😦 
- [focus only] Includes UI changes?
> Note: After the PR has been created, certain checks will be kicked off. …
> feat(tt-aug-2020): Only set focus to hierarchy tree on menu action

- src/AccessibilityInsights.Extensions.AzureDevOps/ConfigurationControl.xaml
- src/AccessibilityInsights.Extensions.AzureDevOps/ConfigurationControl.xaml.cs
- src/AccessibilityInsights.Extensions.AzureDevOps/Properties/Resources.Designer.cs
- src/AccessibilityInsights.Extensions.AzureDevOps/Properties/Resources.resx
This fixes 2 issues with the ADO connection experience:
1. We no longer disable the connection button, because its disabled state wasn't distinguishable in high contrast modes.
2. We now display an error message if we're unable to connect to the server. The same code covers both the "unknown server" case (manifests as a timeout) and the "unknown project" case (manifests as an immediate error).
For brevity, the GIF excludes the timeout case.
> fix(tt-aug-2020): Enable connect button, add error message

- src/AccessibilityInsights.Extensions.AzureDevOps/ConfigurationControl.xaml.cs
These two lines need to be surrounded by Dispatcher.Invoke ([info here](https://docs.microsoft.com/en-us/dotnet/api/system.windows.threading.dispatcher.invoke?view=netcore-3.1#remarks)). Other operations in this area have them. Without these, the two following scenarios occur:
- when the project list is updated, an exception is sometimes caught mentioning the projects treeView can't be updated from a thread other than the one that owns it
- when using Narrator, an exception is thrown when raising the LoadedCompleted event
> fix: ensure two calls are made from the dispatcher

- src/AccessibilityInsights.Extensions.AzureDevOps/Extensions.AzureDevOps.csproj
To help maintain modularity, extensions are allowed to depend only on a set of low-level assemblies (SharedUX, SetupLibrary, Win32, and CommonUxComponents). Somehow the ADO extension is depending on SharedUx, even though it only needs CommonUxComponents (for the FabricIcon control). This machine-driven change simply replaces the SharedUx dependency with a CommonUxComponents dependency. Sanity tested that ADO still works as expected.
The search icon (highlighted in red) is visible in this snippet from a screenshot of running the ADO …
> chore: Extensions should not depend on SharedUX

- src/AccessibilityInsights.SharedUx/Controls/TestTabs/ColorContrast.xaml
- src/AccessibilityInsights.SharedUx/Resources/Dark/Brushes.xaml
- src/AccessibilityInsights.SharedUx/Resources/HighContrast/Brushes.xaml
- src/AccessibilityInsights.SharedUx/Resources/Light/Brushes.xaml
The "New for WCAG 2.1" bubble background colors were broken in #719. This change restores the Light colors to their original values from #502, and revisits the HC modes to reasonably display a bubble (#502 originally omitted the bubble in HC modes). We do this by explicitly assigning a bubble foreground color, in addition to the button background color (which was incorrect in Light mode). The Light background color disappeared when inserting the screenshot directly (limited palette, I'm guessing), so I've attached the zipped PNG file to the bug, instead.
[Bubbles.png.zip](https://github.com/microsoft/accessibility-insights-windows/files/5190243/Bubbles.png.zip)
> fix: Correct the colors used for bubbles

- src/AccessibilityInsights.Extensions.AzureDevOps/ConfigurationControl.xaml
- src/AccessibilityInsights.Extensions.AzureDevOps/ConfigurationControl.xaml.cs
- src/AccessibilityInsights.Extensions.AzureDevOps/Properties/Resources.Designer.cs
- src/AccessibilityInsights.Extensions.AzureDevOps/Properties/Resources.resx
This PR:
- raises a LiveRegionChanged event when the ADO connection screen goes into its indeterminate loading state
- places focus on the team project treeview once its data is populated
- updates the team project treeview automation name to 'select team project'
Using Narrator / NVDA, the user is now notified that the app is waiting to connect to Azure Boards when the "Loading..." control shows up.
> feat(tt-aug-2020): add status announcement when app is waiting for ADO connection

- src/AccessibilityInsights.SharedUx/Controls/TestTabs/AutomatedChecksControl.xaml
- src/AccessibilityInsights.SharedUx/Controls/TestTabs/AutomatedChecksControl.xaml.cs
- src/AccessibilityInsights.SharedUx/Properties/Resources.Designer.cs
- src/AccessibilityInsights.SharedUx/Properties/Resources.resx
The current UI puts the rule source in the group header in automated results view. This looks great but has accessibility issues because the link never makes it into the UIA tree. Feedback from users is that having the link at the top level is useful, so we're going with the approach of putting the link in each row. It's busy visually, but we'll see what sort of feedback we get and adjust accordingly.
The rule source link is announced a button instead of a hyperlink to better fit into the custom handling within the control.
> feat(tt-aug_2020): Relocate the source link from the group header to each list item

- src/AccessibilityInsights.SharedUx/SharedUx.csproj
- src/UITests/UITests.csproj
Pick up Axe.Windows 1.0.2, which fixes https://github.com/microsoft/axe-windows/issues/432
> chore: Bump Axe.Windows from 1.0.1 to 1.0.2

- src/AccessibilityInsights.Extensions.AzureDevOps/ConfigurationControl.xaml
- src/AccessibilityInsights.SharedUx/Resources/Dark/Brushes.xaml
- src/AccessibilityInsights.SharedUx/Resources/HighContrast/Brushes.xaml
- src/AccessibilityInsights.SharedUx/Resources/Light/Brushes.xaml
- src/AccessibilityInsights.SharedUx/Resources/Styles.xaml
Commit #921 addressed some HC issues in the ADO connection dialog, but missed the text colors for the disabled controls. This PR includes:
- Rename `ButtonDisabledBrush` to `ButtonDisabledFGBrush` to correctly reflect its usage, update its comment
- Move the behavior to set a grid opacity at 30% when disabled into the `gridPartialOpacityWhenDisabled` style
- Don't set `gridPartialOpacityWhenDisabled` on the TextBlock and Button controls, since HC modes define a color that is incompatible with the opacity
- Create 2 new styles (`tbPrimaryFGBrushWithDisabledFGBrush` and `tbButtonLinkFGBrushWithDisabledFGBrush`) to control the colors for the "Select your Azure Boards team" and "Refresh" text blocks, respectively.
> Note: After the PR has been created, certain checks will be kicked off. All …
> fix: Use correct HC colors for disabled text

- src/AccessibilityInsights.SharedUx/SharedUx.csproj
- src/UITests/UITests.csproj
Update Axe.Windows from version 1.0.2 to 1.0.3. This picks up the rule changes of replacing the *SpecialCharacters rules with *PrivateUnicodeCharacters rules, which are clearer and more actionable.
> chore: Bump axe.windows from 1.0.2 to 1.0.3

- src/AccessibilityInsights.SharedUx/Resources/Styles.xaml
The bottom and right border color on the delay timer edit control is failing to provide a contrast ratio of at least 3.0. This changes the style to explicitly set the border brush to the same value as the foreground and caret brush. This is the only control that currently uses this style, so the change is very scoped.
The screenshot shows unfocused colors with the pre-change visual on the left, the post-change visual on the rights. The contrast indicated is the contrast of the bottom and right edges of the edit (which are the edged that failed the contrast check). I also validated contrast when the control has the focus--21.0 in all HC modes. 7.3 in light mode, and 4.6 in dark mode.
- [n/s] Run the production version of Accessibility Insights for Windows against a version with changes.
> …
> fix: Specify explicit border color on timer delay edit

- src/AccessibilityInsights.SharedUx/Controls/EventConfigTabControl.xaml
- src/AccessibilityInsights.SharedUx/Controls/TestTabs/AutomatedChecksControl.xaml
- src/AccessibilityInsights.SharedUx/Dialogs/TextRangeFindDialog.xaml
- src/AccessibilityInsights.SharedUx/Resources/Styles.xaml
Default checkboxes are failing WCAG 2.1 color contrast requirements in High Contrast White mode. They're OK in other modes, but this change applies in all modes. These are the default colors from .NET, so I'll probably file an issue there, as well (they probably haven't yet picked up the latest WCAG requirements).
The workaround is to create a new style called `CheckBoxContrastingBorder` and use this as the base style for all checkboxes in the product. This includes:
- The first-boot telemetry permissions dialog
- The Welcome screen
- The configuration page for event listening
- The Automated checks results page
- The Text Range find dialog
I've sanity checked all of these and found no issues other than the checkbox is a little darker than it use to be in the light theme. Here's a …
> fix: Checkboxes fail color contrast in HC White

- src/AccessibilityInsights.SharedUx/Resources/Styles.xaml
- src/AccessibilityInsights/MainWindow.xaml
We have several cases where we have button that wraps a FabricIconControl. Even if the FabricIconControl is hover-aware, there's a range of mouse positions where IsMouseOver for the button is true, but IsMouseOver for the FabricIconControl is false, which causes us to fail color contrast. This change allows a FabricIconControl to be hover-aware for its button parent, so that we always have sufficient contrast.
Note that this fixes only the contrast issue of glyph color to button color--there may also be an issue of highlighted button color to background color that will be tracked separately.
Before change:
After change:
> fix: Change glyph color on button hover

- src/AccessibilityInsights.SharedUx/Resources/Dark/Brushes.xaml
- src/AccessibilityInsights.SharedUx/Resources/HighContrast/Brushes.xaml
- src/AccessibilityInsights.SharedUx/Resources/Light/Brushes.xaml
- src/AccessibilityInsights.SharedUx/Resources/Styles.xaml
- src/AccessibilityInsights/MainWindow.xaml
This PR does the following:
- In the list of brushes, rename `LightIconBrush` to a hopefully more descriptive `NavBarIconFGBrush`. This brush is the foreground brush of non-hovered icons in the nav bar
- Add a brush named `NavBarIconHoverFGBrush`. This is the foreground brush of hovered icons in the nav bar
- Add a brush named `NavBarButtonHoverBGBrush`. This is the background brush of nav bar buttons (fabric icons are transparent, so they appear with the button color as their background). This is mostly identical to `BlueButtonHoverBGBrush`, but I dropped the dark mode value into light mode value to provide adequate color contrast between hover and non-hover.
Here are gifs of the nav bars in all modes. The only expected change is in HC White. Some of the "Contrast" Tooltips appear …
> fix: Update nav bar hover colors

- src/AccessibilityInsights.SharedUx/Dialogs/StartUpModeControl.xaml
- src/AccessibilityInsights.SharedUx/Resources/Dark/Brushes.xaml
- src/AccessibilityInsights.SharedUx/Resources/HighContrast/Brushes.xaml
- src/AccessibilityInsights.SharedUx/Resources/Light/Brushes.xaml
- src/AccessibilityInsights.SharedUx/Resources/Styles.xaml
The Play button in the welcome screen always overlays a blue image, and the brush in HC White was not providing enough contrast. Since the image never changes, the brush can use a fixed value. This change hardcodes it to White (the color used in all modes but HC White) and updates the brush name and comment to better reflect what it's currently used for.
Screenshot showing both the icon in white and the shortcut sample button text (still black). Before this change, the same brush was used for both:
- [color only] Includes UI changes?
> fix: Use hardcoded white play button in welcome screen

- src/AccessibilityInsights.SharedUx/Controls/ScannerResultControl.xaml
- src/AccessibilityInsights.SharedUx/Resources/Dark/Brushes.xaml
- src/AccessibilityInsights.SharedUx/Resources/HighContrast/Brushes.xaml
Issue #843 calls out 2 places where colors are incorrect in dark mode. This fixes both.
The first problem is due to `SelectedFGTabBrush` being set to the wrong value, so we drew the text for the "Automated Checks tab" in the wrong color. This is the only place this value is used, so we can just change the color value without creating another brush. I discovered that HC Black and HC White modes are also broken, so I had to change brushes for both dark and HC modes. I've included screenshots of all 6 modes, just for completeness. In all cases, the old version is on the left, and the new version is on the right:
Mode | Screenshot
--- | ---
Light (no change) | ![image](https://user-images.githubusercontent.com/45672944/95272120-7027c000-07f4-11eb-8217-5e9638906f98.png)
Dark (fixed) | …
> fix: Some dark mode text has insufficient contrast

- src/AccessibilityInsights.SharedUx/Resources/Dark/Brushes.xaml
- src/AccessibilityInsights.SharedUx/Resources/HighContrast/Brushes.xaml
- src/AccessibilityInsights.SharedUx/Resources/Light/Brushes.xaml
- src/AccessibilityInsights.SharedUx/Resources/Styles.xaml
As called out in #842, the default link hover color fails color contrast requirements in dark mode. This PR adds the ability to override the link text and changes the color in dark mode. The link color in other modes is unchanged. Here's a GIF of the new link color in action:
- [style only] Includes UI changes?
> fix: Update Link color on hover (dark mode)

- src/AccessibilityInsights.SharedUx/Resources/Dark/Brushes.xaml
- src/AccessibilityInsights.SharedUx/Resources/HighContrast/Brushes.xaml
- src/AccessibilityInsights.SharedUx/Resources/Light/Brushes.xaml
- src/AccessibilityInsights.SharedUx/Resources/Styles.xaml
Tabs in test view have some issues in high contrast black and high contrast white (see #870). This does the following:
- Use the HC disabled text color if the tabs are not enabled
- Use the HighlightColor for the tab background if selected or hovered in HC
- Use the HighlightTextColor for tab foreground if selected or hovered in HC
- Use more descriptive names for the brushes that are unique to this view
- In the brushes.xaml files, put the brushes in a group to emphasize their relationships
Here's a screenshot of all 6 modes with the tabs disabled with this change:
Here's a collections of gifs showing the selected and hover behavior. 
GIF | Mode/comment
--- | ---
- [colors only] Includes UI changes?
> Note: After the PR has been created, certain checks will be kicked off. All of these …
> fix: Update high contrast colors of tabs in test view

- src/AccessibilityInsights.SharedUx/Resources/Dark/Brushes.xaml
- src/AccessibilityInsights.SharedUx/Resources/HighContrast/Brushes.xaml
- src/AccessibilityInsights.SharedUx/Resources/Light/Brushes.xaml
- src/AccessibilityInsights.SharedUx/Resources/Styles.xaml
In HC modes, hovering on the actions button sets the background to HighContrastColor without setting the foreground to HighContrastTextColor, which causes problems in HC White and HC Black modes. This PR adds an explicit foreground brush and sets it on hover. The brush color for Light and Dark mode are aligned with PrimaryFGBrush.
GIF | Mode
--- | ---
- [style only] Includes UI changes?
> fix: Use correct HC foreground color for Actions buttons

- src/AccessibilityInsights.SharedUx/Controls/SettingsTabs/ConnectionControl.xaml.cs
- src/AccessibilityInsights.SharedUx/Resources/Styles.xaml
Radio buttons for issue filing are dynamically created with a color from the theme that is in effect when the controls are created. As such, they're not responsive to theme changes that occur afterward. The solution is to assign a style instead of a color, and then use a theme-responsive color within the style. Since I need to specify the style from code, I chose a name that explicitly names it as a style, which is something that we don't do for styles loaded from XAML.
This GIF only shows changing between dark and light, but I tested changing between HC and non-HC, as well as between HC modes. They all transition as expected.
- [style only] Includes UI changes?
> fix: Use a style instead of a fixed color in issue filing radio buttons

- src/AccessibilityInsights.SharedUx/Resources/Styles.xaml
In HC Light and HC Dark, the Expand/Collapse icon in our TreeViews fails contrast when the item is selected. This PR addresses #860 (which calls out the UIA TreeView) as well as our other TreeViews, such as the Patterns tree. It sets the color of the expander to match the color of the other text and icons on selected items.
Screenshots in Light, Dark, HC Dark, HC White, HC 1, and HC 2:
> Fix: Use correct brush for TreeView Expand/Collapse icons when selected

- src/AccessibilityInsights.SharedUx/Resources/HighContrast/Brushes.xaml
- src/AccessibilityInsights.SharedUx/Resources/Styles.xaml
Addresses Focus indicator on 'selected' test in Fast Pass has insufficient contrast against its background #868. Currently, the focus indicator on a test tab header is the normal black or white outline, but the color of the selected tab can be close to black or white. We had a similar problem with our left nav bar buttons, so I used the same solution here. Now, when a test tab has focus, it gets an inner border with the opposite (black or white) color of the current focus indicator. This means that there will always be a black and white border to indicate focus, which will pass contrast requirements. Also, this active rectangle on the left side of the selected tab now has a better color for high contrast modes.
Screenshots in Light, Dark, HC Black, HC White, HC 1, and HC 2:
- [n/a] Run …
> fix: Improve contrast of test tab header focus indicator with inner border

- src/AccessibilityInsights.SharedUx/ActionViews/ReturnA11yElementsView.xaml
- src/AccessibilityInsights.SharedUx/Behaviors/DropDownButtonBehavior.cs
- src/AccessibilityInsights.SharedUx/Controls/ColorChooser.xaml
- src/AccessibilityInsights.SharedUx/Controls/EventConfigurationControl.xaml
- src/AccessibilityInsights.SharedUx/Controls/EventRecordControl.xaml
- src/AccessibilityInsights.SharedUx/Controls/HierarchyControl.xaml
- src/AccessibilityInsights.SharedUx/Controls/InspectTabsControl.xaml
- src/AccessibilityInsights.SharedUx/Controls/TestTabs/AutomatedChecksControl.xaml
- src/AccessibilityInsights.SharedUx/Controls/TextRangeControl.xaml
- src/AccessibilityInsights.SharedUx/Dialogs/ElementInfoDialog.xaml
- src/AccessibilityInsights.SharedUx/Resources/Styles.xaml
- src/AccessibilityInsights.SharedUx/Utilities/ContainedControlFinder.cs
- src/AccessibilityInsights/Modes/ConfigurationModeControl.xaml
This change fixes 3 types of issues (one reported, two not) associated with hover buttons with fabric icons, some of which also have pop-up context menus. The behavior of fixing them separately is bad (controls become invisible), so they're all in a single PR. I scanned the code for all instances and included them here.
Problem 1 (Reported): Buttons with pop-up context menus fail contrast requirements in HC White and HC Black modes once the user clicks on the button (the foreground color of the FabricIconControl doesn't get updated). This was reported in the events dialog, but it happens in several places. Root cause is that the foreground color of the FabricIconControl is never getting updated from its default color. Here's one example of the before and after using HC White:
Before | …
> fix issues with FabricIconControls on buttons

- src/AccessibilityInsights.SharedUx/Controls/EventConfigTabControl.xaml
- src/AccessibilityInsights.SharedUx/Controls/HierarchyControl.xaml
- src/AccessibilityInsights.SharedUx/Controls/PatternInfoControl.xaml
- src/AccessibilityInsights.SharedUx/Resources/Styles.xaml
As noted in #867, the event configuration page has issues in HC White and HC Black modes when an event or property is selected. The checkbox state always appears unchecked (because it's using the same foreground and background color), and the name of the event/property is drawn with a foreground color that isn't appropriate for the background color when selected.
The fix is as follows:
- Modify the `tviStandard` style to default to using PrimaryFGBrush as its foreground color. `tviStandard` already sets the correct colors when an item is selected.
- In the event configuration page, stop overriding the foreground color for the TextBlock, so it uses the values from `tviStandard`
- In the event configuration page, override the foreground color for the checkbox, so it always uses …
> fix: Event configuration is broken in HC Black & HC White

- src/AccessibilityInsights.SharedUx/Controls/PatternInfoControl.xaml
- src/AccessibilityInsights.SharedUx/Resources/Dark/Brushes.xaml
- src/AccessibilityInsights.SharedUx/Resources/HighContrast/Brushes.xaml
- src/AccessibilityInsights.SharedUx/Resources/Light/Brushes.xaml
- src/AccessibilityInsights.SharedUx/Resources/Styles.xaml
Issue #872 points out that the patterns actions buttons have no visual indication in HC modes that they're anything more than generic text. This PR adds a border in HC modes. The eagle-eyed observer might note that it also makes the buttons in non-HC modes a tiny bit taller and rounds the corners, both of which look better to my (potentially biased) eye. Happy to discuss alternatives here.
One potential oddity is that I'm using the button foreground color as the button's border color. That's to ensure that the button outline is still visible on mouse hover when the pattern is selected in the UI. You can observe this in the following GIFs (the `InvokePattern` is selected, the `LegacyIAccessiblePattern` is not):
Mode | GIF
--- | ---
Light | …
> fix: Make Action buttons more obvious in HC modes

- src/AccessibilityInsights.SharedUx/Resources/Styles.xaml
As called out in both #817 and #871, keyboard focus around the "Test element" and "More options" buttons of the hierarchy view is too hard to see in some High Contrast modes. These buttons float over a selected line, so their focus needs to stand out against the selected line color. This PR modifies the FocusVisualStyle so that:
1. It's drawn using the same brush as the text on the selected line
2. It's drawn inside the selected line
3. It's drawn with a thicker pen
After some discussion, we decided to follow the same pattern for non-HC modes, as well, since it helps the focus to stand out a lot better than the old way.
Here's the current behavior in Light and HC White modes, just as a reference:
Mode | GIF
--- | ---
Light | ![871-current-light](https://user-images.githubusercontent.com/45 …
> fix (HC): Change focus styling for buttons that superimpose a selected line

- src/AccessibilityInsights.SharedUx/Resources/HighContrast/Brushes.xaml
There is no definition for `UnselectedInspectTabBrush` in HC modes, meaning that a null (transparent) brush gets used. This brush sets the background for the Inspect Tabs control, and when viewing the UIA tree after running a test, the breadcrumbs text can (depending on the splitter position) collide with the text control. This PR simply defines `UnselectedInspectTabBrush` in HC modes, using SystemColor.ControlColor--this is the same color used as the background in all HC modes.
Screenshots--the top of the screenshot shows the updated behavior, the bottom shows the current production behavior, where the breadcrumbs overlap the tabs)
Mode | Screenshot
--- | ---
Light (unchanged) | ![Light](https://user-images.githubusercontent.com/45672944/96638209-a1b08900-12d4-11eb-853d-1ed292898e6c.PNG) …
> fix(HC): Prevent breadcrumbs from overlapping tabs in HC modes

- src/AccessibilityInsights.SharedUx/Controls/TestTabs/ColorContrast.xaml.cs
- src/AccessibilityInsights/Modes/CCAModeControl.xaml.cs
The automatic color contrast code is heuristic-based, and can't always guess at a color pair. When this happens, we dereference a null object, which triggers a NullReferenceException. This has the following effects:
1. If running under the debugger, the NullReferenceException causes a (very annoying) DebugBreak
2. The error handler handles the exception and sets the highlighter to "Unable to detect colors!", but leaves the stale data in the dialog.
This PR does 4 things:
1. Instead of throwing a NullReferenceException, it throws an InvalidOperationException. This avoids the automatic break in the debugger
2. In the exception handler, it calls the ClearUI method to flush the stale color and confidence information
3. The ClearUI method now clears the stale confidence information
4. Fixes a …
> fix: Improve CCA handling when we can't get a color pair

- src/AccessibilityInsights.SharedUx/Resources/Dark/Brushes.xaml
- src/AccessibilityInsights.SharedUx/Resources/HighContrast/Brushes.xaml
- src/AccessibilityInsights.SharedUx/Resources/Light/Brushes.xaml
- src/AccessibilityInsights.SharedUx/Resources/Styles.xaml
As reported in #866, the focus rectangle on the tabs in the inspect view is really hard to see in HC modes, especially HC White. This PR changes the styling of the tabs so that they draw a border inside the focus rectangle. The color is chosen to match the tab background color in Light and Dark modes, but to contrast against it in HC modes. This makes the focus rectangle stand out a lot more clearly in HC modes.
There's on minor side effect--when the focus moves to the tab, the border causes a very small shift to the text in the tab, so there's a small visual "jump" that isn't there in the current code. I mention this only to call out that it's there, but I'm not proposing that we try to fix it--at least not unless we get complaints about it.
Here are the GIF's showing before and after in …
> fix(HC): Add a contrasting border around tab icons when they're focused

- src/AccessibilityInsights.SharedUx/Controls/TestTabs/AutomatedChecksControl.xaml
If you resize the app when in automated checks view, the descriptive text at the top of the view gets clipped as the window gets narrower. This is because we're using a Grid without allowing the contents to span multiple columns. 
Before: 
After:
- [style only] Includes UI changes?
> fix: Don't clip descriptive text unnecessarily

- src/AccessibilityInsights.SharedUx/Controls/ColorChooser.xaml
- src/AccessibilityInsights.SharedUx/Controls/ColorPicker/ColorPickerControl.xaml
- src/AccessibilityInsights.SharedUx/Controls/TestTabs/ColorContrast.xaml
- src/AccessibilityInsights.SharedUx/Resources/Dark/Brushes.xaml
- src/AccessibilityInsights.SharedUx/Resources/HighContrast/Brushes.xaml
- src/AccessibilityInsights.SharedUx/Resources/Light/Brushes.xaml
- src/AccessibilityInsights.SharedUx/Resources/Styles.xaml
Issue #874 calls out some non-text color contrast issues in the color contrast analyzer. This fixes _most_ of them--we'll create a new issue to track the focus color of the edit control, as this is part of the edit control and occurs in multiple places. This PR does the following:
1. Use PrimaryBGBrush in the color picker (not called out in the bug, but needed to free up GreyBackgroundBrush)
2. Rename GreyBackgroundBrush to HorizontalRuleBGBrush (used to draw horizontal rules in color contrast dialog), specify a value (SystemColors.ControlDarkColor) that has adequate contrast (>= 3.0) in all HC modes.
3. Add ColorChooserBorderBrush (will be used for the borders of the color chooser (combobox + edit)
4. Use Replace BorderBrush with ColorChooserBorderBrush for the color chooser combobox & …
> fix(HC): Fix non-text contrast issues in Color Contrast analyzer

- src/AccessibilityInsights.SharedUx/SharedUx.csproj
- src/UITests/UITests.csproj
Grab the latest version of Axe.Windows. This will fix #974  
> chore: Bump Axe.Windows to version 1.0.4

- src/AccessibilityInsights.SetupLibrary/TrustVerifier.cs
- src/AccessibilityInsights.VersionSwitcher/InstallationEngine.cs
Issue #731 came from a previous security review and was intended to prevent us from launching an MSI that we weren't sure that we trusted. We already verify that the MSI is authenticode signed and that the signing chain is valid. This change adds a check based on the organization that issued the certificate used to sign the MSI. I've confirmed that the same issuer is reported in current Production and Canary builds. 
This adds no unit tests to avoid adding binary files to the repo. We could definitely change that, if desired. 
This approach is future-proofed against _anticipated_ changes to the issuer of the signing certificate. Should that happen, we'd just add another entry in `TrustedCertIssuerEndings` some time before the change, and the transition from old to new will be seamless. We …
> fix: Validate MSI signer before installing it

- src/AccessibilityInsights.SharedUx/Dialogs/HotkeyGrabDialog.xaml
The HotkeyGrabDialog has a few issues:
- It always uses the default background color, which is a problem in dark mode, since it's putting white text on a white background
- It has no border, which is confusing on a busy screen
- The TextBlock that displays the shortcut gets truncated in HC modes
Changes:
- Specify a palette-keyed background color, border color, and a border thickness (even in non-HC modes)
- Make the TextBlock taller (even in non-HC modes)
Mode | Old behavior | New behavior
Light | ![image](https://user-images.githubusercontent.com/45672944/97620014-3191b980-19de-11eb-8010-702c629917e5.png) | ![image](https://user-images.githubusercontent.com/45672944/97620069-42dac600-19de-11eb-9972-701197b6b427.png)
Dark | …
> fix: Update visuals in Hot key grabber dialog

- build/NetFrameworkRelease.targets
- src/AccessibilityInsights.Win32/Properties/AssemblyInfo.cs
- src/AccessibilityInsights/Properties/AssemblyInfo.cs
Based on recommendation from https://docs.microsoft.com/en-us/visualstudio/code-quality/migrate-from-fxcop-analyzers-to-net-analyzers?view=vs-2019
Also removed some disabled warnings which appear to no longer be necessary after the change.
> Chore: Switch from using Microsoft.CodeAnalysis.FxCopAnalyzers to Microsoft.CodeAnalysis.NetAnalyzers

- src/AccessibilityInsights.SharedUx/Resources/Dark/Brushes.xaml
- src/AccessibilityInsights.SharedUx/Resources/HighContrast/Brushes.xaml
- src/AccessibilityInsights.SharedUx/Resources/Light/Brushes.xaml
- src/AccessibilityInsights.SharedUx/Resources/Styles.xaml
The color picker creates a custom combobox, but the colors used in the toggle button fail color contrast requirements in multiple modes (tracked in #875). This change adds 2 new brushes (one background, one foreground) that get used for the toggle button.
Some comments:
1. There's a small flash as the mouse cursor moves across the boundary inside the combobox. This is existing behavior, and I wasn't able to find a nice way to address it in the scope of this change.
2. I tried to use a new style for the fabricIcon (along the lines of `hoverAwareFabricIconOnButtonParent`, but ran into problems trying to get this to work in the context of the combobox because I wasn't able to align the `IsMouseOver` property of the button and the icon. I ended up just setting the properties within the …
> fix(hc): Fix contrast issues in color picker toggle button

- src/AccessibilityInsights.SharedUx/Dialogs/GlobalEyedropperWindow.xaml.cs
The color contrast eyedropper is intended to use the mouse to get "close" to a point, then you can use the keyboard to nudge to the exact position desired. Unfortunately, there's no keyboard-only way to travel quickly and get "close". This PR adds a way to move quickly by holding the ctrl key while pressing the arrows.
Without a mouse, the default mouse cursor will be the center of the primary screen. AIWin updates this position, but these videos both assume it's in the default location. The objective is to get to the center of the 't' in "switch".
Old navigation
New navigation
- [?] Includes UI changes?
> Note: After the …
> fix: Improve keyboard only nav experience in color contrast

- build/NetFrameworkRelease.targets
- build/signedbuild.yml
We have been unnecessarily including a PackageReference to the BinSkim tools. BinSkim 1.7.1 has a breaking change that prevents us from including the PackageReference, so we're removing the reference. I'll kick off a signed build after this merges to ensure that the BinSkim build task is working correctly without the PackageReference.
> chore: Remove BinSkim package reference

- src/AccessibilityInsights.SharedUx/Settings/ConfigurationManager.cs
As called out in #1009, the EventConfig.json file should be stored with the other config files, instead of being stored with the user's documents. This is a 2 line fix, but it will have the side effect of "losing" user event configs on upgrade. Since this impacts a very small set of users, this PR makes no effort to migrate existing data. That doesn't mean that we can't migrate the data, only that it's not in this PR.
> fix: Change where eventconfig.json is stored

- src/AccessibilityInsights.VersionSwitcher/EventLogger.cs
The VersionSwitcher writes is progress to the Windows Event Log, but it records that progress from the wrong source. The intended source is AccessibilityInsights.VersionSwitcher, but when the code was first written, the string used was ApplicationInsights.VersionSwitcher. 
Here's the old (incorrect) output in CSV format:
```
Level	Date and Time	Source	Event ID	Task Category
Information	1/5/2021 7:55:23 AM	ApplicationInsights.VersionSwitcher	0	None	Completed Installation
```
Here's the new (corrected) output in CSV format:
```
Level	Date and Time	Source	Event ID	Task Category
Information	1/5/2021 10:56:32 AM	AccessibilityInsights.VersionSwitcher	0	None	Completed Installation
```
- [n/a] Run the …
> fix: Correct wrong name when logging to event viewer

- Channels/Insider/release_info.json
- Channels/Insider/release_notes.md
- Channels/Production/release_info.json
- Channels/Production/release_notes.md
This updates the Insider & Production channels to build 1.1.1467.01. This change moves us from Axe.Windows 1.0.3 to Axe.Windows 1.0.5, so the release notes changes reflect changes from 2 releases of Axe.Windows.
> chore: Release 1.1.1467.01 to Insider and Production

- src/AccessibilityInsights.SharedUxTests/Settings/ConfigurationModelTests.cs
Our PR tests currently produce the following exception on every execution:
```
Class Cleanup method ConfigurationModelTests.ClassCleanup failed. Error Message: System.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\a\_temp\TestResults\Deploy_VssAdministrator 2021-01-11 13_22_45\user'.. Stack Trace:     at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
at System.IO.Directory.Delete(String path)
at AccessibilityInsights.SharedUxTests.Settings.ConfigurationModelTests.ClassCleanup() in D:\a\1\s\src\AccessibilityInsights.SharedUxTests\Settings\ConfigurationModelTests.cs:line 37
```
This isn't a fatal error, but it's a distraction when trying to find …
> fix: Remove spurious failure message in unit tests

- src/AccessibilityInsights.SharedUx/SharedUx.csproj
- src/UITests/UITests.csproj
Bump Axe.Windows from 1.0.5 to 1.0.6. This fixes issue #1017 and removes build warnings that were a side effect of Axe.Windows 1.0.5.
> chore(deps): Bump Axe.Windows from 1.0.5 to 1.0.6

- build/build-and-unit-tests.yml
- build/signedbuild.yml
- src/AccessibilityInsights.CustomActions/ConfigFileCleaner.cs
- src/AccessibilityInsights.CustomActions/CustomAction.config
- src/AccessibilityInsights.CustomActions/CustomActions.csproj
- src/AccessibilityInsights.CustomActions/ISystemShim.cs
- src/AccessibilityInsights.CustomActions/Properties/AssemblyInfo.cs
- src/AccessibilityInsights.CustomActions/SystemShim.cs
- src/AccessibilityInsights.CustomActionsUnitTests/ConfigFileCleanerUnitTests.cs
- src/AccessibilityInsights.CustomActionsUnitTests/CustomActionsUnitTests.csproj
- src/AccessibilityInsights.sln
- src/MSI/MSI.wixproj
- src/MSI/Product.wxs
To fix #1007, we've chosen to use a custom action per the following spec:
1. It is invoked only on uninstall
2. When invoked, it checks to see if a process named AccessibilityInsights.VersionSwitcher.exe is currently running
3. If AccessibilityInsights.VersionSwitcher.exe is not running, the custom action deletes all files in the configuration directory (ignoring subdirectories)
Ran full E2E tests using actual MSI files in the following scenarios (config files exist at the beginning of each scenario):
Scenario | Result
--- | ---
Install | Config files are preserved
Upgrade by manually running MSI (no VersionSwitcher) | Config files are preserved
Uninstall MSI while VersionSwitcher is running | Config files are preserved
Uninstall MSI while VersionSwitcher is not running | Config files are …
> fix: Use a custom action to delete user config files on uninstall

- src/AccessibilityInsights.SharedUx/Dialogs/GlobalEyedropperWindow.xaml.cs
Issue #951 calls out that the color picker control's memory footprint is directly linked to the logical size of the screen, so there's a potential to use a lot of memory if the logical size is large. This PR doesn't fundamentally change the approach, but it specifies a 24 bit bitmap format instead of a 32 bit bitmap format. Intuitively, that should reduce our memory footprint by about 25%. I tested the current bits on my machine and found that the working set increased by about 120KB each time I clicked on the color picker. With the change, the working set increased by about 90KB, which is consistent with the expected 25% reduction.
The color contrast [algorithm](https://github.com/microsoft/accessibility-insights-windows/blob/master/src/AccessibilityInsights.SharedUx/ViewModels/ColorContr …
> fix: Reduce memory usage for eyedropper control

- src/AccessibilityInsights.Extensions.GitHub/Extensions.GitHub.csproj
- src/AccessibilityInsights.Extensions.Telemetry/Extensions.Telemetry.csproj
This PR removes some "residual" references to System.Drawing.Common. These are not needed and even led to a hard-to-debug issue in UITests when dependabot tried to update these references for us (reference PR #1042). The best answer seems to be to simply remove them.
Avoid noise, good hygiene
> chore: Remove direct references to System.Drawing.Common

- src/AccessibilityInsights.SharedUx/Controls/TestTabs/TabStopControl.xaml
- src/AccessibilityInsights.SharedUx/Properties/Resources.Designer.cs
- src/AccessibilityInsights.SharedUx/Properties/Resources.resx
Currently, tab stops has a help (i) icon that is a hyperlink. It does not show a tooltip on keyboard focus. This PR replaces that icon with text to avoid the need for a tooltip.
Addresses an accessibility issue
I tried to adapt `KeyboardToolTipButtonBehavior` to function on hyperlinks. Unfortunately, `Hyperlink` is not a `FrameworkElement` and thus cannot be set as a `ToolTip`'s `PlacementTarget` and does not prove screen location information. This makes it very difficult to position a keyboard focus triggered `ToolTip` on the screen for a `Hyperlink`. As such, this PR's approach was selected instead.
Screenshots, before on top, after below:
Dark Mode:
HC White:
HC Black:
> Note: After the PR has been created, certain checks …
> fix: Replace tab stops help icon with text

- build/NetFrameworkRelease.targets
VisualStudio 16.9.0 recently released, and builds with the new version are suddenly broken due to 18 new warnings that were not occurring before. We've reached out to the Visual Studio team to understand why VS suddenly decided to raise these warnings, but the quickest mitigation to get everyone unstuck is to suppress these warnings globally. 
Allow the team to develop with VS 16.9.0
This is a temporary mitigation to get unstuck. It comes with the understanding that we'll actually evaluate and maybe fix these issues going forward.
- [n/a] Run the …
> fix: Suppress warnings that VS 16.9.0 is suddenly flagging

- build/NetFrameworkRelease.targets
- src/AccessibilityInsights.SharedUx/Controls/SettingsTabs/ConnectionControl.xaml.cs
- src/AccessibilityInsights.SharedUx/FileIssue/IssueReporter.cs
- src/AccessibilityInsights.SharedUx/Highlighting/HollowHighlightDriver.cs
- src/AccessibilityInsights.SharedUx/Highlighting/Win32SnapshotButton.cs
- src/AccessibilityInsights.Win32/Win32Structures.cs
In #1054, we suppressed CS8073 warnings. This benign warning indicates that a conditional has a clause that is always either true or false. The "change nothing" change is just to remove the clause. I went a bit beyond that and tried to capture the _intent_ of the check, as opposed to the actual effect. There are 3 basic cases that are addressed here:
1. Guid is a value type, not a reference type. It will never be null, but its default value is Guid.Empty. I changed checks of Guid == null to Guid.IsEmpty
2. Rectangle is a value type, not a reference type. It will never be null, but its default value is (0,0,0,0) . I changed checks of Rectangle == null to Rectangle.IsEmpty
3. IntPtr is a value type, not a reference type. It will never be null, but its default value is IntPtr.Zero. I changed …
> fix: Address code that triggers CS8073 warnings

- build/NetFrameworkRelease.targets
- src/AccessibilityInsights.Extensions.GitHub/ConfigurationModelControl.xaml.cs
In #1054, we suppress CA2019 warnings. We only have one of these, and it's a trivial fix--make a method private instead of public, when it's only called from within the class. To be honest, I'm somewhat impressed that we don't have more of these in the codebase! 😉 
I confirmed that the Save button in the connection config page still updates as expected.
> Note: After the PR has been created, …
> Fix: Address code that triggers CA2109 warning

- build/NetFrameworkRelease.targets
- src/AccessibilityInsights.SharedUx/Dialogs/GlobalEyedropperWindow.xaml.cs
In #1054, we suppressed CA1822 warnings. We only have one of these, and it's a trivial fix--remove an unused parameter.
I confirmed that the keyboard movement of the color contrast eyedropper still works as expected.
> fix: Address code that triggers CA1801 warning

- build/NetFrameworkRelease.targets
- src/AccessibilityInsights.CommonUxComponents/Controls/FabricIconControl.xaml.cs
- src/AccessibilityInsights.Win32/Win32Enums.cs
In #1054, we suppressed CA171 warnings. We only just two of these, and since the names both reflect external values, it makes sense to suppress the warning, but to suppress close to the code instead of globally.
> fix: Address issues triggering CA1711 warnings

- build/NetFrameworkRelease.targets
- src/AccessibilityInsights.Extensions.Telemetry/AITelemetry.cs
- src/AccessibilityInsights/MainWindow.xaml.cs
In #1054, we suppressed CA1725 warnings. We have just a few of these, and it's a trivial fix--rename a parameter in the implementation to match the parameter in the interface. Changes were done by the IDE.
> fix: Address code that triggers CA1725 warnings

- build/NetFrameworkRelease.targets
- src/AccessibilityInsights.SharedUx/Dialogs/GlobalEyedropperWindow.xaml.cs
In #1054, we suppressed CA1822 warnings. We only have one of these, and it's a trivial fix--make a method static. To be honest, I'm somewhat impressed that we don't have more of these in the codebase! 😉 
I confirmed that the keyboard movement of the color contrast eyedropper still works as expected.
> Note: After the PR has been created, certain checks will be kicked off. All of these checks must …
> fix: Address code that triggers CA1822 warning

- build/NetFrameworkRelease.targets
- src/AccessibilityInsights.Extensions.AzureDevOps/ConnectionInfo.cs
- src/AccessibilityInsights.Extensions.AzureDevOps/Models/AdoTeam.cs
- src/AccessibilityInsights.Extensions/Container.cs
- src/AccessibilityInsights.SharedUx/Controls/EventConfigurationControl.xaml.cs
- src/AccessibilityInsights.SharedUx/FileIssue/IssueReporterManager.cs
- src/AccessibilityInsights.SharedUx/Highlighting/TextTip.cs
- src/AccessibilityInsights/MainWindowHelpers/StateMachine.cs
In #1054, we suppressed CA1508 warnings, which deal with redundant code. Looking through these, some are legit but many of them are false positives. Details are called out in the comments.
> fix: Address code that triggers CA1508 warnings

- build/NetFrameworkRelease.targets
- src/AccessibilityInsights.CustomActions/ConfigFileCleaner.cs
In #1054, we suppressed CA1031 warnings. We only have one of these, and we just wrap it in an suppression like we do in other places in the code.
> fix: Address code that triggers CA1031 warning

- build/NetFrameworkRelease.targets
- src/AccessibilityInsights.Win32/Win32Enums.cs
In #1054, we suppressed [CA1027](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1027) warnings, which are purely stylistic and don't alter the generated code in any way. I had to suppress the warning in a couple of cases where the rule is overzealous and incorrectly wants non-flag enums to be attributed as flags.
> Note: After the PR has been created, certain …
> fix: Address code that triggers CA1027 warnings

- docs/FAQ.md
- docs/TelemetryDetails.md
- docs/TelemetryOverview.md
So far, our telemetry docs have lived in OneNote, which is not directly bound to the code and has accessibility issues due to the use of tables. This migrates the documentation into the repo, in markdown format.
Improve accessibility and visibility of telemetry documentation
> chore: Revise telemetry documentation

- build/NetFrameworkRelease.targets
- src/AccessibilityInsights.Extensions.GitHub/IssueReporter.cs
- src/AccessibilityInsights.SharedUx/Controls/HierarchyControl.xaml.cs
- src/AccessibilityInsights.SharedUx/Controls/SettingsTabs/ConnectionControl.xaml.cs
- src/AccessibilityInsights.SharedUx/Controls/TestTabs/ColorContrast.xaml.cs
- src/AccessibilityInsights.SharedUx/Controls/TestTabs/TabStopControl.xaml.cs
- src/AccessibilityInsights.SharedUx/FileIssue/IssueReporter.cs
- src/AccessibilityInsights.SharedUx/FileIssue/IssueReporterManager.cs
- src/AccessibilityInsights.SharedUx/Highlighting/ClearOverlayDriver.cs
- src/AccessibilityInsights.SharedUx/Highlighting/ImageOverlayDriver.cs
- src/AccessibilityInsights.SharedUx/Misc/VersionTools.cs
- src/AccessibilityInsights.SharedUx/Settings/Layout.cs
- src/AccessibilityInsights.SharedUx/ViewModels/AboutTabViewModel.cs
- src/AccessibilityInsights.SharedUxTests/FileIssue/IssueReporterManagerTests.cs
- src/AccessibilityInsights/Modes/CCAModeControl.xaml.cs
- src/AccessibilityInsights/Modes/LiveModeControl.xaml.cs
- src/AccessibilityInsights/Modes/SnapshotModeControl.xaml.cs
In #1054, we suppressed [CA1024](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1024) warnings, which nudge users to use properties where practical. The analyzer isn't perfect, and some cases that shouldn't be properties were manually suppressed. It did, however, identify a few places where properties were appropriate. I needed to do some in-class renaming to have an intuitive property name, but it's pretty simple to follow the process if you do review each commit--look for commits prefixed **phase 1**, **phase 2**, etc.
- …
> fix: Address code that triggers CA1024 warnings

- src/AccessibilityInsights.Win32/Win32Enums.cs
#1063 added `[FlagsAttribute]` to some enums. It's better to just use the simpler form of `[Flags]`.
> chore: Simplify Flags attribution

- src/AccessibilityInsights.SharedUx/Controls/CustomControls/CustomGridViewColumn.xaml
- src/AccessibilityInsights.SharedUx/Controls/CustomControls/CustomGridViewColumn.xaml.cs
Currently, our properties table column headers are visible and directly accessible via assistive technology as `TextBlock` elements. Unfortunately, the header elements exposed by the table patterns are not those `TextBlock` elements and do not have accessible names set. This PR addresses the issue by setting `AutomationProperties.Name` on those header elements to the same value has the text displayed.
Fixes an accessibility issue.
I tried a few different ways to do this without success, including setting the Header property on the table directly, setting `LabeledBy` on the header to the visible text element, and changing the TextBlock we use to render the text to be a Label. I bet there are other ways to achieve the desired behavior, but this was simple and successful so I stopped …
> fix: Set automation name on CustomGridViewColumn headers

- build/NetFrameworkAll.targets
- build/NetFrameworkRelease.targets
#1065 added the CLSCompliant attribute to all assemblies, including test assemblies. Test assemblies don't need this since we don't run the analyzers on them. This change simply reduces the scope such that the CLSCompliant attribute gets set only for released assemblies.
> chore: Limit CLSCompliant attribute to released files

- src/AccessibilityInsights.SharedUx/Controls/PatternInfoControl.xaml.cs
- src/AccessibilityInsights.SharedUx/Settings/ConfigurationManager.cs
- src/AccessibilityInsights.SharedUx/Settings/ConfigurationModel.cs
- src/AccessibilityInsights.SharedUx/Settings/PropertySettings.cs
- src/AccessibilityInsights.SharedUxTests/Settings/ConfigurationModelTests.cs
While addressing some analyzer issues in Axe.Windows, I realized that the following methods (and their backing code) in https://github.com/microsoft/axe-windows/blob/main/src/Desktop/UIAutomation/DesktopElementHelper.cs are not used anywhere in Axe.Windows, and should be migrated into AIWin:
`SetCorePropertiesList`
`GetCorePropertiesList`
`GetDefaultCoreProperties`
After talking with @jalkire, we've chosen the following plan of action:
1. Give AIWin its own implementation of this functionality (this PR)
2. Remove the code from Axe.Windows (https://github.com/microsoft/axe-windows/pull/550). 
I've tested the changes locally and we seem to have parity with the old code, including resetting to the default set of properties if the user happens to remove all properties from the config (it may …
> chore: Move property management into AIWin (from Axe.Windows)

- src/AccessibilityInsights.SharedUx/Dialogs/TextRangeFindDialog.xaml
- src/AccessibilityInsights.SharedUx/Resources/Dark/Brushes.xaml
- src/AccessibilityInsights.SharedUx/Resources/HighContrast/Brushes.xaml
- src/AccessibilityInsights.SharedUx/Resources/Light/Brushes.xaml
- src/AccessibilityInsights.SharedUx/Resources/Styles.xaml
In #1085, the "Ignore case" checkbox in the Find Text dialog has a disappearing border due to overtheming because this dialog has no dark mode theme. This PR creates and uses a brush that is fully themed in HC modes, but retains the light mode border color in dark mode.
Tested Light mode and HC modes to confirm that they're not modified. Here are the screenshots in Dark mode:
State | Image
--- | ---
Unchecked without hover | ![image](https://user-images.githubusercontent.com/45672944/111709734-6bd0eb80-8805-11eb-93d6-d93e0d447237.png)
Unchecked with hover | ![image](https://user-images.githubusercontent.com/45672944/111709828-a5095b80-8805-11eb-9b6e-3527901da81d.png)
Checked with hover | ![image](https://user-images.githubusercontent.com/45672944/111709763-80ad7f00-8805-11eb-92bd-37b32532d …
> fix: Correct dark mode checkbox in find text dialog

- docs/TelemetryDetails.md
Add some more details to the docs about UIFramework identifiers, based on what's actually in the pipeline. This replaces several places where the previous version just said "Undetermined"
Desire to have complete docs
> chore: Improve UIFramework identifiers documentation (telemetry)

- .github/ISSUE_TEMPLATE/bug_report.md
Often we need to transfer issue reports from AI-Windows to Axe.Windows because the questions are rule-related. This updates the issue template to encourage ruleset questions should go to Axe.Windows.
> chore: mention that ruleset bugs go to axe.windows

- src/AccessibilityInsights.SharedUx/Controls/SettingsTabs/ApplicationSettingsControl.xaml
- src/AccessibilityInsights.SharedUx/Properties/Resources.Designer.cs
- src/AccessibilityInsights.SharedUx/Properties/Resources.resx
In a recent accessibility pass, it was pointed out that our accessible name on a label could be improved. Upon further review, we concluded that the display name could also be improved.
Old/New | Visual | NVDA
Old | ![image](https://user-images.githubusercontent.com/45672944/117069681-a45b5480-ace1-11eb-8c89-12b223f389f1.png) | Set delay in MS edit 100
New | ![image](https://user-images.githubusercontent.com/45672944/117069838-d4a2f300-ace1-11eb-9cfd-77be434aa69c.png) | Set delay in milliseconds edit 100
Address https://mseng.visualstudio.com/1ES/_workitems/edit/1750054
> fix: Use "milliseconds" instead of "ms" for label of mouse hover delay

- Channels/Insider/release_info.json
- Channels/Insider/release_notes.md
- ReadME.md
Release 1.1.1562.02 to insider, which has identical behavior to https://github.com/Microsoft/accessibility-insights-windows/releases/tag/v1.1.1562.01
We made some changes to the release promotion pipeline and would like to validate it. Pushing to insider since it's mainly for just our team. We don't intend to promote to production afterwards.
> chore: release 1.1.1562.02 to insider (validating release promotion pipeline, no behavior changes)

- src/AccessibilityInsights.SharedUx/Highlighting/HollowHighlightDriver.cs
This PR fixes stale tooltip updates described in 1123.
It also suppresses an instance of CA1062 after the refactor - I think the warning is a false positive because `element != null && !element.BoundingRectangle.IsEmpty;` should short-circuit if `element` is null. Let me know if I'm mistaken or there's a better way to match with the rule.
addresses #1123 
This fix works because we move the `IsVisible` setter after `Highlighter.SetText`.
The issue in 1123 occurs because:
- The TextTip text is drawn when [`WndProc`](https://github.com/microsoft/accessibility-insights-windows/blob/main/src/AccessibilityInsights.SharedUx/Highlighting/TextTip.cs#L364) is triggered with `WM_ERASEBKGND`
- `WndProc` is triggered if we explicitly call [`InvalidateRect`](https://docs.microsoft.com/en-us/windows/win3 …
> fix: ensure Tooltip stays up to date with highlighted element

- src/AccessibilityInsights.SharedUx/ActionViews/GeneralActionView.xaml
- src/AccessibilityInsights.SharedUx/ActionViews/ReturnA11yElementsView.xaml
- src/AccessibilityInsights.SharedUx/ActionViews/TextRangeActionView.xaml
- src/AccessibilityInsights.SharedUx/Controls/DisplayCountControl.xaml
- src/AccessibilityInsights.SharedUx/Controls/EventRecordControl.xaml
- src/AccessibilityInsights.SharedUx/Controls/HierarchyControl.xaml
- src/AccessibilityInsights.SharedUx/Controls/ScannerResultControl.xaml
- src/AccessibilityInsights.SharedUx/Controls/SettingsTabs/ApplicationSettingsControl.xaml
- src/AccessibilityInsights.SharedUx/Controls/SettingsTabs/ConnectionControl.xaml
- src/AccessibilityInsights.SharedUx/Controls/TestTabs/AutomatedChecksControl.xaml
- src/AccessibilityInsights.SharedUx/Controls/TestTabs/TabStopControl.xaml
- src/AccessibilityInsights.SharedUx/Controls/TextRangeControl.xaml
- src/AccessibilityInsights.SharedUx/Dialogs/MoveTextRangeDialog.xaml
- src/AccessibilityInsights.SharedUx/Dialogs/StartUpModeControl.xaml
- src/AccessibilityInsights.SharedUx/Properties/Resources.Designer.cs
- src/AccessibilityInsights.SharedUx/Properties/Resources.resx
- src/AccessibilityInsights/MainWindow.xaml
- src/AccessibilityInsights/Modes/LiveModeControl.xaml
- src/AccessibilityInsights/Modes/SnapshotModeControl.xaml.cs
- src/AccessibilityInsights/Modes/TestModeControl.xaml
- src/AccessibilityInsights/Properties/Resources.Designer.cs
- src/AccessibilityInsights/Properties/Resources.resx
Moves strings/text to resources files.
Compliance feature work.
> feat(compliance-may21): move text/content strings to resources files

- src/AccessibilityInsights.Extensions.AzureDevOps/Extensions.AzureDevOps.csproj
These 4 IdentityModel packages are codependent, but dependabot was trying to update them independently. This PR supersedes the 4 separate dependabot PRs to update these packages atomically.
* https://github.com/microsoft/accessibility-insights-windows/pull/1132
* https://github.com/microsoft/accessibility-insights-windows/pull/1131
* https://github.com/microsoft/accessibility-insights-windows/pull/1130
* https://github.com/microsoft/accessibility-insights-windows/pull/1129
Keep deps up to date
n/a
- [n/a] Run the production version of Accessibility Insights …
> Bump related IdentityModel packages to 6.11.1

- src/AccessibilityInsights.SharedUx/ViewModels/BaseActionViewModel.cs
Axe.Windows 1.0.7 changed a couple of return types from `List` to `IList`, but the code that maps the return type to a view didn't get updated. Issue #1138 was a direct result of that oversight.
Address #1138, fix regression
It occurs to me that we might consider some E2E tests that exercise patterns, but that's out of scope for this change.
- [fixes regression] Includes UI changes?
> fix: Update pattern content to reflect interface changes

- src/AccessibilityInsights.SharedUx/Properties/Resources.Designer.cs
- src/AccessibilityInsights.SharedUx/Properties/Resources.resx
The SharedUx assembly has several strings that have been either removed completely or migrated into other assemblies, but the string resources never got removed. We noticed a few of these while working on #1126 and #1127, but deferred the cleanup until a later change. This PR is intentionally broken up into one change per resource, if that makes it simpler to review.
Remove unused stuff
I found some misspellings and strings with awkward names, but it would be cleaner to remove the chaff before trying to change anything else.
> Note: …
> chore: Remove unused resource strings from SharedUx assembly

- src/AccessibilityInsights.SharedUx/SharedUx.csproj
- src/UITests/UITests.csproj
Update to the newest release of Axe.Windows (1.0.9)
Unblock work on adding live support for custom UIA properties
- [n/a] Does this address an existing issue?
> chore: Bump Axe.Windows from 1.0.8 to 1.0.9

- src/AccessibilityInsights/MainWindowHelpers/Initialize.cs
Initial support for displaying custom UI Automation properties in live mode.
Part of custom UIA extensions (internal access required to view).
Blocked by upgrade to Axe.Windows v1.0.10.
> feat(custom-uia): Initial support for live mode.

- src/AccessibilityInsights.SharedUx/Controls/PropertyInfoControl.xaml
Fix styling details that were missed on the properties search dialog. This includes setting the foreground and caret colors, as well as making the containing control tall enough to not clip the top part of the focus rectangle.
GIF wall with fix in place (Note that the blue highlight in HC2 is just because I happened to have that item selected and is unrelated to the change):
Mode | GIF
--- | ---
Light | ![search-light](https://user-images.githubusercontent.com/45672944/125844294-860b8d2f-7b2a-4c1a-9848-064bc9561a62.gif)
Dark | ![search-dark](https://user-images.githubusercontent.com/45672944/125844325-4b9ac1d3-95a4-4fd1-8d96-bc62f5011ccf.gif)
HC 1 | ![search-hc1](https://user-images.githubusercontent.com/45672944/125844346-4d5d7558-4a24-46b3-9044-4a5dd65f4d4d.gif)
HC 2 | …
> fix: Add themed styling to properties search bar

- src/AccessibilityInsights.SharedUx/SharedUx.csproj
- src/UITests/UITests.csproj
Update to Axe.Windows 1.1.0 to complete support for custom UIA properties
Complete custom UIA properties feature
> chore: Bump to Axe.Windows version 1.1.0

- src/AccessibilityInsights.SharedUx/Dialogs/StartUpModeControl.xaml
- src/AccessibilityInsights.SharedUx/Properties/Resources.Designer.cs
- src/AccessibilityInsights.SharedUx/Properties/Resources.resx
The startup screen currently shows Shift+F6 as the shortcut for event recording. The correct value, shown in both the control panel in the [documented shortcuts](https://accessibilityinsights.io/docs/en/windows/reference/keyboard/#live-inspect)), as well as proven by direct testing, is Shift+F7
Show correct information
Before change | After change
--- | ---
I renamed the string name for consistency with the content
> fix: Show correct keyboard shortcut in startup screen

- src/AccessibilityInsights.SharedUx/Telemetry/TelemetryAction.cs
- src/AccessibilityInsights.SharedUx/Telemetry/TelemetryBuffer.cs
- src/AccessibilityInsights.SharedUx/Telemetry/TelemetryProperty.cs
- src/AccessibilityInsights.SharedUxTests/Telemetry/TelemetryBufferUnitTests.cs
- src/AccessibilityInsights/MainWindow.xaml.cs
- src/AccessibilityInsights/MainWindowHelpers/Initialize.cs
- src/AccessibilityInsights/Misc/TelemetryEventFactory.cs
Add telemetry for number of registered custom UIA properties when telemetry and custom UIA are enabled.
Part of custom UIA extensions feature (internal Microsoft access required to view).
- [n/a] Does this address an existing issue? If yes, Issue# -
> feat(custom-uia): Add telemetry for custom UIA property count

- docs/TelemetryDetails.md
In #1162, we added telemetry without updating the corresponding documentation. This updates the documentation 
Keep docs in sync with code.
Here's slightly redacted output of an actual event in telemetry--note that the value for the `customDimensions` property is a json-formatted object, and that `CustomUIAPropertyCount` is a property on that object:
Property | Value
--- | ---
name | Custom_UIA
itemType | customEvent
customDimensions | {"ReleaseChannel":"Canary","InstallationID":"4d05726d-3e0f-43e1-83c2-0aefa1709636","AppSessionID":"ff1dc94a-ef9e-4e66-a5c4-d13fd156d0b9","SessionType":"Desktop","Version":"1.1.1667.1","CustomUIAPropertyCount":"9"}
- [n/a] Run the production version of Accessibility …
> chore: Update telemetry docs to include Custom_UIA event

- src/AccessibilityInsights.Extensions.AzureDevOps/FileIssue/AdoNotSupportedDialog.xaml
- src/AccessibilityInsights.Extensions.AzureDevOps/FileIssue/AdoNotSupportedDialog.xaml.cs
- src/AccessibilityInsights.Extensions.AzureDevOps/FileIssue/FileIssueHelpers.cs
ADO bug filing has recently stopped working (see #1167). We need to investigate a long-term strategy here, but we've agreed to a short-term strategy of warning uses who attempt to use ADO bug filing that it's unavailable and provide information to learn more about the current state. 
Educate the user about #1167 
When the user clicks on the "File Issue" button using ADO, the following dialog is presented:
If the user clicks on the link, the issue is opened. The dialog goes away when the user clicks the OK button (which is also the default button)
We considered just using MessageBox but decided that the experience was less than we wanted it to be.
- [ado fails] Run through of all [test scenarios](https://github.com/Microsoft/accessibility-insights-windows/blob/main/docs/Scenarios.md) …
> chore: Replace ADO dialog with simple error dialog

- docs/TelemetryOverview.md
There's a typo in the link from `TelemetryOverview.md` to `TelemetryDetails.md`, so the link doesn't work. This fixes the typo.
Links should work
- [n/a] Does this address an existing issue? 
- [docs only] Includes UI changes?
> fix: Correct incorrect document link

- src/AccessibilityInsights.SharedUx/Controls/PatternInfoControl.xaml
- src/AccessibilityInsights.SharedUx/Controls/SettingsTabs/AboutTabControl.xaml
- src/AccessibilityInsights.SharedUx/Resources/Styles.xaml
Convert labels in the About dialog to focusable text to they're more accessible via NVDA & Narrator
Addresses issue found in trusted tester pass
Mode | GIF
--- | ---
Light | ![focusable-light](https://user-images.githubusercontent.com/45672944/131548947-78c4c061-55dd-46f9-935b-6b392f61fa85.gif)
Dark | ![focusable-dark](https://user-images.githubusercontent.com/45672944/131548987-eb4136fe-205b-4fa7-841b-50f76f3abcdf.gif)
HC 1 | ![focusable-hc-1](https://user-images.githubusercontent.com/45672944/131549017-406b371f-4e30-424e-aef0-a1bce445fcf0.gif)
HC 2 | ![focusable-hc-2](https://user-images.githubusercontent.com/45672944/131549050-6d265d6c-cffa-473c-88ca-0230109ff014.gif)
HC Black | ![focusable-hc-black](https://user-images.githubusercontent.com/45672944/131549076-1c72da64-b5fb-4d6a-b72a-fe …
> fix: Make labels in About dialog focusable

- src/AccessibilityInsights.SharedUx/Controls/PrivacyLearnMore.xaml
- src/AccessibilityInsights.SharedUx/Controls/SettingsTabs/AboutTabControl.xaml
- src/AccessibilityInsights.SharedUx/Controls/SettingsTabs/ConnectionControl.xaml
- src/AccessibilityInsights.SharedUx/Controls/TestTabs/ColorContrast.xaml
- src/AccessibilityInsights.SharedUx/Controls/TestTabs/TabStopControl.xaml
- src/AccessibilityInsights.SharedUx/Dialogs/StartUpModeControl.xaml
- src/AccessibilityInsights.SharedUx/Dialogs/TelemetryApproveContainedDialog.xaml
- src/AccessibilityInsights.SharedUx/Resources/Styles.xaml
In a recent trusted tester pass, a bug was filed about distinguishing hyperlinks only by color, since they had no underlines. This was a design decision made a long time ago, but since we've put underlines in some places in response to trusted tester bugs, I just went ahead and put underlines in all hyperlinks. More specifically, this involved 2 changes:
1. We were suppressing the underlines by overriding the **TextDecorations** property. The PR removes all of those overrides.
2. In the tbLink style, we were only setting the Underline style on mouse hover. This now sets the style all the time
Address trusted tester bug
I'm just including the Color Contrast screen and the test results screen in the screenshots, even though the change impacts other places, as well:
Location | Before | After …
> fix: Use underlines for hyperlinks

- src/AccessibilityInsights.SharedUx/Behaviors/KeyboardToolTipButtonBehavior.cs
- src/AccessibilityInsights/App.xaml.cs
The current code hides tooltips after 5 seconds, which violates current accessibility requirements. Change the code to display them until the user takes some action that would dismiss them.
We actually had code that was hardcoded to a 5 second dismissal of the tooltips, but 5 seconds also seems to be the default value from WPF. I found no way to tell WPF not to hide tooltips at all, but I was able to set the duration to int.MaxValue
Address trusted tester bug
These screenshots only show the tooltip for about 15 seconds, but it will last much longer. In fact, int.MaxValue in milliseconds represents about 24 days of actual time...
Old | New
--- | --- …
> fix: Allow tooltips to display until the user takes action

- src/AccessibilityInsights.SetupLibrary/REST/GitHubClient.cs
- src/AccessibilityInsights.SetupLibrary/TriState.cs
Issue #1191 highlighted an error case that we overlooked. The root cause is that the code added to provide a progress indicator to the dialog didn't include handling for externally caused failure (network issue, etc.) or for user cancellation. In terms of the code, when the download failed, we get to https://github.com/microsoft/accessibility-insights-windows/blob/main/src/AccessibilityInsights.SetupLibrary/REST/GitHubClient.cs#L72 and access the value for `DownloadDataCompletedEventArgs.Result`. This indirectly calls into https://github.com/microsoft/referencesource/blob/master/System/compmod/system/componentmodel/AsyncCompletedEventArgs.cs#L60, where the `TargetInvocationException` gets thrown if an error occurred. Since the callback to DownloadCompleted is async, the exception is …
> fix: Handle unhandled exception during update

- src/AccessibilityInsights.SharedUx/Behaviors/KeyboardToolTipButtonBehavior.cs
#1192 Made tooltips stay visible indefinitely (instead of disappearing after 5 seconds). What was lacking, though, was a way to dismiss the tooltip to get it out of the way, and the bug was reactivated as a result. This PR adds a keyboard handler to dismiss the tooltip when the user presses Escape, as described in https://www.w3.org/WAI/WCAG21/Understanding/content-on-hover-or-focus.html.
Fix trusted tester bug
Dismiss on escape was raised in the comments for #1192, but since the framework dismissed on Shift+Ctrl+F10, we believed that would suffice. To meet WCAG guidelines, we need something easier.
> Note: After the PR has been created, certain checks will be kicked off. All of these …
> fix: Add a handler to clear button tooltip when Escape is pressed

- src/AccessibilityInsights.sln
- src/AccessibilityInsights/MainWindowHelpers/Initialize.cs
- src/AccessibilityInsights/Properties/AssemblyInfo.cs
- src/AccessibilityInsightsUnitTests/AccessibilityInsightsUnitTests.csproj
- src/AccessibilityInsightsUnitTests/MainWindowHelpers/InitializeUnitTests.cs
Our window positioning code has some problems:
1. It never resizes the window, even if it's tool big to fit on screen
2. It fails to handle cases where the window position is `double.NaN` (which happens on first boot). As documented at https://docs.microsoft.com/en-us/dotnet/api/system.double.nan?view=net-5.0, comparing `double.NaN` to any other value (except `double.NaN`) will return false, and this is breaking the current code.
Because of these problems, it's possible to have parts of the app inaccessible on first boot at 200% zoom.
The fix is to rework the code that sets the initial window position so that the entire app is always in the virtual window, even if we need to resize the window (old code could only reposition, not resize). I also added some unit tests to make it easier to …
> fix: Ensure windows bounds at all zoom levels

- src/AccessibilityInsights.SharedUx/Resources/Styles.xaml
The keyboard focus indicator in the tabstops list doesn't match updated WCAG requirements. Our color palette is pretty minimal in dark and HC modes, so we fix this by enabling a stronger system focus indicator, then we make it stand out by adding a contrasting border inside the focus indicator.
Address TT bug
These are all the same sequence where we use the keyboard to move between some items in the list, then tab to the nav bar, shift-tab back to the list, the move back to our starting point.
Mode | GIF
--- | ---
Light | ![tabstops-light](https://user-images.githubusercontent.com/45672944/133855667-9563a4b7-b0d9-4c06-b1b4-7379e988c963.gif)
Dark | ![tabstops-dark](https://user-images.githubusercontent.com/45672944/133855712-ad7c6db8-aa73-4f14-8fb8-5ff4af34da9b.gif)
HC 1 | …
> fix: Clearer keyboard focus indicator for tabstops list

- src/AccessibilityInsights.SharedUx/Resources/Styles.xaml
Make selected menu items bold to satisfy WCAG 1.4.1 requirements. According to https://www.w3.org/TR/2016/NOTE-UNDERSTANDING-WCAG20-20161007/visual-audio-contrast-without-color.html, there are multiple ways to satisfy this requirement. One of these ways is https://www.w3.org/TR/2016/NOTE-WCAG20-TECHS-20161007/G182, which states:
To use this technique, an author incorporates a visual cue in addition to color for each place where color alone is used to convey information. Visual cues can take many forms including changes to the font style, the addition of underlines, bold, or italics, or changes to the font size.
Our color palette in Dark and HC modes are very limited, so we're taking the approach of making the selected popup menu item bold, so that color isn't the only distinguishing …
> fix: Make selected menu item bold

- src/AccessibilityInsights.Extensions.AzureDevOps/Properties/Resources.Designer.cs
- src/AccessibilityInsights.Extensions.AzureDevOps/Properties/Resources.resx
- src/AccessibilityInsights.Extensions.GitHub/Properties/Resources.Designer.cs
- src/AccessibilityInsights.Extensions.GitHub/Properties/Resources.resx
Adjust the help text for GitHub and ADO issue filing to be slightly more descriptive, but still be succinct.
Address TT bug
Type of issues | Screenshot
--- | ---
ADO (Azure Boards) | ![image](https://user-images.githubusercontent.com/45672944/134042497-1733583b-ffa9-46ec-9347-2830aaad6d7f.png)
GitHub | ![image](https://user-images.githubusercontent.com/45672944/134042530-64d74200-0906-4a88-bfab-5ab9c7e7a900.png)
Note that the help text is shorter than the text that appears directly above the edit control. This is _intentional_, since reading the full line actually reduces the usability of the control when an AT is used. The text we settled on is long enough to describe what the control does, but is succinct enough to not get in the way.
> Note: After the PR has been created, certain …
> fix: Revise repo link help text to be more helpful

- docs/TelemetryOverview.md
- src/AccessibilityInsights.SharedUx/Controls/SettingsTabs/ApplicationSettingsControl.xaml
- src/AccessibilityInsights.SharedUx/Controls/SettingsTabs/ApplicationSettingsControl.xaml.cs
- src/AccessibilityInsights.SharedUx/Dialogs/TelemetryApproveContainedDialog.xaml.cs
- src/AccessibilityInsights.SharedUx/Properties/Resources.Designer.cs
- src/AccessibilityInsights.SharedUx/Properties/Resources.resx
- src/AccessibilityInsights.SharedUx/Settings/ConfigurationModel.cs
- src/AccessibilityInsights.SharedUx/Telemetry/ITelemetrySink.cs
- src/AccessibilityInsights.SharedUx/Telemetry/TelemetryController.cs
- src/AccessibilityInsights.SharedUx/Telemetry/TelemetrySink.cs
- src/AccessibilityInsights.SharedUxTests/Settings/ConfigurationModelTests.cs
- src/AccessibilityInsights.SharedUxTests/Telemetry/TelemetrySinkUnitTests.cs
- src/AccessibilityInsights/MainWindowHelpers/Initialize.cs
- src/AccessibilityInsights/MainWindowHelpers/TelemetryStartup.cs
Create a registry-based policy to disable telemetry from a computer. The suppression is system-wide and persists across uninstall/reinstall. The suppression is added by creating the following registry value:
Key: HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Accessibility Insights for Windows
Value (DWORD): DisableTelemetry = 1
In terms of a reg file, it looks like this:
```
Windows Registry Editor Version 5.00
[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Accessibility Insights for Windows]
"DisableTelemetry"=dword:00000001
```
If this value exists and is set to 1, then the initial telemetry prompt is skipped. Inside the settings dialog, the standard telemetry block is also changed, as shown here:
Key not set (default) | Key set (with this change)
--- | ---
The key is read when the app starts up, and …
> fix: Allow system administrators to suppress telemetry by policy

- src/AccessibilityInsights/MainWindow.xaml.cs
- src/AccessibilityInsights/MainWindowHelpers/Initialize.cs
Fix canary upgrade problem by ensuring that ordering assumptions are respected during initialization. For the autoupdate to work as expected, it's important that `Container.SetAutoUpdateReleaseChannel` gets called before `Container.GetDefaultInstance`. When #1204 was added, the code is in the proper sequence, and the upgrade works as expected when built for the debug config. When built for the release config, though, I was able to prove that the calls were occurring in the wrong order. It seems that the optimizer decided to change the sequence of calls between the API's, meaning that the autoUpdate code always loaded the production data.
The change here is to move the telemetry initialization code into a separate method so the optimizer can no longer change the call order. As an aside, …
> fix: Ensure proper sequencing during initialization

- src/AccessibilityInsights.SharedUx/Controls/TestTabs/ColorContrast.xaml.cs
Back in https://github.com/microsoft/axe-windows/pull/469, we made it possible for AIWin to control the parameters used for automatic color detection. We then forgot to use this ability. This finishes that change so that we have the ability to experiment with color contrast parameters strictly from the AIWin side (without requiring a re-release of Axe.Windows). Once this merges, we can also remove the legacy ctor from the Axe.Windows `BitmapCollection` class (https://github.com/microsoft/axe-windows/pull/652).
Complete a task that was only halfway finished
> chore: Control color contrast detection parameters from AIWin

- src/AccessibilityInsights.SharedUx/Controls/ScannerResultControl.xaml
- src/AccessibilityInsights.SharedUx/Resources/Styles.xaml
This is a quick fix to the color contrast problem reported in bug #845 
Due to problems with the current implementation of the GridViewColumnHeader, it is not possible to customize the background properties (the color changes are not reflected in the element). This is the reason why I decided to change the foreground color to increase the ratio between the header and the background as shown in the following picture.
(The image above shows the color contrast analyzer test of the background color against the foreground color, which gives a ratio of 8.917:1)
| Mode  | Image |
| ------------- | ------------- |
| Light  | ![image](https://user-images.githubusercontent.com/32908302/141720212-67e2f6f9-7d6f-42d6-aa83-6e2b9a63b55c.png) |
| Dark  | …
> AI-Win color contrast bug

- src/AccessibilityInsights.Extensions.AzureDevOps/AzureBoardsIssueReporting.cs
- src/AccessibilityInsights.Extensions.AzureDevOps/AzureDevOpsIntegration.cs
- src/AccessibilityInsights.Extensions.AzureDevOps/ConfigurationControl.xaml.cs
- src/AccessibilityInsights.Extensions.AzureDevOps/FileIssue/FileIssueHelpers.cs
- src/AccessibilityInsights.Extensions.AzureDevOps/Properties/Resources.Designer.cs
- src/AccessibilityInsights.Extensions.AzureDevOps/Properties/Resources.resx
This PR improves localization in the `AccessibilityInsights.Extensions.AzureDevOps` project. All of the changes replace a hardcoded string with a new resource string.
To make the work more manageable, I'll create a separate PR for each project.
Each commit includes strings from a single .cs file. It might be easier to review each commit separately. They do not overlap.
> feat(compliance-fall-21): Improve localizability in AzureDevOps project

- src/AccessibilityInsights.VersionSwitcher/MainWindow.xaml.cs
- src/AccessibilityInsights.VersionSwitcher/Properties/Resources.Designer.cs
- src/AccessibilityInsights.VersionSwitcher/Properties/Resources.resx
This PR improves localization in the `AccessibilityInsights.VersionSwitcher` project. All of the changes replace a hardcoded string with a new resource string.
To make the work more manageable, I'll create a separate PR for each project.
Each commit includes strings from a single .cs file. It might be easier to review each commit separately. They do not overlap.
> feat(compliance-fall-21): Improve localizability in VersionSwitcher project

- src/AccessibilityInsights.SharedUx/Controls/SettingsTabs/ApplicationSettingsControl.xaml.cs
Remove some code that serves no purpose. A _**long**_ time ago, each of these blocks included a final line that sent a telemetry event to track that the user had changed a hotkey mapping. The code to _send_ the telemetry was removed, but the code to _set up_ for the telemetry was left intact. The logical options seem to be to bring back the telemetry or to remove the code that sets up for the no-longer called telemetry. I opted for the latter option.
Code hygiene, reduce clutter
> chore: Remove dead code

- src/AccessibilityInsights.SharedUx/ActionViews/ReturnA11yElementsView.xaml.cs
- src/AccessibilityInsights.SharedUx/Controls/EventConfigTabControl.xaml.cs
- src/AccessibilityInsights.SharedUx/Controls/EventRecordControl.xaml.cs
- src/AccessibilityInsights.SharedUx/Controls/HierarchyControl.xaml.cs
- src/AccessibilityInsights.SharedUx/Controls/PatternInfoControl.xaml.cs
- src/AccessibilityInsights.SharedUx/Controls/PropertyInfoControl.xaml.cs
- src/AccessibilityInsights.SharedUx/Controls/TestTabs/AutomatedChecksControl.xaml.cs
- src/AccessibilityInsights.SharedUx/Dialogs/PropertyConfigDialog.xaml.cs
- src/AccessibilityInsights.SharedUx/Dialogs/TextPatternExplorerDialog.xaml.cs
- src/AccessibilityInsights.SharedUx/Enums/FileFilters.cs
- src/AccessibilityInsights.SharedUx/FileIssue/IssueReporterManager.cs
- src/AccessibilityInsights.SharedUx/Highlighting/Highlighter.cs
- src/AccessibilityInsights.SharedUx/Highlighting/HollowHighlightDriver.cs
- src/AccessibilityInsights.SharedUx/Properties/Resources.Designer.cs
- src/AccessibilityInsights.SharedUx/Properties/Resources.resx
- src/AccessibilityInsights.SharedUx/ViewModels/BaseActionViewModel.cs
- src/AccessibilityInsights.SharedUx/ViewModels/ColorContrastViewModel.cs
- src/AccessibilityInsights.SharedUx/ViewModels/EventConfigNodeViewModel.cs
- src/AccessibilityInsights.SharedUx/ViewModels/HierarchyNodeViewModel.cs
- src/AccessibilityInsights.SharedUx/ViewModels/ScanListViewItemViewModel.cs
This PR improves localization in the `AccessibilityInsights.SharedUx` project. Some of the changes replace a hardcoded string with a new resource string, while others replace hardcoded concatenation of resource strings with a parameterized resource string (which would allow the parameters to be used in any order).
Each commit includes strings from a single .cs file. It might be easier to review each commit separately. There is at least 1 overlapping commit, because the first commit to `HierarchyViewNodeModel` created a bug that got fixed in the second commit to `HierarchyViewNodeModel`. The second commit also renamed some of the string resources to be more consistent with the new ones (and to simplify the names).
This PR does not fully …
> feat(compliance-fall-21): Improve localizability in SharedUx project

- src/AccessibilityInsights.SharedUx/Dialogs/StartUpModeControl.xaml
- src/AccessibilityInsights.SharedUx/Resources/Styles.xaml
In #1249, the welcome screen has some text that responds to text scaling, some that doesn't. As a result, the dialog becomes unusable. This PR just specifies a font size for the 3 screen items that are being clipped.
Address #1249 
Before at 200% text size (from #1249):
After at 200% text size:
> fix: Specify font size in welcome screen text

- src/AccessibilityInsights.CustomActions.Package/CustomActions.Package.csproj
- src/MSI/MSI.wixproj
- src/MSI/packages.config
Dependabot PR #1233 bumped the MicroBuild version in all of the new-format projects, but we failed to upgrade the project that generates an MSI file (the WiX project is incompatible with the new format, or else we would have changed this before). This PR changes the MicroBuild version in the MSI-related projects. Validation signed build (where MicroBuild really matters) is at https://dev.azure.com/mseng/1ES/_build/results?buildId=16433452&view=results
Use updated build package
- [n/a] Run the production version of Accessibility Insights for Windows against …
> chore: Use latest MicroBuild package when building MSI-related projects

- src/AccessibilityInsights.SharedUx/ActionViews/ReturnA11yElementsView.xaml
- src/AccessibilityInsights.SharedUx/ActionViews/TextRangeActionView.xaml
- src/AccessibilityInsights.SharedUx/Controls/EventRecordControl.xaml
- src/AccessibilityInsights.SharedUx/Controls/HierarchyControl.xaml
- src/AccessibilityInsights.SharedUx/Controls/InspectTabsControl.xaml
- src/AccessibilityInsights.SharedUx/Controls/TestTabs/AutomatedChecksControl.xaml
- src/AccessibilityInsights.SharedUx/Controls/TestTabs/TabStopControl.xaml
- src/AccessibilityInsights.SharedUx/Controls/TextRangeControl.xaml
- src/AccessibilityInsights.SharedUx/Dialogs/EventConfigDialog.xaml
- src/AccessibilityInsights.SharedUx/Properties/Resources.Designer.cs
- src/AccessibilityInsights.SharedUx/Properties/Resources.resx
- src/AccessibilityInsights/MainWindow.xaml
- src/AccessibilityInsights/Modes/ConfigurationModeControl.xaml
- src/AccessibilityInsights/Properties/Resources.Designer.cs
- src/AccessibilityInsights/Properties/Resources.resx
I found some localizable resources embedded into XAML files. This PR simply pulls them out into resx files. It also corrects a shortcut conflict where the "expand/collapse all" accessibility shortcut in the automated checks view and the "show configuration" accessibility shortcut in the main window were both mapped to alt+c. The "expand/collapse all" accessibility shortcut in the automated checks view is now mapped to alt+e so there's no longer a conflict.
Baby steps towards being able to localize.
This is another case where it's probably easiest to review on a per-commit basis. There's 1 overlapping commit because I realized that `RetunA11yElementsView_Header_Value` should have been `RetunA11yElementsView_Value_Header` for consistency
- [n/a] Does this address an existing issue? If yes, …
> feat(compliance-fall-21): Improve localizability in xaml files

- src/AccessibilityInsights.CustomActionsUnitTests/CustomActionsUnitTests.csproj
- src/AccessibilityInsights.Extensions.AzureDevOpsTests/Extensions.AzureDevOpsTests.csproj
- src/AccessibilityInsights.Extensions.GitHubAutoUpdateUnitTests/Extensions.GitHubAutoUpdateUnitTests.csproj
- src/AccessibilityInsights.Extensions.GitHubUnitTests/Extensions.GitHubUnitTests.csproj
- src/AccessibilityInsights.Extensions.TelemetryTests/Extensions.TelemetryTests.csproj
- src/AccessibilityInsights.ExtensionsTests/ExtensionsTests.csproj
- src/AccessibilityInsights.SetupLibraryUnitTests/SetupLibraryUnitTests.csproj
- src/AccessibilityInsights.SharedUxTests/SharedUxTests.csproj
- src/AccessibilityInsightsUnitTests/AccessibilityInsightsUnitTests.csproj
- src/UITests/UITests.csproj
Dependabot PR's #1260 and #1261 work locally but are failing in the build pipeline. This PR combines the changes to see if they'll work together... or to allow some debugging if they don't.
> chore: Bump MSTest.Test* from 2.2.7 to 2.2.8

- src/AccessibilityInsights.SharedUx/Controls/TextRangeControl.xaml
- src/AccessibilityInsights.SharedUx/Dialogs/TextPatternExplorerDialog.xaml
- src/AccessibilityInsights.SharedUx/Resources/Dark/Brushes.xaml
- src/AccessibilityInsights.SharedUx/Resources/HighContrast/Brushes.xaml
- src/AccessibilityInsights.SharedUx/Resources/Light/Brushes.xaml
- src/AccessibilityInsights.SharedUx/Resources/Styles.xaml
As called out in #1262, we have some cases where we apply the color theme in unthemed dialogs, leading to controls that are not visible until they experience a mouse hover. This PR creates a new theme, `hoverAwareFabricIconOnUnthemedButtonParent`, and sets an appropriate foreground color when no mouse hover exists.
Address #1262 
These screenshots were all taken with the mouse hover over the settings button of the attributes control. Hover colors for the other 3 buttons all match what is displayed here.
Mode | Screenshot
--- | ---
Light | <img width="478" alt="Explorer-Light" src="https://user-images.githubusercontent.com/45672944/144152405-5d127db1-3259-4f7b-bce1-348409dd8505.png">
Dark | <img width="478" alt="Explorer-Dark" src="https://user-images.githubusercontent.com/45672944/14415241 …
> fix: Stop overtheming controls in dark mode

- src/AccessibilityInsights.SharedUx/Controls/EventConfigurationControl.xaml
- src/AccessibilityInsights.SharedUx/Dialogs/ElementInfoDialog.xaml
As called out in #1266, we have controls that become invisible in dark mode due to theming issues. This PR address the items in #1266, but in slightly different ways. In the `EventConfigurationControl`, we just change the styles of the `fabricIconControl` objects and leave the surrounding dialog unthemed. In the `ElementInfoDialog`, it's simpler to just theme the dialog. 
Address #1266
Attributes dialog: In each case, the mouse hover is on the "Add" button.
Theme | Screenshot
--- | ---
Light | <img width="425" alt="attributes-light" src="https://user-images.githubusercontent.com/45672944/144302856-519bc350-1210-418a-8d4a-1b1b25672989.png">
Dark | <img width="425" alt="attributes-dark" src="https://user-images.githubusercontent.com/45672944/144302877-30387a17-055c-47b4-9cff-9278a86a4350.png …
> fix: Address theming issues in dark mode

- src/AccessibilityInsights.Extensions.GitHub/Extensions.GitHub.csproj
- src/AccessibilityInsights.Extensions.Telemetry/Extensions.Telemetry.csproj
- src/AccessibilityInsights.SharedUx/SharedUx.csproj
- src/UITests/UITests.csproj
Bump Axe.Windows (and transient dependencies) to latest versions
Incorporate latest rule changes
- [n/a] UI changes?
> chore: Bump Axe.Windows from 1.1.1 to 1.1.2, update dependencies

- src/AccessibilityInsights.SharedUx/Properties/Resources.Designer.cs
- src/AccessibilityInsights.SharedUx/Properties/Resources.resx
- src/AccessibilityInsights/Properties/Resources.Designer.cs
- src/AccessibilityInsights/Properties/Resources.resx
Together, #1201 and #1250 added 3 resource strings that each contain a newline. In each case, the newline was added as a `\n` in the resx file, but the resource compiler treats this as visible text, meaning that the newline gets misrendered. This change simply replaces the `\n` sequence with a newline in the resx file. Changes were made via the resource editor, so no manual changes to the resx files occurred. I checked for any other instances of escaped characters in resource files and found nothing else that needed changes.
Represent newlines correctly. Two of the strings are error messages and unlikely to occur very often. The third one is in rendering the auto-detected color contrast and is easy to demonstrate:
Current Version | Fixed version
--- | --- …
> fix: Line breaks in resources files are rendered as literals

- src/AccessibilityInsights/App.config
.NET released some [accessibility fixes](https://docs.microsoft.com/en-us/dotnet/framework/whats-new/whats-new-in-accessibility#whats-new-in-accessibility-in-the-august-11-2020-cumulative-update-for-net-framework-48) in August 2020. These changes are focused around the `PropertyGrid`, `PropertyGridView`, and `DataGridView`, which we use in multiple places. In order to enable these fixes, we need to specify `Switch.UseLegacyAccessibilityFeatures.4=false` in our app manifest.
Get the latest .NET accessibility fixes. Before merging, we should review old bugs that involve `PropertyGrid`, `PropertyGridView`, or `DataGridView` objects, and see what benefits we receive from the .NET fixes.
- [n/a] Run the …
> chore: Enable .NET accessibility features from August 2020 .NET update

- src/AccessibilityInsights.Extensions.AzureDevOps/FileIssue/IssueFileForm.cs
We discovered that our ADO bug filing is not compatible with the ADO policy that requires InTune management. The missing piece was to set the [AllowSingleSignOnUsingOSPrimaryAccount ](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2environmentoptions.allowsinglesignonusingosprimaryaccount?view=webview2-dotnet-1.0.1185.39) property, which allows our hosted WebView2 browser to present the credentials that tell ADO that we're InTune managed.
Enable ADO bug filing to work with more stringent security policy
- [n/a] Does this address an existing issue? If yes, Issue:
> chore: Allow SSO with ADO bug filing

- docs/TelemetryDetails.md
- src/AccessibilityInsights.SharedUx/Telemetry/TelemetryProperty.cs
- src/AccessibilityInsights/Misc/TelemetryEventFactory.cs
In a recent conversation, @RobGallo and I considered the possibility of moving from being an x86 app to being an x64 app. This would be a breaking change for users on x86 platforms and we have no way to approximate how many people it would impact. This PR adds a new `OsArchitecture` property to the `Mainwindow_Startup` telemetry event so that we have data to inform that decision. The supported values are either `x86` or `x64`. Here's the local telemetry that it produced on my x64 machine:
```
{
"EventName": "Mainwindow_Startup",
"EventProperties": {
"UIAccessEnabled": "False",
"OsArchitecture": "x64",
"InstalledDotNetFrameworkVersion": "528372"
}
}
```
Help us to understand the impact of moving to x64.
- [n/a] Does this address an existing issue? If yes, Issue …
> chore: Add OS Architecture to telemetry

- src/AccessibilityInsights.SharedUx/FileIssue/IssueReporter.cs
There are a couple of valid cases in issue filing where we trigger a `NullReferenceException`:
1. User files an issue in GitHub, where the code [always returns null](https://github.com/microsoft/accessibility-insights-windows/blob/main/src/AccessibilityInsights.Extensions.GitHub/IssueReporter.cs#L85).
2. Users opens the ADO bug filing dialog, but the browser is closed [without saving the bug](https://github.com/microsoft/accessibility-insights-windows/blob/main/src/AccessibilityInsights.Extensions.AzureDevOps/AzureBoardsIssueReporting.cs#L103))
This PR just adds a level of null propagation to prevent us from making that mistake.
Make it easier to diagnose what the "real" problem is
- [n/a] Does this address an existing issue? If yes, Issue:
> Note: After the …
> fix: Avoid NullReferenceException

- src/AccessibilityInsights.Extensions.AzureDevOps/FileIssue/IssueFileForm.cs
- src/MSI/Product.wxs
#1312 set a new environment, but it wasn't setting the `userDataFolder` when creating the environment ([docs](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2environment.createasync?view=webview2-dotnet-1.0.1185.39)). As a result, the WebView2 was trying to put data under the folder where the app exists, which is under C:\Program Files (x86) when using an MSI install. This folder requires administrative permissions, so it failed unless the app was running as administrator. Running as administrator still had a problem because the administrative privileges didn't propagate to the hosted control.
This change sets the `userDataFolder` when creating the environment, so no administrative permissions are required and the data ends up where it's expected. Note …
> fix: Support ADO when running from MSI install

- src/AccessibilityInsights.SharedUx/Controls/TestTabs/ColorContrast.xaml.cs
- src/AccessibilityInsights.SharedUx/SharedUx.csproj
- src/AccessibilityInsights/Modes/SnapshotModeControl.xaml.cs
- src/AccessibilityInsights/Modes/TestModeControl.xaml.cs
- src/UITests/UITests.csproj
Move to Axe.Windows 1.1.3. This PR includes a couple of tiny changes in the private API that we use with Axe.Windows.
We want to include the Axe.Windows scanDurationInMilliseconds telemetry changes in our next Prod release.
> chore: Pick up Axe.Windows 1.1.3

- src/AccessibilityInsights.SharedUx/ActionViews/ReturnA11yElementsView.xaml
- src/AccessibilityInsights.SharedUx/Controls/EventRecordControl.xaml
- src/AccessibilityInsights.SharedUx/Controls/HierarchyControl.xaml
- src/AccessibilityInsights.SharedUx/Controls/InspectTabsControl.xaml
- src/AccessibilityInsights.SharedUx/Controls/PatternInfoControl.xaml
- src/AccessibilityInsights.SharedUx/Controls/PropertyInfoControl.xaml
- src/AccessibilityInsights.SharedUx/Controls/TextRangeControl.xaml
- src/AccessibilityInsights.SharedUx/Dialogs/ElementInfoDialog.xaml
- src/AccessibilityInsights.SharedUx/Dialogs/TextPatternExplorerDialog.xaml
- src/AccessibilityInsights.SharedUx/Resources/Styles.xaml
- src/AccessibilityInsights/MainWindow.xaml
Currently, some of our MenuItems are bolded and highlighted when selected, while others are just highlighted. Because the default highlight behavior has insufficient color contrast, this PR ensures all MenuItems are bolded when selected. To do this, 
`menuPlainWhite` is applied to as many menus as possible. In cases where it has issues, a new `menuDefault` style has been created to provide the bolding behavior. 
Screen capture:
Addresses an accessibility issue
Ideally, we would fully standardize to use `menuPlainWhite`. Unfortunately, it has issues with multi-leveled menus which were too complicated to address as a part of this PR.
To reduce the amount of size changing on selection, a minor `LayoutTransform` is applied alongside the bolding.
- [n/a] Run through of all [test …
> fix: Bold MenuItem text when selected

- src/AccessibilityInsights.SharedUx/Controls/EventRecordControl.xaml
- src/AccessibilityInsights.SharedUx/Controls/HierarchyControl.xaml
- src/AccessibilityInsights.SharedUx/Properties/Resources.Designer.cs
- src/AccessibilityInsights.SharedUx/Properties/Resources.resx
- src/AccessibilityInsights/MainWindow.xaml.cs
- src/AccessibilityInsights/Properties/Resources.Designer.cs
- src/AccessibilityInsights/Properties/Resources.resx
Improve some accessible names in the product.
Address #1322 
These table shows the accessible names and tooltips before and after the change. The "1 of 2": and "2 of 2" in the nav bar are because the signin button and the settings button are in a functional group. We follow a similar pattern for the buttons for inspect, test, and color modes (a separate group within the nav bar)
Element - property | Before change | After change
Connection button - Name (unchanged) | n/a (button is hidden) | n/a (button is hidden)
Connection button - Tooltip (unchanged) | n/a (button is hidden) | n/a (button is hidden)
Settings button - Name (changed) | Settings 1 of 2 | Application Settings
Settings button - Tooltip (unchanged) | Change settings... | Change settings...
Element - property | …
> fix: Improve some accessible names

- SECURITY.md
We are adding the latest version of the SECURITY.md file as found here: https://github.com/microsoft/repo-templates/blob/main/shared/SECURITY.md.
After checking with the Github in Microsoft (GiM) team, we are being asked to add this file to all of our open-source repos. This file is used to help the community understand the Microsoft open source security policy and how to safely report security issues. GitHub uses the presence of this file to light-up security reminders and a link to the file. More information for internal reference can be found here: https://aka.ms/opensource
Ensures compliance with GiM/Open Source policy preferences
> chore: Adding required SECURITY.md file

- src/AccessibilityInsights.SharedUx/Controls/ScannerResultControl.xaml
- src/AccessibilityInsights.SharedUx/Properties/Resources.Designer.cs
- src/AccessibilityInsights.SharedUx/Properties/Resources.resx
- src/AccessibilityInsights.SharedUx/ViewModels/ScanListViewItemViewModel.cs
This PR extends the existing "View Code Sample" behavior to allow it to be used for framework issues, as well. Specifically:
1. `ScannerResultControl.xaml` uses hardcoded strings for "Fix the following" and "View Code Sample". Move these strings into resource strings
2. Add resource strings that we display when we have a FrameworkIssueLink
3. Add `ScanListViewItemViewModel.HyperlinkText` to provide the string that is the visible portion of the Hyperlink. It's "View Code Sample" for issues without a FrameworkIssueLink, and "How to investigate" for issues with a FrameworkIssueLink
4. Use `ScanListVIewItemViewModel.HyperlinkText` to set the text for the Hyperlink
5. Overload `ScanViewItemViewModel.HowToFixText` so that it uses the framework issue boilerplate text if the issue has a …
> feat(framework-issues-ui): Add link to framework issue

- src/AccessibilityInsights.SharedUx/Controls/CustomControls/AutomatedChecksCustomListControl.xaml
- src/AccessibilityInsights.SharedUx/Controls/TestTabs/AutomatedChecksControl.xaml
In #1354, we made a change that shifted the horizontal scrollbar from the pane to each child ListView, which triggered a design discussion and the decision was made that we didn't want it that way. This PR makes both ListView controls scroll horizontally together.
Feature work
Description | Screenshot
--- | ---
Current Production (1 scrollbar) | ![image](https://user-images.githubusercontent.com/45672944/173632740-35a8ec18-07ea-49fb-8527-0b5fc60b14a5.png)
Current Canary (2 scrollbars) | ![image](https://user-images.githubusercontent.com/45672944/173632923-db765b33-fce6-42aa-8dfe-62a885872574.png)
This PR (1 scrollbar) | ![image](https://user-images.githubusercontent.com/45672944/173633129-f970c4b1-05b7-456e-b7b4-3ecf1e5da19a.png)
> Note: After the PR has been created, certain checks will …
> feat(framework-issues-ui): Revisit scrollbars in AutomatedChecks view

- src/AccessibilityInsights.SharedUx/Controls/CustomControls/AutomatedChecksCustomListControl.xaml.cs
- src/AccessibilityInsights.SharedUx/Controls/CustomControls/ScannerResultCustomListControl.xaml.cs
- src/AccessibilityInsights.SharedUx/Controls/FileIssueWrapper.cs
- src/AccessibilityInsights.SharedUx/Controls/FileIssueWrapperInput.cs
- src/AccessibilityInsights.SharedUx/Controls/HierarchyControl.xaml.cs
- src/AccessibilityInsights.SharedUx/Controls/ScannerResultControl.xaml.cs
- src/AccessibilityInsights.SharedUx/Enums/FileBugRequestSource.cs
- src/AccessibilityInsights.SharedUx/Interfaces/IIssueFilingSource.cs
- src/AccessibilityInsights.SharedUx/Properties/Resources.Designer.cs
- src/AccessibilityInsights.SharedUx/Properties/Resources.resx
- src/AccessibilityInsights.SharedUx/ViewModels/HierarchyNodeViewModel.cs
- src/AccessibilityInsights.SharedUx/ViewModels/RuleResultViewModel.cs
- src/AccessibilityInsights.SharedUx/ViewModels/ScanListViewItemViewModel.cs
Issues can be filed from 3 locations in the UI:
1. From the AutomatedChecks view
2. From the HowToFix view
3. From the UIA Hierarchy
Each of these locations has a unique version of the code, with the following differences:
- Source for telemetry
- Input type (generally a ViewModel of some sort)
- Plumbing changes (some callers store their data directly, some delegate to other classes)
- In one case, we have better error handling to clean up temporary files if the issue filing fails
This PR does the following:
- Moves the common code into the new `FileIssueWrapper` class--it uses the version with the file cleanup if issue filing fails
- Provides control class abstraction by adding the `FileIssueWrapperInput` class
- Provides ViewModel abstraction by adding the `IIssueFilingSource` …
> feat(framework-issues-ui): Consolidate issue filing

- src/AccessibilityInsights.sln
This PR updates a GUID in the solution file. I noticed that VS make this change when an unrelated change I made locally updated the solution file. The GUID in question identifies the project type and probably goes back to a mistake when the project was added in #1302.
This change has no impact on what tests are run, and exists primarily to keep the same change from randomly appearing in a future change that touches the solution file.
Code hygiene
- [n/a] Does this address an existing issue? If yes, Issue
> Note: After the PR has been created, certain checks will be kicked off. All of these checks …
> chore: Correct GUID in solution file

- src/AccessibilityInsights.SharedUx/Controls/CustomControls/ScannerResultCustomListContext.cs
- src/AccessibilityInsights.SharedUx/Controls/CustomControls/ScannerResultCustomListControl.xaml
- src/AccessibilityInsights.SharedUx/Controls/CustomControls/ScannerResultCustomListControl.xaml.cs
- src/AccessibilityInsights.SharedUx/Controls/ScannerResultControl.xaml.cs
This PR includes some small tweaks to displaying results in the `ScannerResultControl`. In order of commit, they are:
1. The original code created a separate `ScannerResultCustomListContext` for each `ScannerResultCustomListControl` object. The 2 controls can and should share the same context, since all of the state is shared.
2. The `ItemSelectedHandler` was weakly typed since it passed on a generic object. I passed along the `this` object, which gives us stronger typing and stronger encapsulation.
3. The code was trying to select an item in the list, but was setting the `SelectedItem` property (which tries to match an object). The fix is to set the `SelectedIndex` property instead of `SelectedItem`
4. The `ChangeVisibility` method ends up generating multiple calls to `UpdateTree`, so we …
> feat(framework-issues-ui): Minor tweaks

- build/prbuild-Control.yml
During our recent release, the following warning was displayed during the [validation pipeline](https://dev.azure.com/accessibility-insights/Accessibility%20Insights%20(private)/_build/results?buildId=36711&view=logs&j=638eecd0-5cac-57a6-ab90-2825363d4ba8):
```
##[warning]The windows-2016 environment is deprecated and will be removed on June 30, 2022. For more details, see https://github.com/actions/virtual-environments/issues/5403
```
This pipeline simply executes a PowerShell script and has no output that links to the build, so we can reasonably allow it to "float" to the latest version of Windows.
Prevent the pipeline from breaking in a few days.
We could pin to a specific Windows version, but why?
- [n/a] Run through of all [test …
> chore: Update windows version

- src/AccessibilityInsights.Extensions.AzureDevOps/Extensions.AzureDevOps.csproj
Component Governance is flagging the AzureDevOps extension as using NewtonSoft.Json.dll version 12.0.3. This is a transitive dependency that gets overridden in AIWin's product.wxs file, but CG doesn't know about that because of our use of MEF. This PR simply explicitly sets NewtonSoft.Json.dll version 13.0.1, which doesn't have the vulnerability that exists in 12.0.3.
Make CG happy
> fix: Add forced reference to latest NewtonSoft version

- src/MSI/Product.wxs
Our WXS file has not been kept current when package contents change. This PR just updates the WXS file to match the list of assemblies in `./src/AccessibilityInsights/bin/release/net472`, with the intentional omission of the local disk logging assembly.
Keep the code up to date
Most of these changes probably came from dependabot updates. I wonder if we should consider having a pipeline check that intelligently compares the WXS file with the contents of the folder, then fails if they get out of sync. I'll add this to my list of things to do in slack time...
> chore: Update wxs file to match package contents

- src/AccessibilityInsights.Extensions.AzureDevOps/Extensions.AzureDevOps.csproj
- src/AccessibilityInsights.Extensions.AzureDevOps/FileIssue/FileIssueHelpers.cs
- src/AccessibilityInsights.Extensions.AzureDevOpsTests/FileIssue/FileIssueHelpersTests.cs
- src/AccessibilityInsights/AccessibilityInsights.csproj
- src/MSI/Product.wxs
As called out in #1377, the ADO issue filing code has a dependency on an assembly that Microsoft no longer supports but that someone has published to NuGet with a license that is probably incorrect. This code gets used to modify the HTML that is used to attach a screenshot to the issue in ADO.
This PR replaces the code that uses the old assembly with code that uses the HtmlAgilityPack [package](https://www.nuget.org/packages/HtmlAgilityPack), which is _genuinely_ MIT licensed, is actively maintained, and is fully open source at [this GitHub repo](https://github.com/zzzprojects/html-agility-pack/).
In addition to minor API differences, the HTML produced is different in 3 ways:
1. The old library forced all HTML tags to upper case; the new library doesn't do this. HTML is case-insensitive …
> fix: Remove dependency on legacy assembly

- src/AccessibilityInsights.SharedUx/Controls/SettingsTabs/ConnectionControl.xaml.cs
- src/AccessibilityInsights.SharedUx/Highlighting/Win32SnapshotButton.cs
- src/AccessibilityInsights.SharedUx/Settings/ConfigurationBase.cs
We have a `ReportException` method in 3 namespaces, each with a slightly different intended scope:
Namespace | Intended scope
--- | ---
`Axe.Windows.Telemetry` | Exceptions caught inside Axe.Windows
`AccessibilityInsights.Extensions` | Exceptions caught inside extension assemblies
`AccessibilityInsights.SharedUx.Telemetry` | Exceptions caught inside the rest of AIWin
I found 3 places where the wrong namespace was being used. It was probably a case where the method was added, VS suggested a namespace, and the wrong one was chosen. This PR ensures that AIWin's non-extension calls to `ReportException` use the method from the `AccessibilityInsights.SharedUx.Telemetry` namespace.
I've confirmed that the only remaining reference to the `Axe.Windows.Telemetry` namespace is correct (it's where we …
> fix: Use ReportException from correct namespace

- build/build-and-unit-tests.yml
- build/signedbuild.yml
- build/ui-test-job.yml
- docs/SetUpDevEnv.md
- src/AccessibilityInsights.CommonUxComponents/Properties/Resources.Designer.cs
- src/AccessibilityInsights.CustomActions/CustomActions.csproj
- src/AccessibilityInsights.Extensions.AzureDevOps/Properties/Resources.Designer.cs
- src/AccessibilityInsights.Extensions.GitHub/Properties/Resources.Designer.cs
- src/AccessibilityInsights.SharedUx/Properties/Resources.Designer.cs
- src/AccessibilityInsights.VersionSwitcher/Properties/Resources.Designer.cs
- src/AccessibilityInsights.sln
- src/AccessibilityInsights/Properties/Resources.Designer.cs
- tools/WildlifeManager/src/WildlifeManager.sln
- tools/WildlifeManager/src/WildlifeManager/Properties/Resources.Designer.cs
- tools/WildlifeManager/src/WildlifeManager/Properties/Settings.Designer.cs
This PR moves us from VS2019 to VS2022. The solution, project and resource files were manually updated. The pipeline files were manually edited and required some trial and error. I originally updated the Roslyn analyzers version number from 16.0 to 17.0, but that failed, so they're intentionally remaining at 16.0. In the test tasks, I tried both 16.0 and 17.0 for `vsTestVersion`. Reading the [docs](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/vstest?view=azure-devops), though, this parameter is optional and things worked once I removed the parameter.
A successful run of the signed pipeline can be found [here](https://dev.azure.com/mseng/1ES/_build/results?buildId=17666697&view=results).
Use the current tools
- [n/a] Addresses an existing issue
> chore: Move to VS2022

- src/AccessibilityInsights.Extensions.AzureDevOps/FileIssue/IssueFileForm.cs
This PR updates the File Issue dialog's state machine to detect when an authentication redirect is taking place and confirm the dialog can reach the page without the query parameters before visiting the full pre-populated issue template.
Addresses issue #1398 
The error state in #1398 appears to happen because the `WebView2` dialog that opens during the File Issue flow does not load with the cached credentials from the ADO connection, causing the dialog to redirect to AAD endpoints as it logs in. These redirects extend the url and include the original query parameters in addition to new query parameters that allow for post-authentication redirection to the original page. These new urls are both past the 2000-character limit and prevent the dialog from ever reaching the original url. We …
> fix: Ensure ADO file issue dialog can reach authenticated page

- src/AccessibilityInsights.VersionSwitcher/EventLogger.cs
- src/AccessibilityInsights.VersionSwitcher/InstallationEngine.cs
- src/AccessibilityInsights.VersionSwitcher/InstallationOptions.cs
- src/AccessibilityInsights.VersionSwitcher/Properties/AssemblyInfo.cs
This PR fixes various spelling and typographical errors found in strings and comments in the `AccessibilityInsights.VersionSwitcher` namespace.
> chore: Fix various spelling and typographical errors in source code comments and strings (AccessibilityInsights.VersionSwitcher namespace)

- src/AccessibilityInsights.SharedUx/Controls/ColorChooser.xaml.cs
- src/AccessibilityInsights.SharedUx/Controls/ColorPicker/ColorPickerControl.xaml.cs
- src/AccessibilityInsights.SharedUx/Controls/CustomControls/AutomatedChecksCustomListControl.xaml.cs
- src/AccessibilityInsights.SharedUx/Controls/EventConfigurationControl.xaml.cs
- src/AccessibilityInsights.SharedUx/Controls/EventRecordControl.xaml.cs
- src/AccessibilityInsights.SharedUx/Controls/HierarchyControl.xaml.cs
- src/AccessibilityInsights.SharedUx/Controls/InspectTabsControl.xaml.cs
- src/AccessibilityInsights.SharedUx/Controls/ScannerResultControl.xaml.cs
- src/AccessibilityInsights.SharedUx/Controls/SettingsTabs/ConnectionControl.xaml.cs
- src/AccessibilityInsights.SharedUx/Controls/TestTabs/AutomatedChecksControl.xaml.cs
- src/AccessibilityInsights.SharedUx/Controls/TestTabs/TabStopControl.xaml.cs
This PR fixes various spelling and typographical errors found in strings and comments in the `AccessibilityInsights.SharedUx.Controls` namespace.
> chore: Fix various spelling and typographical errors in source code comments and strings (AccessibilityInsights.SharedUx.Controls namespace)

- src/AccessibilityInsights.SharedUx/Highlighting/ClearOverlayDriver.cs
- src/AccessibilityInsights.SharedUx/Highlighting/Highlighter.cs
- src/AccessibilityInsights.SharedUx/Highlighting/HollowHighlightDriver.cs
- src/AccessibilityInsights.SharedUx/Highlighting/ImageHighlighter.cs
- src/AccessibilityInsights.SharedUx/Highlighting/ImageOverlayDriver.cs
- src/AccessibilityInsights.SharedUx/Highlighting/LineBorder.cs
- src/AccessibilityInsights.SharedUx/Highlighting/TextRangeHilighter.cs
- src/AccessibilityInsights.SharedUx/Highlighting/TextTip.cs
- src/AccessibilityInsights.SharedUx/Highlighting/WindowHighlighterBase.cs
This PR fixes various spelling and typographical errors found in strings and comments in the `AccessibilityInsights.SharedUx.Highlighting` namespace.
> chore: Fix various spelling and typographical errors in source code comments and strings (AccessibilityInsights.SharedUx.Highlighting namespace)

- src/AccessibilityInsights.SharedUx/Properties/Resources.Designer.cs
- src/AccessibilityInsights.SharedUx/Properties/Resources.resx
- src/AccessibilityInsights.SharedUx/Resources/Dark/Brushes.xaml
- src/AccessibilityInsights.SharedUx/Settings/AppLayout.cs
- src/AccessibilityInsights.SharedUx/Settings/ConfigurationBase.cs
- src/AccessibilityInsights.SharedUx/Settings/ConfigurationModel.cs
- src/AccessibilityInsights.SharedUx/Telemetry/ReportExceptionBuffer.cs
- src/AccessibilityInsights.SharedUx/Utilities/ExtensionMethods.cs
- src/AccessibilityInsights.SharedUx/Utilities/HelperMethods.cs
- src/AccessibilityInsights.SharedUx/Utilities/InstallationInfo.cs
- src/AccessibilityInsights.SharedUx/Utilities/ReferenceHolder.cs
This PR fixes spelling and typographical errors found in strings and comments in various namespaces under `AccessibilityInsights.SharedUx`.
> chore: Fix various spelling and typographical errors in source code comments and strings (AccessibilityInsights.SharedUx namespaces)

- src/AccessibilityInsights.SharedUx/Settings/ConfigurationConstants.cs
- src/AccessibilityInsights.SharedUx/Settings/ConfigurationModel.cs
- src/AccessibilityInsights.SharedUxTests/Resources/ConfigSettings.json
- src/AccessibilityInsights.SharedUxTests/Settings/ConfigurationModelTests.cs
- src/AccessibilityInsights/MainWindow.xaml.cs
Remove support for the `DisableDarkMode` config setting. This setting has no UI and required manual editing of the config file.
When dark mode was introduced in #719, it was gated behind a non-UI config setting named `EnableDarkMode` so that people had to explicitly _opt in_ to use dark mode. When dark mode was enabled by default in #764, we provided a non-UI config setting named `DisableDarkMode` so that people had a way to _opt out_ from dark mode in AIWin. Both of these settings were included because we were concerned about dark mode bugs that could potentially block usability. That was 2 years ago and dark mode has matured a lot since then, so this config setting can now be removed.
> Note: After the PR has been created, certain checks will be kicked off. All of these checks must pass …
> chore: Remove DisableDarkMode config setting

- build/NetFrameworkRelease.targets
Embed symbol (PDB) files into the shipping assemblies and enable SourceLink. This is similar to what we did for Axe.Windows in [#719](https://github.com/microsoft/axe-windows/pull/719) and [#727](https://github.com/microsoft/axe-windows/pull/727). In this case, though, we're moving directly to centrally managed settings, instead of first adding them in the projects, then centralizing them.
A recent issue included a dump file in which the symbols did not resolve (because they aren't indexed). Looking at crash reports, the embedded symbols in Axe.Windows are getting recognized, so embedding symbols in AIWin should be helpful. It increases the file size by about 20%, but that's a small price to pay if we have better debugging support.
I tested this by building a signed build from this …
> chore: Embed symbols and SourceLink in released binaries

- docs/TelemetryDetails.md
- src/AccessibilityInsights.SharedUx/Controls/TestTabs/ColorContrast.xaml.cs
- src/AccessibilityInsights.SharedUx/Telemetry/TelemetryAction.cs
- src/AccessibilityInsights.SharedUx/Telemetry/TelemetryProperty.cs
This PR adds telemetry to report:
* Whether automatic colour contrast detection is enabled/disabled by the user.
* The size (width * height) of bitmaps run under automatic colour contrast detection.
* The confidence reported by automatic colour contrast detection.
The telemetry schema is compatible with that introduced in #1404.
We are considering disabling or removing automatic colour contrast detection due to a propensity to provide inaccurate results but want to assess impact first.
Related to #144, #537, #996, #1244, #1387.
This PR leaves automatic colour contrast detection as-is, only adding telemetry. No changes to functionality have been made.
- [n/a] Run through of all [test scenarios](https://github.com/Microsoft/accessibility-insights-windows/blob/main/docs/Scenarios.md) …
> Add telemetry for auto colour contrast detection

- build/signedbuild.yml
The version of the ADO signing task that we've been using has been deprecated, causing our signed build to break. This simply bumps the task to the latest version. None of the parameters needed to be updated. Validation build is at https://dev.azure.com/mseng/1ES/_build/results?buildId=18305232&view=results.
We need to be able to sign to ship.
> chore: Use newer signing plugin

- src/AccessibilityInsights.SharedUx/Properties/Resources.Designer.cs
- src/AccessibilityInsights.SharedUx/Properties/Resources.resx
- src/AccessibilityInsights/Modes/CCAModeControl.xaml.cs
This PR disables automatic colour contrast detection by default and adds additional explanatory text to reduce possible user confusion.
Related to #996. Follow-up of #1427.
> Chore: Disable automatic colour contrast detection by default

- src/AccessibilityInsights.CommonUxComponents/Controls/ProgressRingControl.xaml.cs
Accessibility Insights for Windows has an option to play a sound when scanning, but it is only honoured when the system screen reader flag is set.
Remove the SR flag check. We might bring it back in another location if we need it down the track.
* Run the latest canary build with the sr flag set (run NVDA with no command line options).
*  With the option to play a sound while scanning active, observe that the Windows NFC connection sound is played while scanning a complex app (such as `devenv`).
* Run the latest canary build without the sr flag set (run nvda with `--no-sr-flag` on the command line).
*  With the option to play a sound while scanning active, observe that no sound is played while scanning a complex app (such as `devenv`).
* Run a build of this PR with the SR flag set and …
> Play sound when scanning independent of the screen reader flag

- src/AccessibilityInsights.SharedUx/ActionViews/NotSupportActionView.xaml
- src/AccessibilityInsights.SharedUx/ActionViews/NotSupportActionView.xaml.cs
- src/AccessibilityInsights.SharedUx/Properties/Resources.Designer.cs
- src/AccessibilityInsights.SharedUx/Properties/Resources.resx
Revise the unsupported action dialog as outlined in #1420. This replaces a button that does nothing with directions of how to use AIWin's issues to request support for an unsupported pattern action. These dialogs are not themed in dark mode.
Mode | Before | After
Light/Dark | ![image](https://user-images.githubusercontent.com/45672944/195468699-4ad04a33-3881-457b-9119-f7e803f2beff.png) | ![image](https://user-images.githubusercontent.com/45672944/195468574-0c5b013f-b712-403b-bf16-f3f78ada611c.png)
Aquatic | ![image](https://user-images.githubusercontent.com/45672944/195468772-f7ea18e0-ecf3-4a71-81da-b72ca43d9215.png) | ![image](https://user-images.githubusercontent.com/45672944/195468374-92a61a27-10ad-46fd-9da1-dbe56101c8d1.png)
Desert | …
> fix: Provide effective way for user to request Pattern Action

- build/NetFrameworkAll.targets
- build/signedbuild.yml
- docs/NewProject.md
- docs/SetUpDevEnv.md
- docs/TelemetryDetails.md
- src/AccessibilityInsights.CustomActions.Package/CustomActions.Package.csproj
- src/AccessibilityInsights.Extensions.AzureDevOpsTests/app.config
- src/AccessibilityInsights.Extensions.TelemetryTests/app.config
- src/AccessibilityInsights.SharedUxTests/app.config
- src/AccessibilityInsights.VersionSwitcher/App.config
- src/AccessibilityInsights/App.config
- src/MSI/Product.wxs
- src/MsiFileTests/WxsValidationTests.cs
- src/UITests/app.config
We need .NET Framework 4.8 to address some accessibility issues, because the required properties are not exposed in .NET 4.7.2. Telemetry indicates that 98.1% of our current users are running on systems where .NET Framework 4.8 is already installed and will not be impacted by this change. The remaining 1.9% will experience a failed upgrade until they install a newer version of .NET Framework 4.8. They can learn of this requirement in any of the following ways:
1. Read the release notes (accessible directly from the upgrade dialog)
2. Uninstall and reinstall AIWin (the installer will tell the user to install the new version)
3. Search for a GitHub issue that we will create after this PR merges
Note: The primary change is captured in the change to `build\NetFrameworkAll.targets`, then the …
> chore: Target .NET Framework 4.8

- src/AccessibilityInsights/Modes/TestModeControl.xaml
Bug [1998198](https://mseng.visualstudio.com/DefaultCollection/1ES/_workitems/edit/1998198) points out that the test model control reports the wrong information in the test nav bar. Screen readers report "Automated checks 2 of 3" and "Tab stops 3 of 3". This is because the non-focusable item in the list is getting counted. We can't prevent the first item from getting counted, but we can override the `PositionInSet` and `SizeOfSet` properties so the properties are reported as "Automated checks 1 of 2" and "Tab stops 2 of 2"
Validated with NVDA
Fix accessibility bug
> fix: Override default indexing values in test mode

- src/AccessibilityInsights.SharedUx/Controls/CustomControls/CheckableTreeView.cs
- src/AccessibilityInsights.SharedUx/Controls/CustomControls/CheckableTreeViewDataItemAutomationPeer.cs
- src/AccessibilityInsights.SharedUx/Controls/CustomControls/CheckableTreeViewItem.cs
- src/AccessibilityInsights.SharedUx/Controls/CustomControls/CheckableTreeViewItemAutomationPeer.cs
- src/AccessibilityInsights.SharedUx/Controls/EventConfigTabControl.xaml
- src/AccessibilityInsights.SharedUx/Controls/EventConfigTabControl.xaml.cs
- src/AccessibilityInsights.SharedUx/Properties/Resources.Designer.cs
- src/AccessibilityInsights.SharedUx/Properties/Resources.resx
- src/AccessibilityInsights.SharedUx/ViewModels/EventConfigNodeViewModel.cs
Building off of @RobGallo's branch to fix https://github.com/microsoft/accessibility-insights-windows/issues/1323 by implementing the TogglePattern in order to ensure that checkboxes in the event configuration report being checked/ unchecked with a screenreader. Tested with NVDA.
Supersedes https://github.com/microsoft/accessibility-insights-windows/pull/1464.
Addresses https://github.com/microsoft/accessibility-insights-windows/issues/1323
> fix: Announce tree view item as checked/unchecked

- build/build-and-unit-tests.yml
While investigating a test failure, I noticed that the debug leg of our PR tests is always using the release configuration. This PR changes the yml file to use the parameterized configuration
Run all tests
> chore: Select unit tests correctly

- src/AccessibilityInsights.SharedUx/Controls/CustomControls/AutomatedChecksCustomListControl.xaml.cs
- src/AccessibilityInsights.SharedUx/Controls/PropertyInfoControl.xaml
- src/AccessibilityInsights.SharedUx/Controls/PropertyInfoControl.xaml.cs
- src/AccessibilityInsights.SharedUx/Utilities/ExtensionMethods.cs
By default when a `ScrollViewer` is wrapping a `Grid`, WPF scrolls to focus on the element being selected in the grid. This is the behavior we want for vertical scrolling, but this causes some jumpy behavior in the horizontal scrollbar, as described in #1150. The horizonal jumps would make more sense if the user were navigating between cells horizontally, but since we treat the properties grid as a list and only allow navigation between rows (as opposed to between cells), the default behavior just looks odd. As a result, this PR overrides WPF default behavior by keeping vertical navigation the same but removing the horizontal component.
Addresses issue https://github.com/microsoft/accessibility-insights-windows/issues/1150
Behavior after this change:
[Description: Gif of AIWin in live …
> fix: Prevent horizontal shifting in properties grid

- src/AccessibilityInsights.SharedUx/Controls/PropertyInfoControl.xaml.cs
Fix bug in https://github.com/microsoft/accessibility-insights-windows/pull/1475 in which search bar height was not taken into account in vertical scrolling logic.
Behavior after this PR:
[Description: Gif of AIWin in live inspect mode. User navigates arounds property grid, which has the search bar visible at the top. Navigation is the same as before but horizontal jumps have been removed.]
Fix bug
> fix: Take searchbar height into account for vertical scroll

- build/signedbuild.yml
#1480 moved our build-generated files from `$(TEMP)` to `.\src\bld`, which was a good thing. It had the unexpected side effect of making the compliance release job of the signed pipeline fail. This happens because now these generated files are being checked for a copyright header...which they lack.
The PR build, which also performs the same check, had no such problem. Comparing the two pipelines, the PR pipeline checks for copyright headers immediately, while the signed pipeline checks a little later. This PR modifies the signed pipeline to perform the copyright header check immediately, so we have parity between the pipelines.
Fix signed pipeline
My first thought was to add the copyright headers to the generated files, then I wondered why we had a difference between the 2 pipelines. The …
> fix: Run license header checks earlier

- src/.editorconfig
- src/AccessibilityInsights.Extensions.AzureDevOps/ConfigurationControl.xaml.cs
- src/AccessibilityInsights.Extensions.AzureDevOps/ForcedDependencies.cs
- src/AccessibilityInsights.Extensions.GitHubAutoUpdate/ExceptionReporter.cs
- src/AccessibilityInsights.ExtensionsTests/ContainerUnitTests.cs
- src/AccessibilityInsights.SetupLibrary/OverridableConfig.cs
- src/AccessibilityInsights.SetupLibrary/SettingsDictionary.cs
- src/AccessibilityInsights.SharedUx/ActionViews/GeneralActionView.xaml.cs
- src/AccessibilityInsights.SharedUx/ActionViews/ReturnA11yElementsView.xaml.cs
- src/AccessibilityInsights.SharedUx/ActionViews/TextRangeActionView.xaml.cs
- src/AccessibilityInsights.SharedUx/Behaviors/DropDownButtonBehavior.cs
- src/AccessibilityInsights.SharedUx/Controls/CustomControls/AutomatedChecksCustomListControl.xaml.cs
- src/AccessibilityInsights.SharedUx/Controls/CustomControls/CheckableTreeViewDataItemAutomationPeer.cs
- src/AccessibilityInsights.SharedUx/Controls/EventConfigurationControl.xaml.cs
- src/AccessibilityInsights.SharedUx/Controls/EventRecordControl.xaml.cs
- src/AccessibilityInsights.SharedUx/Controls/HierarchyControl.xaml.cs
- src/AccessibilityInsights.SharedUx/Controls/NPISlider.cs
- src/AccessibilityInsights.SharedUx/Controls/TestTabs/AutomatedChecksControl.xaml.cs
- src/AccessibilityInsights.SharedUx/Controls/TestTabs/TabStopControl.xaml.cs
- src/AccessibilityInsights.SharedUx/Highlighting/OverlayHighlighter.cs
- src/AccessibilityInsights.VersionSwitcher/MainWindow.xaml.cs
- src/AccessibilityInsights/Modes/EventModeControl.xaml.cs
- src/AccessibilityInsights/Modes/LiveModeControl.xaml.cs
- src/AccessibilityInsights/Modes/SnapshotModeControl.xaml.cs
- src/AccessibilityInsights/Modes/TestModeControl.xaml.cs
This PR addresses some issues around analyzer suggestions:
1. Suppress suggestions from [IDE0054 and IDE0074](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0054-ide0074), since they require C# version 8.0 and .NET Framework 4.8 defaults to C# version 7.3
2. Use null propagation as suggested by [IDE0031](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0031)
3. Rename unused method parameters as described in the docs for [CA1801](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1801) and [IDE0060](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0060). This allows us to remove the pragmas that existed to disable CA1801. If we had empty parameter …
> chore: Address analyzer suggestions

- src/MsiFileTests/WxsValidationTests.cs
This fixes some issues with the MSI checker--I discovered these when I added a file to the VersionSwitcher but the test still succeeded:
1. Due to a logic error, files were returned _only_ if a set of excluded files was provided. This empty set was not caught as a problem. These have both been fixed.
2. We weren't passing the correct component names in 2 places, so we were returning empty sets of files. This empty set was also not caught as a problem. These have been fixed.
3. As written, the checker assumed that everything in a component comes from the same build folder, which we intentionally don't do because of signing requirements. Now we ignore the path and use just the file name (with extension) to ensure that the correct set of files is found.
Make test detect errors (which is why …
> chore: Fix gap in WxsValidationTests

- .gitignore
Current versions of VS store user-specific settings in `launchSettings.json`. This file shouldn't be in the repo, so adding it to the `.gitignore` file seems appropriate.
Enable local debugging without risk of contaminating the repo with these files.
> chore: Ignore launchSettings.json files

- src/AccessibilityInsights.SharedUx/Controls/EventRecordControl.xaml
Address https://github.com/microsoft/accessibility-insights-windows/issues/1438 by implementing the suggestion to set name on element to "{Event Type} from {Event Source} at {Event Time}".
Addresses issue https://github.com/microsoft/accessibility-insights-windows/issues/1438
> fix: Give items in events data grid readable UIA name

- src/AccessibilityInsights.SetupLibrary/GitHubWrapper.cs
We currently use hardcoded links to fetch our upgrade manifests. We're changing these to fwlink values that we can later redirect to the signed manifests once that work is complete. For the moment, the redirects point to the same locations as the old hardcoded links. This is easy to validate by 
Tested locally and confirmed that redirects and updates work as expected.
Part of the feature to improve security of our upgrader.
I have a branch with 49 updated files. The hope is to break that set of changes down into smaller pieces to make it more manageable. You can confirm that the redirects are the same by copying/pasting the old and new links into your browser and comparing the resulting JSON that gets returned.
- [n/a] Run the production version of …
> feat(upgrader-security): Use redirectable links to obtain the upgrade manifests

- build/build-and-unit-tests.yml
- build/signedbuild.yml
It's hard to tell what environment variables are available in the pipeline. This adds a task that displays the variables so it's easier to create scripts. I used this while working on the signed manifest and felt that it offered good value for almost no cost (it adds about 2 seconds to each build), so I opted to apply it generally.
Make it easier to understand available inputs for writing scripts
> chore: Show environment variables in pipelines

- build/signedbuild.yml
This PR adds 2 things:
1. Include the signed manifest in BinSkim and signing validation (not strictly necessary since we don't directly ship the assembly, but it seemed appropriate since we rely on the contents being secured)
2. Publish the manifest as a build artifact so that the release pipeline can easily consume it
The manifest is published as the `manifest` artifact of this test build of the signed pipeline: https://dev.azure.com/mseng/1ES/_build/results?buildId=18867199&view=artifacts&pathAsName=false&type=publishedArtifacts 
Part of the upgrader security work
- [n/a] Attach any …
> feat(upgrader-security): Validate and publish the signed manifest

- build/NetFrameworkRelease.targets
Current builds are cluttered with the following warning:
```
The .NET SDK has newer analyzers with version '7.0.0' than what version '6.0.0' of 'Microsoft.CodeAnalysis.NetAnalyzers' package provides. Update or remove this package reference.
```
https://www.nuget.org/packages/Microsoft.CodeAnalysis.NetAnalyzers has been in v7 preview for about 9 months but hasn't yet shipped. This PR bumps to the most recent preview version to reduce the clutter, with the expectation that dependabot will notify us when v7 is officially released. These changes were made by directly editing the .targets file, but are based on IDE-generated changes from https://github.com/microsoft/axe-windows/pull/853.
Reduce noise in builds (local and pipeline), use latest tools
We want to pin our versions (as opposed to …
> chore: Update to newer NetAnalyzers

- src/AccessibilityInsights.Extensions.DiskLoggingTelemetry/LocalTelemetry.cs
- src/AccessibilityInsights.Extensions.DiskLoggingTelemetryTests/LocalTelemetryUnitTests.cs
- src/AccessibilityInsights.Extensions.Telemetry/AITelemetry.cs
- src/AccessibilityInsights.Extensions.Telemetry/ITelemetryClientWrapper.cs
- src/AccessibilityInsights.Extensions.Telemetry/TelemetryClientWrapper.cs
- src/AccessibilityInsights.Extensions.TelemetryTests/AITelemetryTests.cs
- src/AccessibilityInsights.Extensions.TelemetryTests/TelemetryClientWrapperUnitTests.cs
- src/AccessibilityInsights.Extensions/Interfaces/Telemetry/ITelemetry.cs
- src/AccessibilityInsights.ExtensionsTests/DummyClasses/DummyTelemetry.cs
- src/AccessibilityInsights.SharedUx/Telemetry/ITelemetrySink.cs
- src/AccessibilityInsights.SharedUx/Telemetry/Logger.cs
- src/AccessibilityInsights.SharedUx/Telemetry/TelemetrySink.cs
- src/AccessibilityInsights.SharedUxTests/Telemetry/LoggerUnitTests.cs
- src/AccessibilityInsights.SharedUxTests/Telemetry/TelemetrySinkUnitTests.cs
- src/AccessibilityInsights/MainWindow.xaml.cs
We use [ApplicationInsights](https://www.nuget.org/packages/Microsoft.ApplicationInsights) for our telemetry, which buffers telemetry events for about 30 seconds, then sends them in a burst. This works fine most of the time, but we lose telemetry events that occur in the last few seconds of the app's lifetime. This is especially noticeable with updates, since the app exits within milliseconds of creating the event.
This PR connects the MainWindow's existing onClosed handler to the `Flush` method from ApplicationInsights. Due to how the code is structured, it goes through the following layers:
- `MainWindow.onClosed` calls `Logger.FlushAndShutDown`
- `Logger.FlushAndShutDown` calls (through an interface) into `AITelemetrySink.FlushAndShutDown`
- `AITelemetrySink.FlushAndShutDown` calls …
> chore: Flush telemetry at app shutdown

- src/AccessibilityInsights.Extensions.AzureDevOps/ConfigurationControl.xaml
- src/AccessibilityInsights.Extensions.AzureDevOps/ConfigurationControl.xaml.cs
- src/AccessibilityInsights.Extensions.AzureDevOps/Models/ConfigurationViewModel.cs
- src/AccessibilityInsights.SharedUx/Controls/CustomControls/ScannerResultCustomListControl.xaml
- src/AccessibilityInsights.SharedUx/Controls/EventDetailControl.xaml
- src/AccessibilityInsights.SharedUx/Controls/PropertyInfoControl.xaml
- src/AccessibilityInsights.SharedUx/Controls/ScannerResultControl.xaml
- src/AccessibilityInsights.SharedUx/Controls/ScannerResultControl.xaml.cs
Fix the first batch of debug errors from https://github.com/microsoft/accessibility-insights-windows/issues/1477:
| Error | Change | Notes |
|---|---|---|
| `BindingExpression path error: 'SnippetLink' property not found on 'object'...` | `ScannerResultControl.xaml.cs` | Explicitly set data context to null on start up so it doesn't try to populate properties that do not exist yet | 
| `BindingExpression path error: 'projects' property not found on 'object'...` | `ConfigurationControl.xaml.cs` | Explicitly set items source to null on start up so it doesn't try to populate properties that do not exist yet |
| `Cannot create default converter to perform 'two-way' conversions...` | `EventDetailControl.xaml` and `PropertyInfoControl.xaml` | I can't discern a reason that the `OneWayToSource` …
> fix: Fix debug build errors

- src/AccessibilityInsights.SharedUx/Controls/EventConfigTabControl.xaml
Fix bug introduced in https://github.com/microsoft/accessibility-insights-windows/pull/1471 with dark mode style for event config tree view. 
Before this change:
[Description: screenshot of AI win event config tree view in dark mode. Tree view is too light and unreadable.]
After this change:
[Description: screenshot of AI win event config tree view in dark mode. Tree view is appropriately dark.]
Address issue https://github.com/microsoft/accessibility-insights-windows/issues/1503
> fix: Correct checkable tree view style target

- src/AccessibilityInsights/Modes/LiveModeControl.xaml
In #1512, we added a new way to discover keyboard shortcuts. In doing so, we created a new link instead of using the one that already existed and was used at https://github.com/microsoft/accessibility-insights-windows/blob/main/src/AccessibilityInsights.SharedUx/Dialogs/StartUpModeControl.xaml#L159. This converts both locations to using the existing link. I'll delete the newly created link after this deploys to the Canary release channel.
Verified by clicking link from Live Inspect page and confirming that it ends up where expected.
Avoid redundancy
- [n/a] Attach any screenshots / GIF's that …
> chore: Use existing link instead of new one

- src/AccessibilityInsights.SetupLibrary/REST/GitHubClient.cs
This CodeQL [alert](https://onees.lgtm.microsoft.com/projects/u/gh/microsoft%2Faccessibility-insights-windows%2Ftree%2Fmain?mode=list) is calling out the fact that when we make web calls, we're not asking for SSL certificates to be checked. This PR simply adds the flag to request the SSL check. It's a global state for all `WebClient` objects in the entire process.
Validated against manifest files both in GitHub repos and in Azure blob storage.
Fix issue found by CodeQL
> Note: After the PR has been created, certain checks will be kicked …
> chore: Enforce SSL security check

- src/AccessibilityInsights.SharedUx/Controls/HierarchyControl.xaml.cs
- src/AccessibilityInsights.SharedUx/Controls/InspectTabsControl.xaml
Fix final debug warnings in https://github.com/microsoft/accessibility-insights-windows/issues/1477:
- Changes in [HierarchyControl.xaml.cs](https://github.com/microsoft/accessibility-insights-windows/compare/main...sfoslund:FixDebugErrs?expand=1#diff-e370bcbcf4e6b44f06f8a02fc81900781a8c9bf05fc716144476745d3524d4c2)
- Addresses error: `System.Windows.Data Error: 40 : BindingExpression path error: 'IsLiveMode' property not found on 'object' ''ElementDataContext' (HashCode=25763023)'. BindingExpression:Path=IsLiveMode; DataItem='ElementDataContext' (HashCode=25763023); target element is 'Button' (Name='btnMenu'); target property is 'NoTarget' (type 'Object')`
- Explanation: btnMenu's data context is eventually assigned [here](https://github.com/microsoft/accessibility-insights-windows/blob/m …
> fix: Fix debug errors

- src/AccessibilityInsights.CommonUxComponents/Controls/ProgressRingControl.xaml.cs
- src/AccessibilityInsights.CommonUxComponents/Controls/SelectedSound.cs
- src/AccessibilityInsights/MainWindow.xaml
The `ProgressRingControl` is currently hardcoded to play the same sound resource, regardless of where it's used. This PR adds support for different sounds in different contexts, all controllable by XAML. Changing the SelectedSound value more than once will throw an Exception. These are the steps to add a new sound in a `ProgressRingControl`; steps 1-3 make the sound available to XAML, and step 4 enables the sound for the control:
1. Add the new sound resource to `CommonUxCompoenents.csproj`
2. Add a corresponding entry to the `SelectedSound` enum
3. Update `ProgressRingControl.GetResourceForSound` to map the new `SelectedSound` enum to the name of the new sound resource
4. Add the `SelectedSound` attribute in the XAML that identifies the `ProgressRingControl`
Part of work to improve audio …
> feat(audio-feedback): Add support for selectable sounds in ProgressRingControl

- src/AccessibilityInsights/Modes/LiveModeControl.xaml
- src/AccessibilityInsights/Modes/LiveModeControl.xaml.cs
This PR improves discoverability of the keyboard control scheme by moving the usage hint to earlier in the tab order and causing it to focus immediately on app launch.
Closes #1512.
See linked issue.
> fix: Move the keyboard help hint to the beginning of the tab order

- src/AccessibilityInsights/MainWindow.xaml
- src/AccessibilityInsights/Modes/TestModeControl.xaml
PR #1523 added the ability to choose sounds to the `ProgressRingControl`, where the default sound was `NoSound`. That change set the `Scanner` sound to the wrong `ProgressRingControl`, effectively removing the sound while scanning. This PR simply moves the scanning sound to the appropriate `ProgressRingControl`. Confirmed that it plays the scanning sound when scanning takes a long time.
Fix regression
> feat(audio-feedback): Set scanner sound correctly

- src/AccessibilityInsights.SharedUx/Controls/CustomControls/CheckableTreeViewDataItemAutomationPeer.cs
- src/AccessibilityInsights.SharedUx/Controls/CustomControls/ToggleMenuItem.cs
- src/AccessibilityInsights.SharedUx/Controls/CustomControls/ToggleMenuItemAutomationPeer.cs
- src/AccessibilityInsights.SharedUx/Controls/HierarchyControl.xaml
- src/AccessibilityInsights.SharedUx/Controls/HierarchyControl.xaml.cs
- src/AccessibilityInsights.SharedUx/Properties/Resources.Designer.cs
- src/AccessibilityInsights.SharedUx/Properties/Resources.resx
- src/AccessibilityInsights.SharedUx/Utilities/ExtensionMethods.cs
Fixes the checked/ unchecked instances in https://github.com/microsoft/accessibility-insights-windows/issues/1514
Addresses issue https://github.com/microsoft/accessibility-insights-windows/issues/1514
While checking that this did not disrupt any existing styling, I noticed/ filed https://github.com/microsoft/accessibility-insights-windows/issues/1528 to be addressed separately. 
> fix: replace hardcoded checked/ unchecked names with toggle pattern

- src/AccessibilityInsights/MainWindow.xaml.cs
- src/AccessibilityInsights/Properties/Resources.Designer.cs
- src/AccessibilityInsights/Properties/Resources.resx
Replace hardcoded "x of 3" in element automation name with proper UIA `SizeOfSet` and `PositionInSet` properties. This PR addresses the 3 elements in the left hand side navigation bar (the `Inspect mode`, `Fastpass mode` and `Color contrast analyzer` buttons)
Addresses part of https://github.com/microsoft/accessibility-insights-windows/issues/1514
This is one of several PRs to address the various issues discussed in https://github.com/microsoft/accessibility-insights-windows/issues/1514
> fix: Use size of and position in set for top nav bar elements

- src/AccessibilityInsights/MainWindowHelpers/ControlHelper.cs
- src/AccessibilityInsights/Properties/Resources.Designer.cs
- src/AccessibilityInsights/Properties/Resources.resx
Replace hardcoded "x of 5" in element automation name with proper UIA `SizeOfSet` and `PositionInSet` properties. This PR addresses the elements along the top level live inspect menu (the "what to select menu", the highlighter on button, the pause/ resume button, the timer button, and the load test or event file button)
Addresses part of https://github.com/microsoft/accessibility-insights-windows/issues/1514
This is one of several PRs to address the various issues discussed in https://github.com/microsoft/accessibility-insights-windows/issues/1514
> fix: Use size of and position in set for main window visible elements

- src/AccessibilityInsights/MainWindow.xaml
- src/AccessibilityInsights/MainWindow.xaml.cs
- src/AccessibilityInsights/Properties/Resources.Designer.cs
- src/AccessibilityInsights/Properties/Resources.resx
Replace hardcoded "x of 2" in element automation name with proper UIA `SizeOfSet` and `PositionInSet` properties. This PR addresses the 2 elements at the bottom of the left hand nav bar, the account config and app settings buttons.
Addresses part of https://github.com/microsoft/accessibility-insights-windows/issues/1514
This is one of several PRs to address the various issues discussed in https://github.com/microsoft/accessibility-insights-windows/issues/1514
> fix: Use size of and position in set for lower nav bar elements

- src/AccessibilityInsights.SharedUx/Dialogs/EventConfigDialog.xaml
- src/AccessibilityInsights.SharedUx/Properties/Resources.Designer.cs
- src/AccessibilityInsights.SharedUx/Properties/Resources.resx
Replace hardcoded "x of 3" in element automation name with proper UIA `SizeOfSet` and `PositionInSet` properties. This PR addresses the 2 tabs in in the event config dialog, which can be found as follows:
- Open AI win in live view and inspect any app
- Select 'More options" and "Listen to events" in drop downs.
- In right hand side "Configuration" pane, expand the "My Events" item in the events list
- Select the "Edit my events..." link under "My Events"
- See event configuration dialog pop up. Observe the 2 "Events" and "Properties" tabs in the dialog
Note that this PR changed the size of set value from 3 to 2. There are only 2 tabs so I am not sure why this was ever 'x of 3'. If I'm missing something here, please let me know and I will change it back.
Addresses part of …
> fix: Use size of and position in set for event config dialog tabs

- src/AccessibilityInsights.Extensions.AzureDevOps/AzureDevOpsIntegration.cs
- src/AccessibilityInsights.Extensions.AzureDevOpsTests/AzureDevOpsIntegrationTests.cs
Replace non-breaking spaces with breaking spaces when filing ADO bugs
Addresses #1545
ADO issue test before and after the change
When | Link | Text
Before | [#346](https://dev.azure.com/ada-cat/accessibility/_workitems/edit/346/) | Provide a UI Automation Name property for the element that: -?Concisely identifies the element, AND -?Does not include the same text as the elemen...open attached A11y test file for full details.
After | [#347](https://dev.azure.com/ada-cat/accessibility/_workitems/edit/347) | Provide a UI Automation Name property for the element that: - Concisely identifies the element, AND - Does not include the same text as the elemen...open attached A11y test file for full details.
- [n/a] Run the production version of …
> fix: Improve handling of non-breaking spaces in ADO issues

- build/signedbuild.yml
- src/PrebuiltThirdPartyNotices/thirdpartynotices.html
The API that we use to generate the `thirdpartynotices.html` has recently developed problems that may or may not be fixed in the near future. The recommendation from the team who owns the API is to commit the file into the repo and maintain it manually. This is far from ideal, but our options are pretty limited. In order to get the best balance, we do the following:
1. The manually curated version of `thirdpartynotices.html` is from the last build that successfully called the API
2. Local builds continue to use the placeholder file
3. The signed build copies the manually curated version over the placeholder version before calling the API
4. If the API succeeds, we get the newly generated file. If it fails, we get the manually curated file
5. Errors from the API are surfaced in the build …
> chore: Workaround for broken thirdpartynotice generator

- src/AccessibilityInsights.SharedUx/Properties/Resources.Designer.cs
- src/AccessibilityInsights.SharedUx/Properties/Resources.resx
This commit updates the production, insider, and canary channel descriptions to reflect the reality of their current usage.
Closes #1548.
> Make channel descriptions more accurate

- src/Manifest/Manifest.csproj
- src/ManifestTests/IntegrationTests.cs
- src/props/prod-version.props
- tools/scripts/create-json-for-manifest.ps1
This improves upgrade manifest _handling_ (content and structure are unmodified) in 2 ways:
1. Rather than needing to manually edit the value of `MinimumProdVersion` in [version.props](https://github.com/microsoft/accessibility-insights-windows/blob/main/src/props/prod-version.props) after each production release, we now populate the manifest's `production_minimum_version` field automatically based on the value of `IsMandatoryProdUpdate`, which will only need to changed if a mandatory upgrade released (which has happened **exactly once since 2019**):
- If `IsMandatoryProdUpdate` is `false` (the usual state), then `production_minimum_version` is the same as the latest non-prerelease release from GitHub. This allows production clients to remain 1 version behind the latest release when this …
> feat(upgrader-security): Improve manifest handling

- src/AccessibilityInsights.Extensions.GitHubAutoUpdate/AutoUpdate.cs
- src/AccessibilityInsights.SetupLibrary/ChannelInfoUtilities.cs
- src/AccessibilityInsights.SetupLibrary/VersionSwitcherWrapper.cs
- src/AccessibilityInsights.SetupLibraryUnitTests/ChannelInfoUtilitiesUnitTests.cs
- src/AccessibilityInsights.VersionSwitcher/InstallationEngine.cs
- src/AccessibilityInsights.VersionSwitcher/InstallationOptions.cs
- src/AccessibilityInsights.VersionSwitcherUnitTests/InstallationEngineUnitTests.cs
Now that all channels are using signed manifests, we can deprecate client support for unsigned manifests. This PR removes the code and tests that supported unsigned manifests. It also adds a test to be sure that we can always read the sign Canary manifest. Strictly speaking, this test is an integration test instead of a unit test, but the unit test class is so small that it seemed reasonable to put both types of tests into the same class.
Complete upgrader security migration.
> feat(upgrader-security): Deprecate unsigned manifests

- src/AccessibilityInsights.SharedUx/Controls/EventRecordControl.xaml
- src/AccessibilityInsights.SharedUx/Controls/HierarchyControl.xaml
- src/AccessibilityInsights.SharedUx/Resources/Styles.xaml
Update styling for menu items such that they adhere to dark mode. This effects the hierarchy settings and event settings menus that were identified in https://github.com/microsoft/accessibility-insights-windows/issues/1528.
Addresses issue https://github.com/microsoft/accessibility-insights-windows/issues/1528
[Image grid description: Screenshots of each menu before and after the styling change in dark and light modes]
| | Before | After |
| - | ------- | ------ |
| Hierarchy settings in light mode | <img width="667" alt="light-livesettings-before" src="https://user-images.githubusercontent.com/16010855/214106081-7250b713-ff0b-43c3-94a2-7306e595333b.png"> | <img width="667" alt="Light-livesettings-after" src="https://user-images.githubusercontent.com/16010855/214106022-723384d7-d4a5-465e-8 …
> fix: Add dark mode styling for nested menu items

- build/signedbuild.yml
- tools/scripts/pipeline/build/create-tsa-config.ps1
The compliance tools that we use are being revised, as shown in the following warnings (adapted from this morning's signed build)
Job | Task | Warning
ComplianceDebug | Run AutoApplicability | This tool is no longer supported. Please remove this build task from your build definition.
ComplianceDebug | Run CredScan | Please upgrade the version of this build task in your build to major version: 3.
ComplianceDebug | Run Roslyn analyzers | Please upgrade the version of this build task in your build to major version: 3.
ComplianceDebug | Run PoliCheck | Please upgrade the version of this build task in your build to major version: 2.
ComplianceDebug | Create Security Analysis Report (CredScan, RoslynAnalyzers, and PoliCheck) | Please upgrade the version of this build task in …
> chore: Update compliance tools to the next generation

- build/signedbuild.yml
- tools/scripts/pipeline/deploy/Canary/prevent_version_backfilling.ps1
- tools/scripts/pipeline/deploy/Canary/set_variables.ps1
- tools/scripts/pipeline/deploy/Prod/cleanup_old_releases.ps1
- tools/scripts/pipeline/deploy/Prod/confirm_release_is_ready_for_prod.ps1
- tools/scripts/pipeline/deploy/Prod/set_variables.ps1
ADO release pipelines are limited to classic pipeline definitions, with no YAML support. Our current release pipelines include 5 inline PowerShell scripts, which are hard to discover and harder to review when changes are needed. After discussion as a team, we opted to add the scripts to the repo, publish them as build artifacts, then have the release pipelines execute the scripts that we consume from the build artifacts. This PR completes the first 2 steps, then we'll change the release pipelines once the artifact exists.
Note that while the consumption pattern will change from inline to an artifact, the scripts themselves will not be changing (caveat: 2 non-functional tweaks were made). The publishing of the `deploy_scripts` artifact occurs in the SignedRelease step, so it happens at the …
> chore: Move deployment scripts into build artifact

- build/signedbuild.yml
The old version of TSA automatically added the branch name to the database, which was kind of wasteful since new databases were created from each non-main branch used for a signed test build. The new version of TSA uses the same database name for all branches, which means that builds from any branch could create noise in the production version. To solve both problems, this PR restricts the TSA upload to just the main branch. All TSA artifacts are created as usual, but the upload task gets skipped. This is based on the method shown [here](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/conditions?view=azure-devops&tabs=yaml%2Cstages). Using a couple of recent builds as reference,
build | branch | `Build.SourceBranch` variable …
> chore: Limit TSA uploads to main branch

- build/signedbuild.yml
This should be the last PR in updating the compliance tools. It does 2 things:
- In the Post-Analysis task of the ComplianceDebug job, we want the pipeline to continue even if errors are uploaded to TSA. While working on Axe.Windows, we discovered that we need to provide inputs to the task to get this behavior. We've mirrored the Axe.Windows inputs here. We're intentionally _not_ adding them in the SignedRelease job, since we don't want to release an improperly signed build--even to Canary.
- We previously added the `TSAV2*` pipeline variables to enable migration from TSA V1 to TSA V2. Now that the migration is complete, we want to drop the `V2` from these variables and maintain just one set of variables. The pipeline variables have already been updated.
The TSA changes were validated by …
> chore: Complete TSA migration

- README.md
- build/signedbuild.yml
- docs/SetUpDevEnv.md
- src/AccessibilityInsights.CustomActions.Package/CustomActions.Package.csproj
- src/AccessibilityInsights.CustomActions/ConfigFileCleaner.cs
- src/AccessibilityInsights.CustomActions/CustomActions.csproj
- src/AccessibilityInsights.CustomActions/SystemShim.cs
- src/AccessibilityInsights.CustomActionsUnitTests/ConfigFileCleanerUnitTests.cs
- src/AccessibilityInsights.CustomActionsUnitTests/CustomActionsUnitTests.csproj
- src/AccessibilityInsights.SetupLibrary/MsiUtilities.cs
- src/AccessibilityInsights.SetupLibrary/SetupLibrary.csproj
- src/AccessibilityInsights.VersionSwitcher/InstallationEngine.cs
- src/AccessibilityInsights.VersionSwitcher/VersionSwitcher.csproj
- src/AccessibilityInsights.sln
- src/AccessibilityInsights/AccessibilityInsights.csproj
- src/MSI/MSI.wixproj
- src/MSI/Product.wxs
- src/MSI/packages.config
- src/Manifest/Manifest.csproj
- src/ManifestTests/IntegrationTests.cs
- src/MsiFileTests/WxsValidationTests.cs
Upgrade WixToolset to v4.0.1
Addresses issue #1641 
In WiX v4, it's easier than ever to build MSIs for each platform (x86, x64, arm64) using the exact same sources (with no conditional code).
The default build output directory for the MSI changes from `bin\$(Configuration)\...` to `bin\$(Platform)\$(Configuration)\...` where Platform = `x86`
This MSI contains suboptimal authoring, especially concerning the Windows Installer Best Practices relating to Component/File relationships. Generally speaking, each Component should have only one File. You can create ComponentGroups to group components as needed, but ComponentGroups don't survive in the MSI (they are an authoring-only concept).
It is NOT considered a best practice to mess with any per-user data (configuration or otherwise) in …
> Upgrade WixToolset to v4.0.1

- tools/scripts/pipeline/deploy/Prod/cleanup_old_releases.ps1
Update the release script to properly clean up all PreRelease (i.e., Canary) releases that are older than the version being released to prod. This used to be part of the Canary release but got lost at some point before we moved the scripts to the repo. Before this change, PreRelease releases only get cleaned up if they're older than `$minProdVersionTag`. After the change, we clean up all PreRelease releases that are older than the first non-PreRelease release.
Automate Canary cleanup. Tested locally with a PAT.
- [n/a] Run the production version of …
> chore: Add code to delete Canary releases

- tools/scripts/pipeline/build/clearly-defined/ValidateScript.bat
- tools/scripts/pipeline/build/clearly-defined/check-clearly-defined.ps1
#1669 had 2 bugs about namespaces:
1. Dependabot adds a `/src` component to the branch name of NuGet component. The script didn't take this into account and we ended up with an incorrect url
2. Dependabot omits the `@` from branch names of npm components that include a namespace. The script didn't take this into accoiunt and we ended up with an incorrect url
The fix in both cases is the same--we add a function to adjust the raw namespace that comes from parsing the branch name. 
It also includes a batch script to aid in script validation. If we encounter future branch names that go awry, we can just add additional test cases and have protection against breakage.
Tune the desired friction of dependabot PR's, keep the generated notices file current
Here is the output of the script:
``` …
```
> fix: Correct dependabot validation

- .github/dependabot.yml
- src/AccessibilityInsights.CustomActionsUnitTests/CustomActionsUnitTests.csproj
- src/AccessibilityInsights.Extensions.AzureDevOpsTests/Extensions.AzureDevOpsTests.csproj
- src/AccessibilityInsights.Extensions.DiskLoggingTelemetryTests/Extensions.DiskLoggingTelemetryTests.csproj
- src/AccessibilityInsights.Extensions.GitHubAutoUpdateUnitTests/Extensions.GitHubAutoUpdateUnitTests.csproj
- src/AccessibilityInsights.Extensions.GitHubUnitTests/Extensions.GitHubUnitTests.csproj
- src/AccessibilityInsights.Extensions.TelemetryTests/Extensions.TelemetryTests.csproj
- src/AccessibilityInsights.ExtensionsTests/ExtensionsTests.csproj
- src/AccessibilityInsights.SetupLibraryUnitTests/SetupLibraryUnitTests.csproj
- src/AccessibilityInsights.SharedUxTests/SharedUxTests.csproj
- src/AccessibilityInsights.VersionSwitcherUnitTests/VersionSwitcherUnitTests.csproj
- src/AccessibilityInsightsUnitTests/AccessibilityInsightsUnitTests.csproj
Since 4.20.x, Moq has introduced a privacy vulnerability that improperly handles user data. https://github.com/moq/moq/issues/1372 
This pins to 4.18.4 until we can confirm that those privacy concerns are resolved.
Privacy/Security
> chore: Pin Moq to 4.18.4

- tools/scripts/pipeline/build/clearly-defined/ValidateScript.bat
- tools/scripts/pipeline/build/clearly-defined/check-clearly-defined.ps1
This keeps the ClearlyDefined script up to date with changes made in the web repository, where the script needed to exclude dependabot PRs updating the playwright docker image.
keep the ClearlyDefined script in sync with web, per https://github.com/microsoft/accessibility-insights-web/pull/6917 
> Note: After the PR has been created, certain checks will be kicked off. All of these checks must …
> chore: Update clearly defined script to exclude docker dependabot pull requests

- src/AccessibilityInsights.SharedUxTests/Settings/AppLayoutTests.cs
- src/AccessibilityInsights.SharedUxTests/Settings/ConfigurationModelTests.cs
- src/AccessibilityInsights.SharedUxTests/Settings/LayoutTests.cs
- src/AccessibilityInsights.SharedUxTests/ViewModels/ViewModelTests.cs
I noticed today that the `AppLayoutTests` were not running as expected. In investigating, I found the following, which are fixed in this PR:
- The `AppLayoutTests.ClassInitialize` method needs to take a `TestContext` as a parameter--this is why the tests were being discovered but were not being run
- The `TestClass`, `TestMethod`, `ClassInitialize`, and `ClassCleanup` decorators aren't intended to have parentheses. They still work with the parentheses, but it is a nonstandard representation. I fixed these wherever I found them (4 test classes)
Test coverage and consistency
- [n/a] Does this address an existing issue? If yes, Issue
- [n/a] Attach any …
> chore: Fix test irregularities

- docs/TelemetryDetails.md
- src/AccessibilityInsights.SharedUx/Settings/ConfigurationConstants.cs
- src/AccessibilityInsights.SharedUx/Settings/ConfigurationModel.cs
- src/AccessibilityInsights.SharedUx/Telemetry/TelemetryProperty.cs
- src/AccessibilityInsights.SharedUxTests/Resources/ConfigSettings.json
- src/AccessibilityInsights.SharedUxTests/Settings/ConfigurationModelTests.cs
- src/AccessibilityInsights/MainWindowHelpers/Initialize.cs
- src/AccessibilityInsights/MainWindowHelpers/StateMachine.cs
- src/AccessibilityInsights/Misc/TelemetryEventFactory.cs
Provide an option to include Chromium HTML content in test results. This is intentionally _not_ exposed in the UI, as this is intended uniquely for browser development teams who can reasonably edit their config file by hand. To enable this functionality, do the following:
1. Run Accessibility Insights for Windows at least once, then exit the program. This will create the config file.
2. Using your preferred text editor, edit `%localappdata%\AccessibilityInsights\V1\Configurations\Configuration.json`
3. Add the following line in the json--not at the bottom of the file or the comma will be off
```
"ShouldTestAllChromiumContent": true,
```
4. Save the JSON file
5. Restart Accessibility Insights for Windows
Chromium HTML content will now be included in rule checks.
Since we aren't supporting …
> chore: Enable chromium content scanning (advanced feature, not for general use)

- src/AccessibilityInsights.Extensions.AzureDevOps/Extensions.AzureDevOps.csproj
- src/AccessibilityInsights.Extensions.AzureDevOps/ForcedDependencies.cs
- src/MSI/Product.wxs
ADAL (Active Directory Authentication Library) is being replaced by MSAL (Microsoft Authentication Library) across all products. Our auth is a transitive dependency of the Visual Studio client assemblies, so our upgrade path is to to upgrade the Visual Studio client packages. These packages are still in preview with no publicly announced ETA for the full release, but there are reasons to make this change sooner, rather than later. In conversations with the teams that own the Visual Studio packages, no significant changes are expected between now and the fully released issues, so we're making the change now.
Change was tested by building an MSI, installing it on a machine, and ensuring that ADO bug filing works as expected.
Complete update requirement
- [n/a] Does this address an existing …
> Chore: Migrate from ADAL to MSAL

- src/AccessibilityInsights/App.config
.NET Framework 4.8.1 included several accessibility-related fixes that we want to enable in our code. They're disabled by default, so we need to update the `app.config` file to give .NET Framework permission to use the updated behavior. No bugs have been files on these, so this is a bit of a preemptive strike.
Leverage accessibility improvements where they're available to us.
> chore: Enable .NET Framework 4.8.1 accessibility fixes

- .github/dependabot.yml
Dependabot for our repos is scheduled to run at fairly different times that are inconvenient for some geographies. This PR moves this repo's dependabot time to 08:30 UTC (14:00 IST, 01:30 PDT, 00:30 PST).
Part of [Feature 2083093](https://mseng.visualstudio.com/1ES/_queries/edit/2083093) (internal access required to view).
> feat(oncall-vendor-transition): Move Dependabot to 08:30 UTC

- .github/dependabot.yml
Add a leading zero to the time in the Dependabot config.
> Chore: Fix Dependabot config

- tools/scripts/pipeline/build/clearly-defined/ValidateScript.bat
- tools/scripts/pipeline/build/clearly-defined/check-clearly-defined.ps1
Bring ClearlyDefined tooling in sync with https://github.com/microsoft/accessibility-insights-web/pull/7046 and https://github.com/microsoft/accessibility-insights-web/pull/7055. 
Keep duplicated files in sync since we don't yet have a single place to store these
> chore: Sync latest ClearlyDefined changes

- src/Manifest/Manifest.csproj
- tools/scripts/create-json-for-manifest.ps1
The script to create the release manifest file requires the fully qualified path to the Octokit package. This path used to get passed in as the `OctokitPath` parameter, and the calling code assumed the default cache location. This assumption was recently invalidated in the signed build pipeline, so the pipeline broke.
With this change, the passed-in parameter is now renamed to `OctokitRelativePath` and represents the _relative_ path from the cache root to the Octokit package, The script chooses the cache root location based on the `NUGET_PACKAGES` environment variable (see [docs](https://learn.microsoft.com/en-us/nuget/consume-packages/managing-the-global-packages-and-cache-folders)). If this variable is set, then it is used as the cache root location; otherwise the default cache root …
> fix: Allow nuget cache location override when building manifest

- docs/ChangingVersions.md
- src/ManifestTests/IntegrationTests.cs
- tools/scripts/create-json-for-manifest.ps1
This PR fixes a structural (but non-functional) bug associated with building mandatory prod updates. I also realized that this behavior wasn't documented anywhere, so I added an extra bit to the docs. The integration test that runs during the build now verifies that the generated value for production minimum version is correct based on the `IsMandatoryProdUpdate` environment variable.
I ran 3 validation builds:
1. When `IsMandatoryProdUpdate` = "Dave", the build fails in the integration tests. Log output ([link](https://mseng.visualstudio.com/1ES/_build/results?buildId=24503522&view=logs&j=06f1c8b2-7bb0-5c49-9f03-01a8f16e24cf&t=acaf2a90-5d04-5dbb-0d6a-3dcb39127913&l=4438)):
```
Failed EmbeddedManifestMatchesRawManifest [172 ms]
Error Message:
Assert.IsTrue failed. The …
```
> Chore: Add fix & docs for mandatory prod update

- src/AccessibilityInsights.Extensions.AzureDevOps/Extensions.AzureDevOps.csproj
[CVE-2024-21319](https://msrc.microsoft.com/update-guide/vulnerability/CVE-2024-21319) has been identified as a low risk DOS vulnerability. It is fixed in ADO libraries 7.1.2. Normally we'd let dependabot do this for us, but we ran into some complications that require a manual PR. The changes here made using the "Manage Nuget Packages for Solution" tool built into VisualStudio
Address [CVE-2024-21319](https://msrc.microsoft.com/update-guide/vulnerability/CVE-2024-21319)
> chore: Update ado libraries to version 7.1.2

- src/AccessibilityInsights.SharedUx/Controls/HierarchyControl.xaml
- src/AccessibilityInsights.SharedUx/Resources/Dark/Brushes.xaml
- src/AccessibilityInsights.SharedUx/Resources/HighContrast/Brushes.xaml
- src/AccessibilityInsights.SharedUx/Resources/Light/Brushes.xaml
As called out in #1758, the search box doesn't meet non-text color contrast requirements. This PR changes the border so that it's consistently displayed in all themes.
Address #1758
Mode | Before (only dark mode has border) | After (all modes have border)
Light | ![image](https://github.com/microsoft/accessibility-insights-windows/assets/45672944/84b2dab8-afa1-4179-9acd-95f77d80a226) | ![image](https://github.com/microsoft/accessibility-insights-windows/assets/45672944/183dff19-de12-4db9-899d-02523fd44086)
Dark | ![image](https://github.com/microsoft/accessibility-insights-windows/assets/45672944/91c498c7-f64c-4dff-8948-2a2cf91fb8db) | ![image](https://github.com/microsoft/accessibility-insights-windows/assets/45672944/67eb11c7-7904-4ccb-a549-d8c74f0c235a)
Aquatic | …
> fix: Make the search box border consistent in all themes

- build/signedbuild.yml
- tools/scripts/pipeline/deploy/Canary/set_variables.ps1
This PR is for migrating Microsoft.accessibility-insights-windows(signed) pipeline to 1ES MicroBuild Template.
Old run link: https://dev.azure.com/mseng/1ES/_build/results?buildId=25829770&view=results
New run link: https://dev.azure.com/mseng/1ES/_build/results?buildId=25906954&view=results
Below are details:
1. We have to keep running compliance jobs as we are running TSA upload task. Currently 1ES template do not support dynamic TSA config file.
2. Binskim task is running twice in Signed Release job. One is auto injected by 1ES template and another one we added manually for TSA Upload. 1ES template do not support TSA upload for specific job in the pipeline. If we enable TSA in the template than it will inject TSA task in all the jobs including source SDL job. We cannot enable TSA for …
> feat(Pipeline Migration to 1ES Template): migrated signed build to 1ES micro build template

- build/prbuild.yml
1ES PT adds tags to pipeline runs using the access token provided by ADO. In the case of pipeline runs against forked repos of a GitHub repo, the access token does not have Edit build quality permissions and hence cannot add tags. To unblock those pipelines, skipped tagging by using the option SkipBuildTagsForGitHubPullRequests.
Verified that the only change in the pipeline run is that it do not add "1ES.PT.Unofficial" tag on the Run. In place of that it adds below warning message.
##[warning]1ES PT Warning: Skipping build tags as this build is a pull request form github which does not have permissions to add tags.
- [na] Run through of all [test scenarios](https://github.com/Microsoft/accessibility-insights-windows/blob/main/docs/Scenarios.md) completed?
- [na] Does this address an …
> fix: Added skip tag setting for 1ESPT tags in PR run

- .github/dependabot.yml
- .github/policies/resourceManagement.yml
- build/NetFrameworkAll.targets
- build/NetFrameworkRelease.targets
- build/NetFrameworkTest.targets
- build/build-and-unit-tests.yml
- build/check-dependencies.yml
- build/common.targets
- build/delaysign.targets
- build/prbuild.yml
- build/settings.targets
- build/signedbuild.yml
- build/ui-test-job.yml
- tools/scripts/verification.scripts/LicenseHeaderVerification.ps1
While updating to 1ES pipeline templates, we realized that several of our files were missing copyright headers. This adds them and updates the tooling to ensure that we don't miss them in these files types in the future. Copyright headers were all added by running the script.
The policy service file can't have comments without breaking the bot, so an exception is made for any files under `.github\policies`.
Address #1761  …
> fix: Add license headers to .yml and .targets files

- src/MSI/MSI.wixproj
Update WixToolset to address [CVE-2024-29188](https://github.com/advisories/GHSA-jx4p-m4wm-vvjg). This will fix CG issue https://dev.azure.com/mseng/1ES/_workitems/edit/2162324
CVE
> chore: Updated Wix packages to 4.0.5

- src/AccessibilityInsights.SharedUx/Properties/Resources.Designer.cs
- src/AccessibilityInsights.SharedUx/Properties/Resources.resx
Fix a typo in the property picker's filter hint.
> Fix: Fix typo in filter text

- src/AccessibilityInsights.Extensions.AzureDevOps/Extensions.AzureDevOps.csproj
Updated Microsoft.Identity.Client to 4.61.2 to address https://github.com/advisories/GHSA-x674-v45j-fwxw. This will fix CG issue https://dev.azure.com/mseng/1ES/_workitems/edit/2169693
CVE
> chore: Updated Microsoft.Identity.Client to 4.61.2

- src/AccessibilityInsights.Extensions.AzureDevOps/Extensions.AzureDevOps.csproj
Updated System.Text.Json to 8.0.4 to address https://github.com/advisories/GHSA-hh2w-p6rv-4g7w. This will fix CG issue https://dev.azure.com/mseng/1ES/_workitems/edit/2195381
Along with this updated its root dependencies to latest.
CVE
- [na] Run through of all [test scenarios](https://github.com/Microsoft/accessibility-insights-windows/blob/main/docs/Scenarios.md) completed?
- [na] Includes UI changes?
- [na] Run the production version of Accessibility Insights for Windows against a version with changes.
- [na] Attach any screenshots / GIF's that are applicable.
> chore: Updated System.Text.Json to 8.0.4

- src/AccessibilityInsights.SharedUx/SharedUx.csproj
- src/UITests/UITests.csproj
Janitorial: Ingest latest Axe.Windows manually, since Dependabot isn't detecting the update.
> chore(deps): Bump Axe.Windows to 2.4.1

- src/AccessibilityInsights.SharedUx/Controls/TestTabs/TabStopControl.xaml.cs
Similar to that implemented for event recording, this PR adds an audio cue when the tab stops test is toggled and "provide feedback with sound" is enabled.
Addresses #1833.
This PR does duplicate a small quantity of code, but this is not unprecedented for the project.
> feat(audio-feedback): Add sound feedback when starting and stopping "tab stops" test

- .github/dependabot.yml
Dependabot stopped generating new PRs and logs show no project found. 
```
/opt/nuget/NuGetUpdater/NuGetUpdater.Cli discover --repo-root /home/dependabot/dependabot-updater/repo --workspace / --output /tmp/.dependabot/discovery.1.json --verbose
updater | Discovering build files in workspace [/home/dependabot/dependabot-updater/repo].
No dotnet-tools.json file found.
No global.json file found.
Discovering projects beneath [.].
No project files found.
Central Package Management is not enabled.
Discovery complete.
updater | 2024/07/12 08:09:07 INFO <job_854906625> Discovery JSON content: {
"Path": "",
"IsSuccess": true,
"Projects": [],
"DirectoryPackagesProps": null,
"GlobalJson": null,
"DotNetToolsJson": null
}
```
Implementing fix as per …
> fix: updated dependabot.yml directory to check for projects

- src/AccessibilityInsights.Extensions.AzureDevOps/Extensions.AzureDevOps.csproj
- src/MSI/Product.wxs
- src/MsiFileTests/WxsValidationTests.cs
Updated System.Text.Json to 8.0.5 to address https://github.com/advisories/GHSA-hh2w-p6rv-4g7w. This will fix CG issue https://dev.azure.com/mseng/1ES/_workitems/edit/2221678/?view=edit
Along with this updated its root dependencies to latest.
**NOTE: After updating the version, test case was failing in pipeline with below error**
**Error Log:**
Failed AllDropFilesAreAccountedFor [136 ms]
**Error Message:**
Assert.IsFalse failed. 1 drop files are missing from "ProductComponent" of WXS: Microsoft.Bcl.TimeProvider.dll
**Stack Trace:
at MsiFileTests.WxsValidationTests.CompareWxsSectionToDropPath(String repoRoot, String relativeDropPath, String wxsFile, String wxsComponentId, HashSet`1 intentionalExclusions) in D:\a\_work\1\s\src\MsiFileTests\WxsValidationTests.cs:line 48
at …
> CG work item fix for System.Text.JSON package

- build/signedbuild.yml
This is new pre release version used in 1ES pipeline templates. But our TSA upload task still uses the older version (1.9.5) so this conflict is resulting into pipeline failure.
For now updating pipeline to optout for new version.
There will be separate work item to update binskim to 4.3.1 version as new rules in 4.3.1 might discover issues which also need to be resolved so that pipeline does not break.
> chore: update binskim to optout 4.3.1 version

- src/AccessibilityInsights.SharedUx/Controls/HierarchyControl.xaml
Added tooltip to the search field in "Live Inspect" to allow users to keep referring to it while they fill out the input field.
Below is screenshot for change (blue arrow is for reference and not included in UI)
adresses issue #1757
> fix: adding tooltip to search field

- src/AccessibilityInsights.SharedUx/Controls/ColorPicker/ColorPickerControl.xaml
The input labels in the color picker do not have sufficient contrast with the background when using the dark theme. This PR fixes the issue.
Theme | Screenshot
--- | ---
Windows(Light) | ![Screenshot 2025-04-03 161322](https://github.com/user-attachments/assets/8b9bfbd4-3ce0-42f0-8936-925979993e9c)
Windows(Dark) | ![Screenshot 2025-04-03 161032](https://github.com/user-attachments/assets/edce14cd-7bd9-47c5-a40c-97d338833faa)
Aquatic | ![Screenshot 2025-04-03 161130](https://github.com/user-attachments/assets/8fce8456-f1af-4405-988f-e7301a3026cb)
Dessert | ![Screenshot 2025-04-03 161200](https://github.com/user-attachments/assets/ea36b526-59cb-4e4b-b5fc-5cca6b3281cc)
Dusk | ![Screenshot 2025-04-03 161228](https://github.com/user-attachments/assets/36e69368-be05-4766-85c3-b121ac63386f) …
> fix: enable text color in color picker to change based on windows theme
